### ISSUE TITLE
[New object / Warnings] when creating a new object from the list, 3 errors with no text appear. However, the object and all parameters are added correctly.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#1907]
yammer 1175
New object / Warnings

when creating a new object from the list, 3 errors with no text appear. However, the object and all parameters are added correctly.

https://user-images.githubusercontent.com/67378322/106476687-fce73f80-64af-11eb-8b13-6a83ab3a8f6e.mp4

**Comment by mariiao98** [comment]
The bug could not be reproduced.
