### ISSUE TITLE
[Websites / Settings] add an account selection to the site configuration to receive referral commissions. This account should be indicated as a referral for the site in the event that the user is not tied to other referrals

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#1924]
yammer 1160
Websites / Settings

add an account selection to the site configuration to receive referral commissions. This account should be indicated as a referral for the site in the event that the user is not tied to other referrals

Referral payments
The website owner may receive referral commissions when users claim their rewards through the website. 
Account for referral payments:
The terms for referral commissions are defined by the Campaign Management Services used by sponsors to launch their campaigns.
![2021-02-02_15-32](https://user-images.githubusercontent.com/67378322/106607393-ee5e5e00-656b-11eb-9b0a-2e527c3a67d7.png)

**Comment by Fesmofet** [comment]
`const json = JSON.stringify({
    **host**: 'host.com',
    **account**: 'flowmaster'
});

await client.broadcast.json({
      **id**: 'website_referral_payments',
      json,
      required_auths: [],
      required_posting_auths: [**owner**]
    }, **privateKey**)
`
**account** - account for referral payments
**host** - app host
**owner** - app owner
**privateKey** - private key

**Comment by Diana-Cherry-8** [comment]
Add text.

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Add **host** in json_metadata
does not work without it. The added referral in the settings is not taken into account after writing a review

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Two reviews in a row from the same user, site, campaign, one was credited to the referral agent of the site, the second was not, in the second the host did not go

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
