### ISSUE TITLE
[Object menu / News] when adding a News button, you need to 1. add the News title field so that the user can specify the name of the button and 2. when objects are selected, make the selection field wider (otherwise it is not clear which object)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#1976]
**Back task** https://github.com/Waiviogit/waivio/issues/2225

yammer 1114
Object menu / News

when adding a News button, you need to 
1. add the News title field so that the user can specify the name of the button 
2. when objects are selected, make the selection field wider (otherwise it is not clear which object)
![2021-02-05_13-51](https://user-images.githubusercontent.com/67378322/107030418-4fc73c80-67b9-11eb-85bc-f7d42479d4b3.png)

Comment (back):
В верхнем меню не надо ничего добавлять. Вверху остается только Reviews, который показывает только посты со ссылкой на данный объект (как и для всех остальных объектов).

А кнопки класса news просто показываются в левой колонке (About секции), наравне со всеми другими кнопками (page, list, button, etc.) Если news кнопку с помощью custom sorting поставили на первое место в левой колонке, то при начальном открытии объекта в средней колонке покажется соответствующий news feed.

**Comment by mariiao98** [comment]
1,5h

**Comment by Diana-Cherry-8** [comment]
Replace filter with title in placeholder - "News title"
![2021-03-22_17-01](https://user-images.githubusercontent.com/67378322/112010877-612d9380-8b30-11eb-81d1-7be4ef80ee73.png)

**Comment by Diana-Cherry-8** [comment]
Doesn't work

https://user-images.githubusercontent.com/67378322/112286885-77ecfb00-8c94-11eb-82ac-d923db4062af.mp4

**Comment by Diana-Cherry-8** [comment]
Если не вводить имя, то отображается null, и можно создать только один раз
![2021-03-25_11-51](https://user-images.githubusercontent.com/67378322/112453709-9fa99500-8d60-11eb-833f-d2d18026e656.png)

**Comment by Diana-Cherry-8** [comment]
when approving a reject, all news filters in the left sidebar disappear, after refreshing the page, the necessary ones are displayed



https://user-images.githubusercontent.com/67378322/112952264-f8a07100-9144-11eb-861c-364bd182c1c1.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Add Russian translation
![2021-03-30_13-39](https://user-images.githubusercontent.com/67378322/112976356-6f496880-915d-11eb-9b3f-8bbfde7ccbbe.png)

**Comment by Diana-Cherry-8** [comment]
fields are displayed to the full width of the modal window
![2021-03-30_15-21](https://user-images.githubusercontent.com/67378322/112987744-b9394b00-916b-11eb-9e38-a362309d970f.png)

**Comment by Diana-Cherry-8** [comment]
you can't press the button
![2021-03-31_11-27](https://user-images.githubusercontent.com/67378322/113114582-26082000-9214-11eb-9609-2cf10776d5e6.png)

**Comment by Diana-Cherry-8** [comment]
Новостной фильтр отображает не то
https://waiviodev.com/object/hgq-bird-bar-888/updates
![2021-03-31_16-20](https://user-images.githubusercontent.com/67378322/113150888-354f9380-923d-11eb-935a-b8d54ab02d1b.png)
![2021-03-31_16-22](https://user-images.githubusercontent.com/67378322/113150952-4b5d5400-923d-11eb-90c7-4a770b885ff2.png)

**Comment by Diana-Cherry-8** [comment]
you can't press the button https://waiviodev.com/object/psw-test-news/newsFilter/mnbmnb87-71f4w0lk5tv

https://user-images.githubusercontent.com/67378322/113256103-611c5900-92d1-11eb-9433-d6d379ecdc7b.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Счетчик новостного фильтра добавляет что-то еще (форм?)
![2021-04-01_14-46](https://user-images.githubusercontent.com/67378322/113289652-275f4880-92f9-11eb-87ba-3538c0cb9c5f.png)

**Comment by Diana-Cherry-8** [comment]
Новостные фильтры не работают на сайтах
https://www.waivio.com/object/yue-test-bar/newsFilter/wiv01-jqr6qvnij4a

https://user-images.githubusercontent.com/67378322/113297331-292e0980-9303-11eb-96c7-29c4a43bea3e.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
