### ISSUE TITLE
[Object menu / Forms] a group of form buttons is added to the menu on objects, when clicked, nested forms (external link or widget) open

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#1977]
yammer 1117
Object menu / Forms

a group of form buttons is added to the menu on objects, when clicked, nested forms (external link or widget) open
https://github.com/Waiviogit/waivio/issues/1782

Comment from back:
добавить Form в exposed fields
db.objecttypes.update({name :{$in: ["crypto", "product", "place", "business", "service", "company", "person", "hotel", "restaurant"]}},{ $addToSet: { exposedFields: { $each: ["blog", "form"] } } },false,true)

**Comment by Diana-Cherry-8** [comment]
Add the word "title" to Form placeholder
![2021-03-09_16-37](https://user-images.githubusercontent.com/67378322/110486918-c6779280-80f5-11eb-8345-0b96d9b6c3b9.png)

![2021-03-09_16-34](https://user-images.githubusercontent.com/67378322/110486864-b9f33a00-80f5-11eb-8cb2-652fa9a91671.png)

**Comment by Diana-Cherry-8** [comment]
Edit error under form title field
Actual result: Short description is required
Expected result: Title is required
![2021-03-09_16-39](https://user-images.githubusercontent.com/67378322/110487369-30903780-80f6-11eb-83b8-f2cd3a4a601c.png)

**Comment by Diana-Cherry-8** [comment]
No form name in post
![2021-03-09_16-43](https://user-images.githubusercontent.com/67378322/110487827-9f6d9080-80f6-11eb-8fec-099b929c0ec4.png)

**Comment by Diana-Cherry-8** [comment]
Forms in the left sidebar are displayed only in edit mode
![2021-03-09_16-44](https://user-images.githubusercontent.com/67378322/110488108-dd6ab480-80f6-11eb-8a5b-dc883f316332.png)
![2021-03-09_16-44_1](https://user-images.githubusercontent.com/67378322/110488116-df347800-80f6-11eb-9ad1-bb79351a82ac.png)

**Comment by Diana-Cherry-8** [comment]
Not displayed in custom sorting
![2021-03-09_16-46](https://user-images.githubusercontent.com/67378322/110488295-055a1800-80f7-11eb-9ce6-446945ece99f.png)

**Comment by Diana-Cherry-8** [comment]
Extend the display area if the form is full screen and on middle + right
![2021-03-09_17-10](https://user-images.githubusercontent.com/67378322/110492057-836bee00-80fa-11eb-9837-d1f0c75cf2a2.png)

**Comment by Diana-Cherry-8** [comment]
Change the placeholder and increase the margin for the widget
![2021-03-09_17-16](https://user-images.githubusercontent.com/67378322/110493147-3ccac380-80fb-11eb-854b-112ba6d732d9.png)

**Comment by Diana-Cherry-8** [comment]
Сделать плейсхолдер как на макете: уменьшить шрифт, текст Paste code
![2021-03-09_17-16](https://user-images.githubusercontent.com/67378322/110493147-3ccac380-80fb-11eb-854b-112ba6d732d9.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Виджет записывается в поле link, поэтому не отображаеться

**Comment by mariiao98** [comment]
1,5 hour

**Comment by Diana-Cherry-8** [comment]
Если не ввести тайтл поле не подчеркивается, и нужно дописать в уведомлении Form title is required 
Раньше оно ж было так https://github.com/Waiviogit/waivio/issues/1977#issuecomment-793985170

**Comment by Diana-Cherry-8** [comment]
вопрос - почему нельзя вставить виджет вейвио в форм ?)
<iframe src="https://waivio.com/rewards/all/?display=widget&userName=someUserName&ref=wiv01" height="400" width="350" style="border: none;">Can't load Rewards widget.</iframe>

**Comment by Diana-Cherry-8** [comment]
Задело поле для линки и виджета
![2021-03-31_15-57](https://user-images.githubusercontent.com/67378322/113147767-ccb2e780-9239-11eb-816d-a84e27c0736c.png)

**Comment by Diana-Cherry-8** [comment]
cards must be with an active toggler, independent of each other

https://user-images.githubusercontent.com/67378322/113148615-b5282e80-923a-11eb-9332-852671e8eafa.mp4

**Comment by Diana-Cherry-8** [comment]
remove the scroll if there is no need for it for the widget
![2021-03-31_17-18](https://user-images.githubusercontent.com/67378322/113159336-34226480-9245-11eb-8e9b-f73944e2e229.png)

**Comment by Diana-Cherry-8** [comment]
Пост апдейт не появляться

https://user-images.githubusercontent.com/67378322/113270250-f1fb3080-92e1-11eb-9a72-dd699de97ddf.mp4

**Comment by Diana-Cherry-8** [comment]
Вместо имени формы отображается form
![2021-04-01_12-01](https://user-images.githubusercontent.com/67378322/113270406-1bb45780-92e2-11eb-941c-e9fe7f906f9e.png)

**Comment by Diana-Cherry-8** [comment]
Формы не отображаются, вечный спинер
![2021-04-01_12-03](https://user-images.githubusercontent.com/67378322/113270602-54ecc780-92e2-11eb-9a8d-3e8f33d3f5dc.png)

**Comment by Diana-Cherry-8** [comment]
Модалка для формы пустая
![2021-04-01_15-09](https://user-images.githubusercontent.com/67378322/113291797-3693c580-92fc-11eb-99ec-00d6ec016151.png)

**Comment by Diana-Cherry-8** [comment]
Add information about the link or widget to the post comment, as after adding a button for example
![2021-04-02_09-24](https://user-images.githubusercontent.com/67378322/113388276-99d23600-9396-11eb-8a62-3dfad87d2544.png)

**Comment by Diana-Cherry-8** [comment]
Пост апдейты для формы не записывается в свою фиду
![2021-04-05_13-02](https://user-images.githubusercontent.com/67378322/113562805-6c43f180-960f-11eb-9c1b-4d651d71921c.png)
![2021-04-05_13-03](https://user-images.githubusercontent.com/67378322/113562809-6e0db500-960f-11eb-8b8f-23f2fc6de155.png)

**Comment by Diana-Cherry-8** [comment]
Форму нельзя проскролить https://waiviodev.com/object/pvx-test-map/form/fgh87-c3fb6reg32g
![2021-04-05_13-05](https://user-images.githubusercontent.com/67378322/113562939-9f868080-960f-11eb-94ad-6b8d090b4336.png)

**Comment by Diana-Cherry-8** [comment]
Форма с таким виджетом не отображается https://waiviodev.com/object/pvx-test-map/form/fgh87-ek8h9z6pzyu
<script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-55ff4a60-8da2-4a1d-8979-a68d8ecbf206"></div>

![2021-04-05_13-06](https://user-images.githubusercontent.com/67378322/113563124-d361a600-960f-11eb-9cd1-3ee02786fbbb.png)

**Comment by Diana-Cherry-8** [comment]
![2021-04-06_16-14](https://user-images.githubusercontent.com/67378322/113716468-4db72680-96f3-11eb-8c99-8a059814237c.png)

**Comment by Diana-Cherry-8** [comment]
Right 
![2021-04-06_16-42](https://user-images.githubusercontent.com/67378322/113720298-2a8e7600-96f7-11eb-8dd0-eabe89843601.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
