### ISSUE TITLE
[Websites] the map should show icons (objects) at a certain distance

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#1982]
**Front task** https://github.com/Waiviogit/waivio/issues/2232

- objects with campaigns are of higher priority, so they need to be shown on top
- do not display all objects so that the signs on the map do not overlap
- lower priority objects should not overlap higher priority

**Comment by Diana-Cherry-8** [comment]
Flooded for prod, waiting for the front

**Comment by Diana-Cherry-8** [comment]
**CLOSE**

**Comment by Fesmofet** [comment]
when there is no search string for the map, send mapMarkers: true

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
