### ISSUE TITLE
[Campaigns / Payables] in order for the sponsor to control late payments (after 21 days - in orange): 1. Add the number of days to each line, 2. filters 7/14/21 days, 3. show orange (!) if there is a delay> 21 days, 4. In the report, paint with words (Over ... days)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#1998]
**Back task** https://github.com/Waiviogit/waivio/issues/2347

yammer 1014
Campaigns / Payables

in order for the sponsor to control late payments (after 21 days - in orange): 1. Add the number of days to each line, 2. filters 7/14/21 days, 3. show orange (!) if there is a delay> 21 days, 4. In the report, paint with words (Over ... days)
![2021-02-10_10-46](https://user-images.githubusercontent.com/67378322/107486074-40ffd180-6b8d-11eb-8bef-5a5e42031094.png)

Comment from back: в response на payables добавлено поле notPayedPeriod - количество дней с последнего неоплаченного ревью

**Comment by Waiviogit** [comment]
https://waiviodev.com/campaigns-api/api-docs/#/Payables/get_payments_payable_warning

**Comment by Diana-Cherry-8** [comment]
Need to add  - days
![2021-04-01_12-50](https://user-images.githubusercontent.com/67378322/113276770-d6dfef00-92e8-11eb-923d-6b25099be3db.png)

**Comment by Diana-Cherry-8** [comment]
Display zero, if there is no debt
![2021-04-01_12-52](https://user-images.githubusercontent.com/67378322/113277234-2de5c400-92e9-11eb-94e1-c15489e96132.png)

**Comment by Diana-Cherry-8** [comment]
In Receivables, in table - over 23 displays
![2021-04-01_13-20](https://user-images.githubusercontent.com/67378322/113280551-1c062000-92ed-11eb-971e-2f3997c876ce.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
