### ISSUE TITLE
Social-info request with 404, after clicking on comment post in tab "Comments"

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2020]
**Severity**: Minor
**Steps to reproduce**:
1. Log in
2. Open your profile
3. Click on tab "Comments"
4. Click on comment post

**Expected result**: Social-info request with 200, after clicking on comment post in tab "Comments"
**Actual result**: Social-info request with 404, after clicking on comment post in tab "Comments"

https://user-images.githubusercontent.com/67378322/107744768-f496cc00-6d1b-11eb-9f66-6cd86a88ab7a.mp4

**Comment by mariiao98** [comment]
1h

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
