### ISSUE TITLE
Load the entire list of category filters

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2025]
![2021-02-15_09-17](https://user-images.githubusercontent.com/67378322/107916248-a88f9580-6f6e-11eb-9189-efbd86ebbf1c.png)

**Comment by Fesmofet** [comment]
https://waiviodev.com/api/docs/#/object_type/get_api_objectType_showMoreTags

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
