### ISSUE TITLE
Search for website

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2039]
**Related to** https://github.com/Waiviogit/waivio/issues/2065
Список поиска зависит от карты.
Например, 
карта с объектами
![2021-02-16_17-55](https://user-images.githubusercontent.com/67378322/108087595-44f58d00-7080-11eb-94f4-82b687e9cb2a.png)

в списке должны быть те объекты, что на карте в данный момент
![2021-02-16_17-56](https://user-images.githubusercontent.com/67378322/108087732-65254c00-7080-11eb-93d2-5faa0d791ff0.png)

пользователь переместился на карте - и у него погрузились объекты, те что на карте видны
для того чтобы можно было легче показать актуальный список объектов (без ранее загруженных), есть кнопка reload,  после нажатия на кнопку reload - обновляться список, и в нем отображаются актуальный список объектов, которые отображаются на карте в данный момент   

результаты поиска зависит от типа объектов и фильтров

сортировка объектов по весу

**Comment by Fesmofet** [comment]
new doc on search
https://waiviodev.com/api/docs/#/wobject/post_api_wobjectSearch

**Comment by Diana-Cherry-8** [comment]
При сдвиге карты - если список закончился с предыдущего место, то отображается кнопка reload с новым списком

https://user-images.githubusercontent.com/67378322/109782578-b4878280-7c11-11eb-95a7-1e50941e6763.mp4

Список отображается с учетом территории которая закрыта поисковой панелью
![2021-03-03_11-15](https://user-images.githubusercontent.com/67378322/109782746-e3055d80-7c11-11eb-80a8-884d9db89922.png)

**Staging checked**

**Comment by Diana-Cherry-8** [comment]
![2021-03-11_18-03](https://user-images.githubusercontent.com/67378322/110911055-db813b00-831a-11eb-94f7-1cdfcfbdd5af.png)

**Comment by Diana-Cherry-8** [comment]
Duplicate in rewards

https://user-images.githubusercontent.com/67378322/110943399-d684b180-8343-11eb-8ccb-026453c493f3.mp4

**Comment by Diana-Cherry-8** [comment]
**Production checked**
