### ISSUE TITLE
[Websites / Object (area)] when entering the Objects mode, you need to select such a scale and focus of the map to show all the specified areas for this site

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2040]
yammer 1163
Websites / Object (area)

when entering the Objects mode, you need to select such a scale and focus of the map to show all the specified areas for this site
![2021-02-18_14-16](https://user-images.githubusercontent.com/67378322/108355805-f963f000-71f3-11eb-926a-cb696d057e75.png)

**Comment by Diana-Cherry-8** [comment]
Related to https://github.com/Waiviogit/waivio/issues/1923

**Comment by Fesmofet** [comment]
made changes to the request
https://waiviodev.com/api/docs/#/sites/get_api_sites_map
now an object with an array of coordinates, center point and zoom is sent for correct display by the front

**Comment by Diana-Cherry-8** [comment]
**Staging chekcked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
