### ISSUE TITLE
[Campaigns / Manage] the sponsor has an active campaign but is not listed in the Active and Pending Campaigns list. Apparently there is a limit on the number of campaigns. One spore can launch up to 1,000 campaigns

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2045]
yammer 1224
Campaigns / Manage

the sponsor has an active campaign but is not listed in the Active and Pending Campaigns list. Apparently there is a limit on the number of campaigns. One spore can launch up to 1,000 campaigns
![2021-02-17_09-25](https://user-images.githubusercontent.com/67378322/108169954-20da9000-7102-11eb-90d4-3ec724761fea.png)

**Comment by Diana-Cherry-8** [comment]
Back checked everything is sent
Need to check if there is a limit in the display of campaigns

**Comment by LucyHrinishyna** [comment]
компания есть в списке, ее назвали -> Kitchen And Bar и она на активна.

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
