### ISSUE TITLE
[Guests / App beneficiary] now we do not take% from guest accounts, however, with the launch of sites, this policy will have to be changed and a standard commission should be collected (on Waivio - 3%, on websites - custom%)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2060]
yammer 1229
Guests / App beneficiary

now we do not take% from guest accounts, however, with the launch of sites, this policy will have to be changed and a standard commission should be collected (on Waivio - 3%, on websites - custom%)
![2021-02-19_09-03](https://user-images.githubusercontent.com/67378322/108469778-91fc7d80-7291-11eb-8596-36a5c653e626.png)

**Comment by Fesmofet** [comment]
at the moment when we are on waivio and the guest account is not linked to hive account we send {beneficiaries: [{account: "waivio.hpower", weight: 10000}]}
when the guest account is linked to hive  account - {beneficiaries: [{account: "linked account", weight: 9700}, {account: "waivio", weight: 300}]}

need to do:
**On waivio**
when the guest **account is linked** to hive account - we do not change anything beneficiaries: [{account: "linked account", weight: 9700}, {account: "waivio", weight: 300}]
guest **account is not linked** to hive account {beneficiaries: [{account: "waivio.hpower", weight: 9700}, {account: "waivio", weight: 300}]}

**On sites**
we take beneficiaries from this request (it should already be in the storage at the time of writing the post)
https://waiviodev.com/api/docs/#/sites/post_api_sites

when the guest **account is linked** to hive account {beneficiaries: [{account: "linked account", weight: 10000 - beneficiaries.percent}, {account: beneficiaries.account, weight: beneficiaries.percent}]}
guest **account is not linked** to hive account {beneficiaries: [{account: "waivio.hpower", weight: 10000 - beneficiaries.percent}, {account: beneficiaries.account, weight: beneficiaries.percent}]}

**Comment by Diana-Cherry-8** [comment]
https://github.com/Waiviogit/waivio/issues/2111 
Back problem

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
