### ISSUE TITLE
[dining.gifts / Reserved] on dining.gifts it is important to show how many active bookings a user has. To do this, in the upper right corner you need to make the "Reserved: __" button with a link to Rewards / Reserved

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2066]
**Related to** https://github.com/Waiviogit/waivio/issues/1963

yammer 1196
dining.gifts / Reserved

on dining.gifts it is important to show how many active bookings a user has. To do this, in the upper right corner you need to make the "Reserved: __" button with a link to Rewards / Reserved
![2021-02-19_11-27](https://user-images.githubusercontent.com/67378322/108485334-79965e00-72a5-11eb-9c12-765d0d3992f7.png)

**Comment by Fesmofet** [comment]
doc for new route
https://waiviodev.com/campaigns-api/api-docs/#/Campaign/get_campaigns_reserved_count

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
