### ISSUE TITLE
[Websites] Search filters

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2072]
- the whole list should be displayed

- filters are not displayed where there is no object

- tags must go in a separate word, for example, greek it is greek, but not another world where "greek" is part

![2021-02-22_09-09](https://user-images.githubusercontent.com/67378322/108674426-ebf97f00-74ed-11eb-9b1a-68a2e5580338.png)

**Comment by Fesmofet** [comment]
![2021-02-22_18-21](https://user-images.githubusercontent.com/59839789/108737081-e5452900-753a-11eb-839f-74d3e59bf972.png)
https://waiviodev.com/api/docs/#/object_type/post_api_objectTypes_tags_for_filter

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
