### ISSUE TITLE
[Posts / Video integration] if the post contains a link to a supported video, then it is replaced with an embedded video, however, if this link has a title, then leave it as a text link

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2085]
yammer 1235
Posts / Video integration

if the post contains a link to a supported video, then it is replaced with an embedded video, however, if this link has a title, then leave it as a text link
![2021-02-24_10-02](https://user-images.githubusercontent.com/67378322/108966837-614c8780-7687-11eb-8276-ae7cdab4b687.png)

**Comment by mariiao98** [comment]
2,5h

**Comment by Diana-Cherry-8** [comment]
**Production checked**
