### ISSUE TITLE
[Editor / Video links] an error occurs when adding a video link with the same link as the title

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2086]
yammer 1236
Editor / Video links

an error occurs when adding a video link with the same link as the title
![2021-02-24_10-03](https://user-images.githubusercontent.com/67378322/108966999-9953ca80-7687-11eb-859b-86b3a5ad9de7.png)

**Comment by mariiao98** [comment]
2h

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
