### ISSUE TITLE
[Profile / Filters] add filtering of posts by tags that are linked to posts. If possible, then filtering should be done both by hashtags and by objects to which there are links from posts

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2100]
**Notify back at runtime**

https://waiviodev.com/api/docs/#/user/post_api_user__userName__blog
yammer 1065
Profile / Filters

add filtering of posts by tags that are linked to posts. If possible, then filtering should be done both by hashtags and by objects to which there are links from posts
![2021-03-01_10-20](https://user-images.githubusercontent.com/67378322/109470176-c0d7d800-7a77-11eb-8087-805350a30970.png)

![image-20210118-152624](https://user-images.githubusercontent.com/67378322/111751426-2829c080-889d-11eb-93d6-c4ecbc1bc8ca.png)
![image-20210118-152654](https://user-images.githubusercontent.com/67378322/111751442-2f50ce80-889d-11eb-97c2-e1ee11b71678.png)
![image-20210118-152716](https://user-images.githubusercontent.com/67378322/111751455-32e45580-889d-11eb-9c90-445b6542772f.png)

**Comment by mariiao98** [comment]
3h

**Comment by Diana-Cherry-8** [comment]
Back https://github.com/Waiviogit/waivio/issues/2585

**Comment by Diana-Cherry-8** [comment]
Add filters on the other page user
![2021-05-18_09-30](https://user-images.githubusercontent.com/67378322/118602709-b0541580-b7bb-11eb-9fe9-f1ae4c5981d4.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Prodcution checked**
