### ISSUE TITLE
Add the display of cards rewards on search in tabs Drink, Dish, on the map, websites

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2113]
![2021-03-03_16-25](https://user-images.githubusercontent.com/67378322/109820933-237ad080-7c3e-11eb-9b11-d4e604c03de9.png)

"Если на один вторичный объект есть несколько предложений, пока просто показываем самый дорогой (желательно убедиться, что пользователь eligible на него).

Пока эта ситуация возникает редко, однако в будущем, спонсоры могут предлагать существенно большие вознаграждения influencres у которых много followers и нужно будет придумать интерфейсные решения для показа всех предложений (например, чтобы пользователи стремились получить больше followers или достичь определенный ранк, чтобы получать бОльшие вознаграждения)."

yammer 1251
dining.gifts / Dishes

if dish and drink have rewards, then their cards in the left column must match this
![2021-03-05_10-04](https://user-images.githubusercontent.com/67378322/110085755-2985c400-7d9a-11eb-8993-071740604fd5.png)

**Comment by Fesmofet** [comment]
The highest reward will be the first item in the propositions array. 
Sorting initially by highest reward then by object weight.
The display principle should be taken from the discover page

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
