### ISSUE TITLE
[Editor / Video] When inserting a video from Vimeo, an empty area is formed under the video, which cannot be deleted. This empty space remains after the post / page is published.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2116]
yammer 1248
Editor / Video

When inserting a video from Vimeo, an empty area is formed under the video, which cannot be deleted. This empty space remains after the post / page is published.
https://vimeo.com/519189256
![2021-03-04_10-01](https://user-images.githubusercontent.com/67378322/109930718-a187b780-7cd0-11eb-96c0-3f33706ce027.png)

**Comment by mariiao98** [comment]
1h

**Comment by Diana-Cherry-8** [comment]
Large indent appears after posting
![2021-03-23_11-08](https://user-images.githubusercontent.com/67378322/112121755-43137200-8bc8-11eb-9fef-f02660881b92.png)

**Comment by Diana-Cherry-8** [comment]
В превью не отображается title

https://user-images.githubusercontent.com/67378322/112305524-77aa2b00-8ca7-11eb-914c-6727201b9b3f.mp4

**Comment by Diana-Cherry-8** [comment]
В превью добавляется отступ
![2021-03-25_09-18](https://user-images.githubusercontent.com/67378322/112433548-163b9800-8d4b-11eb-91de-775f8b7bd247.png)
 В превью с видео ютуба также есть отступ
![2021-03-25_09-21](https://user-images.githubusercontent.com/67378322/112433887-8a763b80-8d4b-11eb-9625-bd2a74a124e6.png)

https://user-images.githubusercontent.com/67378322/112433899-8e09c280-8d4b-11eb-9a49-31fe56c895c3.mp4

**Comment by Diana-Cherry-8** [comment]
Title с видео vimeo не кликабельно
![2021-03-25_09-33](https://user-images.githubusercontent.com/67378322/112435270-2f454880-8d4d-11eb-8930-0d6304e032d1.png)

**Comment by Diana-Cherry-8** [comment]
В опубликованном посте отступ
![2021-03-25_13-00](https://user-images.githubusercontent.com/67378322/112462817-2a42c200-8d6a-11eb-96d5-fb059cc857d5.png)

**Comment by Diana-Cherry-8** [comment]
Если пост сделан hive пользователем, то впритык видео

**Comment by Diana-Cherry-8** [comment]
indentation
![2021-03-29_09-29](https://user-images.githubusercontent.com/67378322/112795648-7e52ec80-9071-11eb-9368-a1f20ebd34b3.png)

**Comment by Diana-Cherry-8** [comment]
В превью отступ
![2021-03-29_09-33](https://user-images.githubusercontent.com/67378322/112795901-de499300-9071-11eb-91b7-1254ed2f4551.png)

**Comment by Diana-Cherry-8** [comment]
Выравнять отступы
![2021-03-29_09-34](https://user-images.githubusercontent.com/67378322/112795981-fc16f800-9071-11eb-8375-214e0d985426.png)
![2021-03-29_09-35](https://user-images.githubusercontent.com/67378322/112796067-1a7cf380-9072-11eb-84fc-dc08eb9a6111.png)

**Comment by Diana-Cherry-8** [comment]
При добавлении видео через мобилку, отступы в редакторе и в превью

https://user-images.githubusercontent.com/67378322/112799009-747fb800-9076-11eb-9f8a-762e611891ea.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
