### ISSUE TITLE
[dining.gifts / Editor tags] on * .dining.gifts sites in the post editor, users should be allowed to add hashtags in addition to restaurants / dishes / drinks

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2142]
**Front task** https://github.com/Waiviogit/waivio/issues/2141

yammer 1259
dining.gifts / Editor tags

on * .dining.gifts sites in the post editor, users should be allowed to add hashtags in addition to restaurants / dishes / drinks
![2021-03-09_09-09](https://user-images.githubusercontent.com/67378322/110432334-a32df280-80b7-11eb-80c4-1492387ea6e3.png)

**Comment by Fesmofet** [comment]
added a new property to the request body - addHashtag. It must be used on sites when searching for hashtags for a post.

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
