### ISSUE TITLE
[Tools / New accounts] sale of VIP tickets to users to create new Hive accounts (HiveOnBoard.com)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2145]
**Back task** https://github.com/Waiviogit/waivio/issues/2146

yammer 1264
Tools / New accounts

sale of VIP tickets to users to create new Hive accounts (HiveOnBoard.com)
https://github.com/Waiviogit/waivio/issues/2138

**Comment by Fesmofet** [comment]
when buying tickets, after successful broadcast, you need to send a message over the socket
{"method": "subscribeTicket", "params": ["userName"]} 
Where userName - is name of authorized user
when tickets become available, the socket server will send a message
{"type":"vipTickets","notification":"parsed"}
after it use
https://waiviodev.com/api/docs/#/vipTickets/get_api_vip_tickets
to update tables


for ticket tables use request
https://waiviodev.com/api/docs/#/vipTickets/get_api_vip_tickets
to add note use
https://waiviodev.com/api/docs/#/vipTickets/patch_api_vip_tickets

**Comment by Diana-Cherry-8** [comment]
- Add dot after "Vip tickets" (2nd paragraph)
- Column "Add link" rename in "Link"
- Delete ":" in column name "VIP ticket" 
- Rename "share" in "Share" 


![2021-04-09_14-42](https://user-images.githubusercontent.com/67378322/114174812-d6c39d00-9941-11eb-9861-f390faab3241.png)

**Comment by Diana-Cherry-8** [comment]
Expected result: Note to self
Actual result: Note for self
in modal window "Share VIP ticket"
![2021-04-09_14-45](https://user-images.githubusercontent.com/67378322/114175139-56516c00-9942-11eb-91bd-400fecad2fbb.png)

**Comment by Diana-Cherry-8** [comment]
The table is floating with large text in the note
![2021-04-09_14-48](https://user-images.githubusercontent.com/67378322/114175445-b6481280-9942-11eb-84f3-ba6d4c06e96b.png)

**Comment by Diana-Cherry-8** [comment]
no top navigation menu
![2021-04-09_15-00](https://user-images.githubusercontent.com/67378322/114176902-6e29ef80-9944-11eb-9e8f-3654bd0ff219.png)

**Comment by Diana-Cherry-8** [comment]
Delete string "You can delegate some Hive Power to new accounts, follow them and welcome them to the community." 
since we do not have this functionality yet
![2021-04-09_15-03](https://user-images.githubusercontent.com/67378322/114177248-d8429480-9944-11eb-9fec-36343666d924.png)

**Comment by Diana-Cherry-8** [comment]
After clicking on notifications, tables become empty

https://user-images.githubusercontent.com/67378322/114179329-80595d00-9947-11eb-89fc-86ec31813a70.mp4

**Comment by Diana-Cherry-8** [comment]
eternal spiner for the guest user
![2021-04-09_16-06](https://user-images.githubusercontent.com/67378322/114184791-9f5aed80-994d-11eb-8613-df8da46de657.png)

**Comment by Diana-Cherry-8** [comment]
the tab Tools should be highlighted
![2021-04-12_14-34](https://user-images.githubusercontent.com/67378322/114388368-446b0580-9b9c-11eb-8332-92da8c79363b.png)

**Comment by Diana-Cherry-8** [comment]
the modal window does not open if the user does not have a linked account

https://user-images.githubusercontent.com/67378322/114389862-36b67f80-9b9e-11eb-8555-ea401a63902a.mp4

the modal window  opens with hive-user if the user  has a linked account

https://user-images.githubusercontent.com/67378322/114390110-8137fc00-9b9e-11eb-8f75-92db9f447202.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
