### ISSUE TITLE
[Editor / Remove object links] if you paste a link to an object, it will appear under the post; if the object is deleted, it will disappear; but if you do a reload or a number of other operations, it should not reappear under the post (as a result of parsing URLs)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2161]
yammer 1088
Editor / Remove object links

if you paste a link to an object, it will appear under the post; if the object is deleted, it will disappear; but if you do a reload or a number of other operations, it should not reappear under the post (as a result of parsing URLs)
![2021-03-09_10-46](https://user-images.githubusercontent.com/67378322/110443584-beebc580-80c4-11eb-8790-7f24817465b3.png)

(RU version) если paste линк на объект, то он появится под постом; если объект удалить, он пропадет; но если сделать reload или ряд других операций, он не должен вновь появляться под постом (в результате анализа URLs)

**Comment by mariiao98** [comment]
2,5h

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
