### ISSUE TITLE
[Editor / Videos] add support for videos from Bitchute and Rumble

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2164]
yammer 1078
Editor / Videos

add support for videos from Bitchute and Rumble
https://rumble.com/embed/v8ca18/?pub=4
https://www.bitchute.com/video/9hZ91UDX0V8/
![2021-03-09_10-59](https://user-images.githubusercontent.com/67378322/110445159-84832800-80c6-11eb-918a-d175f840d138.png)

**Comment by AndreyBelichenko** [comment]
5h

**Comment by Diana-Cherry-8** [comment]
Видео с rumble отображается как ссылка в превью и посте

https://user-images.githubusercontent.com/67378322/126278187-6d107a50-582a-4b69-9328-c395daeeca7d.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
