### ISSUE TITLE
[Editor / Add object] if the user typed the # symbol, then a dropdown opens immediately with a search for hashtags & objects (like in Discord); if the user selects an object, then it is inserted in the usual way, if there are no more entries, then we simply highlight the first word (up to the first space) as hashtag and continue typing

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2165]
yammer 1071
Editor / Add object

if the user typed the # symbol, then a dropdown opens immediately with a search for hashtags & objects (like in Discord); if the user selects an object, then it is inserted in the usual way, if there are no more entries, then we simply highlight the first word (up to the first space) as hashtag and continue typing
![2021-03-09_11-16](https://user-images.githubusercontent.com/67378322/110447446-e93f8200-80c8-11eb-983f-e109cf36fc60.png)

**Comment by Diana-Cherry-8** [comment]
Add the ability to add an object using #, as in twitter (and so that when you hover over the options, the cursor changes to a hand cursor)


https://user-images.githubusercontent.com/67378322/113106083-028ca780-920b-11eb-972b-357f87341170.mp4

**Comment by Diana-Cherry-8** [comment]
Драфты сохраняются заново

https://user-images.githubusercontent.com/67378322/125592792-5c6898df-4467-4f25-a554-4cd82c400380.mp4

**Comment by Diana-Cherry-8** [comment]
![2021-07-14_11-38](https://user-images.githubusercontent.com/67378322/125592811-4e9fea65-91e4-4934-8b0f-d5cd299dd8c3.png)

**Comment by Diana-Cherry-8** [comment]
Всплывает (мигает) превью предыдущего поиска, если добавить один объект, потом начать добавлять другой

https://user-images.githubusercontent.com/67378322/125594091-fae06d29-b79f-414f-a749-c08976bcdfac.mp4

**Comment by Diana-Cherry-8** [comment]
Курсор перебрасывается в конец если добавлять объект в середину

**Comment by Diana-Cherry-8** [comment]
Shift + # не работает 

https://user-images.githubusercontent.com/67378322/125606973-8158dc56-cfd3-4f1a-a87c-c9206a883bd5.mp4

**Comment by Diana-Cherry-8** [comment]
При 1м заходе, и если сразу писать #text, после выбора объекта, название объекта не подтягивается

https://user-images.githubusercontent.com/67378322/125616359-453ea343-670f-44c0-82d8-e4ce1b4d5712.mp4

**Comment by Diana-Cherry-8** [comment]
Курсор слитает 

https://user-images.githubusercontent.com/67378322/125627174-10ccd34d-3cab-4d6b-a8b9-6d1307921aee.mp4

**Comment by Diana-Cherry-8** [comment]
Удаляются линки, если сначала текстом вставить ссылку, сделать ее линкой с тем же адресом и потом вставить объект с помощью #

https://user-images.githubusercontent.com/67378322/125639627-5e676831-73e1-4c19-83ea-ebd7e80ce7cc.mp4

**Comment by OleksandrMosiichuk** [comment]
With selected text, the combination Shift+3 (for #) doesn't work

![image](https://user-images.githubusercontent.com/87119098/125747376-2dcbffe4-5744-47f1-9873-018621a7d8cb.png)

**Comment by OleksandrMosiichuk** [comment]
Если после # ввести пробелы, а потом текст для поиска - некоторые символы (по количеству пробелов) продублируются в виде обычного текста.

https://user-images.githubusercontent.com/87119098/125749600-6b1fd95d-71cf-4693-8ab0-dcdbadef3a2a.mp4

**Comment by Diana-Cherry-8** [comment]
Добавить добавления объекта с помощью Enter и проходку по списку с помощью стрелочек вверх, вниз 
**Expected result:**  как с поиска внизу

https://user-images.githubusercontent.com/67378322/125774328-e9c802d9-105b-4187-a2e4-177456bcf17d.mp4

**Comment by Diana-Cherry-8** [comment]
Если скролл не нужен, его не нужно показывать
![2021-07-16_09-36](https://user-images.githubusercontent.com/67378322/125903198-2b85e33e-976f-456e-8643-57ec7dc0308f.png)

**Comment by Diana-Cherry-8** [comment]
Карточка убирается, если добавить объект -> стереть его -> добавить еще один

https://user-images.githubusercontent.com/67378322/126117172-415160f8-7d03-49f2-9d15-d85261f0cd10.mp4

**Comment by Diana-Cherry-8** [comment]
> Карточка убирается, если добавить объект -> стереть его -> добавить еще один
> 
> **Expected result:** Карточки должны "накапливаться", если пользователь сам их не выключает тоглером
> 
>  vokoscreen-2021-07-19_10-03-36.mp4

Другая таска

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
