### ISSUE TITLE
[dining.gifts / Avatar] an avatar is not shown on the object, although it is visible on Waivio (and in the update text it is broken again). Perhaps some of the image formats do not work the same everywhere.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2198]
yammer 1266
dining.gifts / Avatar

an avatar is not shown on the object, although it is visible on Waivio (and in the update text it is broken again). Perhaps some of the image formats do not work the same everywhere.
https://www.waivio.com/object/diy-irish-heather-restaurant/updates/avatar
https://city.dining.gifts/object/diy-irish-heather-restaurant/menu#diy-irish-heather-restaurant-menu
![2021-03-10_09-01](https://user-images.githubusercontent.com/67378322/110589521-35e59480-817f-11eb-8bd8-7d92d31004c3.png)

**Comment by Fesmofet** [comment]
on waivio, the picture is displayed correctly, because there is a vandining account among the administrators. In the case when this account is not an administrator - another field wins with a bigger weight and with an old broken picture

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
