### ISSUE TITLE
[Rewards / Campaigns] when creating / editing campaigns, the list of secondary objects is trimmed to 27. The maximum should be much higher (500 or 1000) and when it is reached, the sponsor must be warned when trying to add the 501st (or 1001)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2238]
**Front task** https://github.com/Waiviogit/waivio/issues/2237

yammer 1277
Rewards / Campaigns

when creating / editing campaigns, the list of secondary objects is trimmed to 27. The maximum should be much higher (500 or 1000) and when it is reached, the sponsor must be warned when trying to add the 501st (or 1001)
![2021-03-16_09-26](https://user-images.githubusercontent.com/67378322/111271345-be5dac80-8639-11eb-8b7d-947f3264fdf2.png)

**Comment by Diana-Cherry-8** [comment]
NOT RELEVANT

**Comment by Diana-Cherry-8** [comment]
test hive-user 
Username: mnbmnb87
Password: 3QTSrLABtr9afDHHonPNRR6py3APeBAK

Campaign with a bunch of secondary objects
![2021-03-22_10-35](https://user-images.githubusercontent.com/67378322/111961971-6374fb00-8afa-11eb-94f9-a9ebf11f1052.png)

**Comment by Diana-Cherry-8** [comment]
You cannot create a duplicate campaign if it is in the status pending

https://user-images.githubusercontent.com/67378322/111963921-be0f5680-8afc-11eb-93e3-b4fcdbf1d37f.mp4

**Comment by Fesmofet** [comment]
https://waiviodev.com/api/wobject
request has limit option, default - 30
if you want  get objects by author_permlink array && array length > 30 set  limit option === array length

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
