### ISSUE TITLE
Twitter and Facebook opens in the same window after clicking on the repost

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2251]
**Severity**: Minor

**Steps to reproduce**:
1. Open feed
2. Do repost

**Expected result**: Twitter and Facebook opens in the new window after clicking on the repost
https://maxiproject.atlassian.net/browse/WAIV-2710 (here, video, as it was before)
**Actual result**: Twitter and Facebook opens in the same window after clicking on the repost

https://user-images.githubusercontent.com/67378322/111648617-38458f80-880c-11eb-9069-55f6feb85af3.mp4

**Comment by mariiao98** [comment]
1,5h

**Comment by Diana-Cherry-8** [comment]
The tab is closed after clicking on publish in the facebook editor

https://user-images.githubusercontent.com/67378322/112011970-722ad480-8b31-11eb-945a-78e30ba0a32e.mp4

**Comment by Diana-Cherry-8** [comment]
CLOSE

NOT RELEAVENT

**Comment by Diana-Cherry-8** [comment]
The tab is closed after clicking on publish in the facebook editor - facebook problem

**Comment by Diana-Cherry-8** [comment]
In modal window - share opens in new tabs

https://user-images.githubusercontent.com/67378322/112467086-44cb6a00-8d6f-11eb-9ae2-765885e5d29a.mp4

**Comment by Diana-Cherry-8** [comment]
Share opened in new window, in post, in modal window

https://user-images.githubusercontent.com/67378322/112467243-7cd2ad00-8d6f-11eb-9a73-5466f5351e88.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
