### ISSUE TITLE
Comments are not loaded on the post with object type (strange author name)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2255]
**Severity**: Major

**Steps to reproduce**:
1. Open http://waivio.com/@fgh87/hgq-bird-bar-888

**Expected result**: Comments are loaded on the post
**Actual result**: Comments are not loaded on the post
![2021-03-19_10-43_1](https://user-images.githubusercontent.com/67378322/111754231-6d032680-88a0-11eb-895e-da74d224cab5.png)
![2021-03-19_10-43](https://user-images.githubusercontent.com/67378322/111754242-6eccea00-88a0-11eb-802a-33416fb02256.png)

**Comment by mariiao98** [comment]
1h

**Comment by Diana-Cherry-8** [comment]
https://www.waivio.com/@an98r/mhg-royal-dinette

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
