### ISSUE TITLE
[Match bot / Authors, Curators, Sponsors] Additional types of match bots

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2281]
**Front task** https://github.com/Waiviogit/waivio/issues/2282

yammer 1291
Match bot / Authors, Curators, Sponsors

Additional types of match bots
https://github.com/Waiviogit/waivio/issues/2197

**Comment by Fesmofet** [comment]
estimate: 30

**Comment by Diana-Cherry-8** [comment]
У кураторского бота должен быть чекбокс, для добавления возможности поддержки комментариев. По умолчанию чекбокс не активен

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
