### ISSUE TITLE
[List / Custom sorting] all existing lists, where there was already custom sorting, are shown empty. If its reject, then all items appear

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2293]
yammer 1295
List / Custom sorting

all existing lists, where there was already custom sorting, are shown empty. If its reject, then all items appear
https://www.waivio.com/object/swu-mezethes-appetizers/list
![2021-03-25_09-44](https://user-images.githubusercontent.com/67378322/112436710-b9da7780-8d4e-11eb-8ffa-770078914444.png)

**Comment by Diana-Cherry-8** [comment]
Боря убрал силу голоса у pacific.gifts, таким образом на стейджине воспроизводиться 
![2021-03-25_10-45](https://user-images.githubusercontent.com/67378322/112445006-556fe600-8d57-11eb-9af9-3ccdc0d18e32.png)

**Comment by mariiao98** [comment]
An array in an array came to the sortCustom field, but an array should.

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
