### ISSUE TITLE
[Object / Email] if the email address is too long, it should wrap to the next line, and not overlap with the middle column

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2318]
yammer 1300
Object / Email

if the email address is too long, it should wrap to the next line, and not overlap with the middle column
https://www.waivio.com/object/ifb-beach-house-restaurant/updates/email

![2021-03-29_09-09](https://user-images.githubusercontent.com/67378322/112793750-84939980-906e-11eb-9b2b-a912b85485a5.png)

**Comment by mariiao98** [comment]
0,5h

**Comment by Diana-Cherry-8** [comment]
Align to make it the same
![2021-03-30_15-44](https://user-images.githubusercontent.com/67378322/112990588-e9361d80-916e-11eb-8cb7-5c1c3cc0b766.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
