### ISSUE TITLE
Fix the display of text with a large amount of character in the left sidebar on objects, in display and edit modes

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2338]
Fix the display of text with a large amount of character in the left sidebar on objects, in display and edit modes
https://waiviodev.com/object/yue-test-bar
Fields: 

- [ ] Description
- [ ] Rating
- [ ] Tag category
- [ ] Price
- [ ] Hours
- [ ] Address
- [ ] Website
- [ ] Phone
- [ ] Title

![2021-03-30_15-40](https://user-images.githubusercontent.com/67378322/112990029-42518180-916e-11eb-8887-0e37ce734773.png)
![2021-03-30_15-41](https://user-images.githubusercontent.com/67378322/112990174-6e6d0280-916e-11eb-92dd-3a9618e39002.png)

**Comment by mariiao98** [comment]
0,5h

**Comment by Diana-Cherry-8** [comment]
make normal word wrap
Expected result: 
![2021-03-31_15-30](https://user-images.githubusercontent.com/67378322/113144685-30d3ac80-9236-11eb-8b59-f86a580824ff.png)
Actual result:
![2021-03-31_15-32](https://user-images.githubusercontent.com/67378322/113144775-4d6fe480-9236-11eb-860e-66032b3883f0.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
