### ISSUE TITLE
The cursor jumps to the end of the text if you add a link in a post

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2343]
**Severity**: Minor

**Steps to reproduce**:
1. Write some text
2. Add link 

**Expected result**: Cursor jump to the end of the added link
**Actual result**: The cursor jumps to the end of the text if you add a link in a post

https://user-images.githubusercontent.com/67378322/113098861-b7ba6200-9201-11eb-8358-efa0311afbab.mp4

**Comment by mariiao98** [comment]
4h

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
