### ISSUE TITLE
The whole text changes, when using H2 and H3 with one word selected

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2344]
**Severity**: Minor

**Steps to reproduce**:
1. Log in
2. Open editor
3. Wrote some text
4. Selected one word
5. Click H2 / H3

**Expected result**: The highlighted word has changed
**Actual result**: The whole text changes, when using H2 and H3 with one word selected

https://user-images.githubusercontent.com/67378322/113100799-88592480-9204-11eb-834e-b160768352cc.mp4

**Comment by AndreyBelichenko** [comment]
3h

**Comment by Diana-Cherry-8** [comment]
**NOT RELEVANT**
