### ISSUE TITLE
when requesting the rewards tab, it should be checked if the user has a debt of more than 21 and a flag with true should be sent

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2347]
**Front task** https://github.com/Waiviogit/waivio/issues/1998
- when requesting the rewards tab, it should be checked if the user has a debt of more than 21 and a flag with true should be sent
- Add field notPayedPeriod, when the payables table is open

yammer 1014
Campaigns / Payables

in order for the sponsor to control late payments (after 21 days - in orange): 1. Add the number of days to each line, 2. filters 7/14/21 days, 3. show orange (!) if there is a delay> 21 days, 4. In the report, paint with words (Over ... days)
![2021-02-10_10-46](https://user-images.githubusercontent.com/67378322/107486074-40ffd180-6b8d-11eb-8bef-5a5e42031094.png)

**Comment by Waiviogit** [comment]
https://waiviodev.com/campaigns-api/api-docs/#/Payables/get_payments_payable_warning

**Comment by Diana-Cherry-8** [comment]
filtering on the right shows from the last completed review, and not the number of days from the very first debt

**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
