### ISSUE TITLE
[News / By type] you need to expand the rules for forming news streams (News buttons in objects) so that you can include not only a specific object, but also the type of objects, for example, restaurant. In this case, the stream will include all posts that link to any restaurant that is included in the subset of objects for this site.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2401]
**Back task** https://github.com/Waiviogit/waivio/issues/2400

yammer 1314
News / By type

you need to expand the rules for forming news streams (News buttons in objects) so that you can include not only a specific object, but also the type of objects, for example, restaurant. In this case, the stream will include all posts that link to any restaurant that is included in the subset of objects for this site.

**Comment by Fesmofet** [comment]
в newsFilter когда пишем тип объектов - записываеть его в свойсто typeList: [String]

**Comment by Diana-Cherry-8** [comment]
**Production checked**
