### ISSUE TITLE
[Deactivated campaign] the user had a reservation at the time the sponsor deactivated the campaign (and marked the object Unavailable). The user still has a reservation (correct), but the sponsor no longer sees this reservation in Reserved (but should)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2429]
yammer 1319
Deactivated campaign

the user had a reservation at the time the sponsor deactivated the campaign (and marked the object Unavailable). The user still has a reservation (correct), but the sponsor no longer sees this reservation in Reserved (but should)
![2021-04-09_09-12](https://user-images.githubusercontent.com/67378322/114136741-df9d7a00-9913-11eb-84c6-881b35cb234c.png)

**Comment by Fesmofet** [comment]
estimate: 3

**Comment by Diana-Cherry-8** [comment]
Воспроизводиться объект должен быть со статусом Unavailable, после резервации нужно сделать объект Unavailable, и посмотреть у спонсора нет карточки о резервации (деактивация кампании не нужна)
И у wiv01 пустая вкладка Reservations

https://user-images.githubusercontent.com/67378322/130015921-d5498cd0-e2aa-457f-9708-9853cd07ab3b.mp4

**Comment by Diana-Cherry-8** [comment]
Карточки пропадают везде и у пользователя во вкладке Reserved и у спонсора
![2021-09-08_16-37](https://user-images.githubusercontent.com/67378322/132519905-ab736320-926e-487c-992b-a4db7a9bd5ae.png)

**Comment by Diana-Cherry-8** [comment]
Отображается карточка на объект который unavailable
Ожидаемый результат: если объект помечен как unavailable то во вкладках All, Eligible не отображается кампания на этот объект

https://user-images.githubusercontent.com/67378322/133068538-1f4a9f18-07b2-485b-9fe7-74c55dd05704.mp4

**Comment by Diana-Cherry-8** [comment]
> **Актуальный результат:** Отображается карточка на объект который unavailable в All, Eligible (object https://waiviodev.com/object/krk-fine-compot)
> **Ожидаемый результат:** если объект помечен как unavailable то во вкладках All, Eligible не отображается кампания на этот объект
> 
>  vokoscreen-2021-09-13_13-29-17.mp4

Это только на этом объекте

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Судя по всему не залито

**Comment by Diana-Cherry-8** [comment]
Вкладка Reservation у спонсора пустая, после того как объект стал со статусом Unavailable
![2021-09-30_13-09](https://user-images.githubusercontent.com/67378322/135436468-916206f3-7a01-4d32-8205-b21b567dec4f.png)

**Comment by Diana-Cherry-8** [comment]
When primary object in unavailable - reproduce
![2021-11-09_09-44](https://user-images.githubusercontent.com/67378322/140884128-f61d9d8c-10c3-44b3-9c31-387a020b6151.png)
![2021-11-09_09-44_1](https://user-images.githubusercontent.com/67378322/140884137-72ea0834-f530-46bf-bada-d99f17b6127e.png)

**Comment by Diana-Cherry-8** [comment]
Сейчас карточка у спонсора осталась, но кампания продолжает отображаться в Eligible и All, когда объект помечен Unavailable 
Ожидаемый результат: Мы не отображаем кампании на объекты которые помечены Unavailable во вкладках Eligible и All

https://user-images.githubusercontent.com/67378322/141275909-c8a6ba7f-fb03-429e-999c-031df7784c9b.mp4

Актуальный результат: кампании отображается на объект со статусом Unavailable 
![2021-11-11_11-44](https://user-images.githubusercontent.com/67378322/141276028-e80c6773-246e-4619-acfb-e3e8a8389663.png)
![2021-11-11_11-44_1](https://user-images.githubusercontent.com/67378322/141276031-c935d327-12e8-4718-b647-99d439791dc8.png)

**Comment by Diana-Cherry-8** [comment]
Карточка у спонсора пропадает

https://user-images.githubusercontent.com/67378322/142852261-4cdde6f3-2a69-4967-924e-5bebca7d50a8.mp4

**Comment by Diana-Cherry-8** [comment]
Воспроизводиться. Карточка пропадает, не только то что зарезервирована, но и все связанные с этим объектом

https://user-images.githubusercontent.com/67378322/149290406-2112eb13-c7d1-4e8e-8858-64c12e854cfd.mp4

**Comment by Diana-Cherry-8** [comment]
**Production checked**
