### ISSUE TITLE
[dining.gifts / Review editing] many strange effects when trying to edit a published review: 1. Title shouldn't change by itself 2. hashtags were lost 3. After manual correction and transition to Preview, Title magically changed again 4. Preview remains blurry, cannot be published

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2475]
yammer 1336
dining.gifts / Review editing

many strange effects when trying to edit a published review: 1. Title shouldn't change by itself 2. hashtags were lost 3. After manual correction and transition to Preview, Title magically changed again 4. Preview remains blurry, cannot be published

![2021-04-16_09-06](https://user-images.githubusercontent.com/67378322/114979200-1aaf2880-9e93-11eb-95e3-26d480bec83e.png)

**Comment by AnnBaidakova** [comment]
https://user-images.githubusercontent.com/85672959/124095784-ada73a00-da62-11eb-9471-ef33b8c71368.mp4

**Comment by Diana-Cherry-8** [comment]
**Production checked** 
fixed as part of the editor's rewriting
