### ISSUE TITLE
[Wallet / Table rates] we have a table of historical exchange rates for HIVE and HBD. In the wallet table, you need to add the exchange rates (HIVE / USD, HBD / USD) columns at the time of transactions in the wallet. This is very useful for generating tax reports.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2481]
**Back-task** https://github.com/Waiviogit/waivio/issues/2498

yammer 1339
Wallet / Table rates

we have a table of historical exchange rates for HIVE and HBD. In the wallet table, you need to add the exchange rates (HIVE / USD, HBD / USD) columns at the time of transactions in the wallet. This is very useful for generating tax reports.

Hive was launched on April 20, 2020 - before that, exchange rates can be imported from STEEM / USD, SBD / USD

![2021-04-19_09-05](https://user-images.githubusercontent.com/67378322/115188998-73c6c880-a0ee-11eb-8ed0-bcda0434a4fe.png)

**Comment by Fesmofet** [comment]
added two new fields in the response: hiveUSD, hbdUSD

**Comment by Diana-Cherry-8** [comment]
Fix end date
![2021-04-26_11-21](https://user-images.githubusercontent.com/67378322/116051992-e2bd9780-a681-11eb-8e5b-d6016b7b97bf.png)
![2021-04-26_11-23](https://user-images.githubusercontent.com/67378322/116052001-e3eec480-a681-11eb-836d-a305aa3c0e19.png)

**Comment by Diana-Cherry-8** [comment]
Nan - for power up
![2021-04-26_11-32](https://user-images.githubusercontent.com/67378322/116053202-164cf180-a683-11eb-9aa4-f0d81856c64e.png)

**Comment by Diana-Cherry-8** [comment]
Doesn't display list
https://waiviodev.com/@localguide/transfers/table


https://user-images.githubusercontent.com/67378322/116053706-a55a0980-a683-11eb-8690-0242b2970c89.mp4

**Comment by Diana-Cherry-8** [comment]
Nan in guest user
![2021-04-26_13-14](https://user-images.githubusercontent.com/67378322/116067020-6b8fff80-a691-11eb-81f9-1099695d35ed.png)

**Comment by Diana-Cherry-8** [comment]
Power up with empty column 
![2021-04-26_14-58](https://user-images.githubusercontent.com/67378322/116078914-dea07280-a69f-11eb-9870-a0b2c8d49d11.png)

**Comment by Diana-Cherry-8** [comment]
Empty column in guest user
![2021-04-26_14-59](https://user-images.githubusercontent.com/67378322/116079097-17404c00-a6a0-11eb-856e-01e8de84ee24.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
