### ISSUE TITLE
[Campaign / Manage] in the table for closed campaigns 1.the Till column should show the date when the campaign was stopped (and not the planned expiry date), 2.the table itself must be sorted by the Till field so that the campaigns that were stopped last are shown first

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2526]
**Sort by till - front-task**

**Back task** https://github.com/Waiviogit/waivio/issues/2152

yammer 1185
Campaign / Manage

in the table for closed campaigns 1.the Till column should show the date when the campaign was stopped (and not the planned expiry date), 2.the table itself must be sorted by the Till field so that the campaigns that were stopped last are shown first
![2021-03-09_10-04](https://user-images.githubusercontent.com/67378322/110438174-cad48900-80be-11eb-8645-182a2f4b8bf5.png)

**Comment by YaroslavSemeniuk** [comment]
I need the front to write the timestamp value (in milliseconds) to json _metadata when the campaign is deactivated

**Comment by YaroslavSemeniuk** [comment]
For sorted by the Till field, should use **stoppedAt** field in campaign entity

**Comment by Diana-Cherry-8** [comment]
Back is ready #3370
