### ISSUE TITLE
[Dish / Initial landing] broken transitions to dish and restaurant objects. On mobile, they should open in About mode, not in Reviews (these are only hashtag objects that should open in Reviews, because their About is empty)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2530]
yammer 1348
Dish / Initial landing

broken transitions to dish and restaurant objects. On mobile, they should open in About mode, not in Reviews (these are only hashtag objects that should open in Reviews, because their About is empty)
![2021-04-27_18-40](https://user-images.githubusercontent.com/67378322/116270770-0ec34080-a788-11eb-9ff1-302f22f471e4.png)

**Comment by YaroslavSemeniuk** [comment]
The redirect doesn't work because in the request header doesn't send the "device" field

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
