### ISSUE TITLE
[Object / New post] when clicking New review from an object (without rewards), the editor should not open empty, but offer a title, enable links to objects (parent object and the object itself) By analogy with paid reviews, only without checks.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2533]
yammer 1351
Object / New post

when clicking New review from an object (without rewards), the editor should not open empty, but offer a title, enable links to objects (parent object and the object itself) By analogy with paid reviews, only without checks.
![2021-04-27_19-07](https://user-images.githubusercontent.com/67378322/116274962-d0c81b80-a78b-11eb-802e-0a93e5bfa465.png)

**Comment by AnnBaidakova** [comment]
Staging checked

**Comment by AnnBaidakova** [comment]
Production checked
