### ISSUE TITLE
[Guest withdrawals / No email] there are many problems with email confirmation (gets into junk, opens in another browser). It is proposed to exclude email confirmation and immediately initiate an exchange.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2572]
**Front-task** https://github.com/Waiviogit/waivio/issues/2573

yammer 1367
Guest withdrawals / No email

there are many problems with email confirmation (gets into junk, opens in another browser). It is proposed to exclude email confirmation and immediately initiate an exchange.

**This is a temporary solution and the email thread does not need to be killed irrevocably yet.**
![2021-05-14_09-43](https://user-images.githubusercontent.com/67378322/118232173-debeb180-b498-11eb-8966-5cc393b503a1.png)

**Comment by Fesmofet** [comment]
https://waiviodev.com/campaigns-api/api-docs/#/withdraw/post_withdraw_immediate_withdraw

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
