### ISSUE TITLE
[Objects / Nearby] for objects that have GPS, add a Nearby section, in which to show 5 objects of the same type that are nearby (the More link can be sent to the Discover / Search area (zoom - 20 km)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2576]
**Back-task**  https://github.com/Waiviogit/waivio/issues/2577

yammer 1369
Objects / Nearby

for objects that have GPS, add a Nearby section, in which to show 5 objects of the same type that are nearby (the More link can be sent to the Discover / Search area (zoom - 20 km)
![2021-05-17_09-12](https://user-images.githubusercontent.com/67378322/118440205-fa6fc500-b6ef-11eb-94c1-6651b3e14fb7.png)

**Comment by AndreyBelichenko** [comment]
4ч

**Comment by YaroslavSemeniuk** [comment]
New route:
https://waiviodev.com/api/docs/#/wobject/get_api_wobject__authorPermlink__nearby

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Produciton checked**
