### ISSUE TITLE
[Objects / Nearby] for objects that have GPS, add a Nearby section, in which to show 5 objects of the same type that are nearby (the More link can be sent to the Discover / Search area (zoom - 20 km)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2577]
**Front-task**  https://github.com/Waiviogit/waivio/issues/2576

yammer 1369
Objects / Nearby

for objects that have GPS, add a Nearby section, in which to show 5 objects of the same type that are nearby (the More link can be sent to the Discover / Search area (zoom - 20 km)
![2021-05-17_09-12](https://user-images.githubusercontent.com/67378322/118440205-fa6fc500-b6ef-11eb-94c1-6651b3e14fb7.png)

**Comment by YaroslavSemeniuk** [comment]
New route:
https://waiviodev.com/api/docs/#/wobject/get_api_wobject__authorPermlink__nearby

**Comment by Diana-Cherry-8** [comment]
Список типов объектов, для которых можно задать map:
restaurant
dish and drink - берут координаты от parent
business
product
place
indices
commodity
currency
stocks
app
currencies
company
organization
hotel
motel
resort
b&b
person
car
test

**Comment by Diana-Cherry-8** [comment]
dish and drink - берут координаты от parent, не берем в расчет

**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
