### ISSUE TITLE
[Objects / Followers] add a block with Followers (this is also for SEO)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2581]
**Front-task** https://github.com/Waiviogit/waivio/issues/2578

yammer 1370
Objects / Followers

add a block with Followers (this is also for SEO)
![2021-05-17_09-16](https://user-images.githubusercontent.com/67378322/118440560-841f9280-b6f0-11eb-83ab-16755cd5819d.png)

**Comment by YaroslavSemeniuk** [comment]
When uploading an object need to make an additional request to get subscribers.
Request: https://waiviodev.com/api/docs/#/wobject/post_api_wobject__authorPermlink__followers

**Comment by Diana-Cherry-8** [comment]
**CLOSE** Back is not needed
