### ISSUE TITLE
Main search should work by keywords

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2582]
For example, if  you enter a name without brackets - Nando's West Vancouver
option is displayed - Nando's (West Vancouver)

**Comment by Diana-Cherry-8** [comment]
Маленькие названия объекта (1 буква, 2 буквы и т.д.) нельзя найти
 
![2021-05-24_13-14](https://user-images.githubusercontent.com/67378322/119332950-f7497b80-bc91-11eb-80c8-64bd067faade.png)

**Comment by Diana-Cherry-8** [comment]
Actual result: 
![2021-07-02_15-57](https://user-images.githubusercontent.com/67378322/124277989-5ed6ce80-db4e-11eb-90c3-93d8e4298517.png)


Prod version:
![2021-07-02_15-58](https://user-images.githubusercontent.com/67378322/124277997-60a09200-db4e-11eb-8b24-adbda570199c.png)

**Comment by Diana-Cherry-8** [comment]
![2021-07-02_16-01](https://user-images.githubusercontent.com/67378322/124278395-df95ca80-db4e-11eb-93ae-bcf4fb319de7.png)

**Comment by Diana-Cherry-8** [comment]
https://waiviodev.com/api/objectType/restaurant добавить поиск как главный, чтобы количество объектов было одинаковым

https://user-images.githubusercontent.com/67378322/124279657-6dbe8080-db50-11eb-9a62-e5891771a5e6.mp4

**Comment by YaroslavSemeniuk** [comment]
searches can be performed by the following fields: name, email, phone, address, author_permlink

**Comment by Diana-Cherry-8** [comment]
Можно искать как раньше + по: номеру телефона, адресу, имейлу. Можно искать без: () {} [] : +_- =. ? * | ^ " ' ! $

**Comment by Diana-Cherry-8** [comment]
Поиск по адресу не работает

https://user-images.githubusercontent.com/67378322/125242362-40fb2d80-e2f5-11eb-96d7-5f4ea42d693a.mp4

**Comment by Diana-Cherry-8** [comment]
Поиск по email ждем фронта https://github.com/Waiviogit/waivio/issues/2840

**Comment by Diana-Cherry-8** [comment]
С пробелами нельзя найти адресс

https://user-images.githubusercontent.com/67378322/125248740-1ca34f00-e2fd-11eb-8482-7e7e451a1493.mp4

**Comment by Diana-Cherry-8** [comment]
Таска фронта https://github.com/Waiviogit/waivio/issues/2849

**Comment by Diana-Cherry-8** [comment]
**Staging checked**
