### ISSUE TITLE
Add default sorting for rewards tabs (All, Eligible)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2592]
**Front-task** https://github.com/Waiviogit/waivio/issues/2593

Default sorting consists of 2 sorts: 
1 - proximity 
2 - by payouts

**Comment by Diana-Cherry-8** [comment]
Fix swagger documentation

**Comment by YaroslavSemeniuk** [comment]
> @YaroslavSemeniuk 
> Fix swagger documentation
> ![2021-06-02_09-55](https://user-images.githubusercontent.com/67378322/120437516-d3b8bc00-c388-11eb-9596-d5a9ada21ac0.png)
> 

Done

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
