### ISSUE TITLE
The counter of comments differs from the real number of comments under the post, in feed and modal mode

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2603]
**Severity**: Minor
**Precondition**: wiv01

**Steps to reproduce**:
1. Open page wiv01
2. Pay attention to the 3rd and 4th post

**Expected result**: The counter of comments the same from the real number of comments under the post, in feed and modal mode
**Actual result**: The counter of comments differs from the real number of comments under the post, in feed and modal mode
![2021-05-20_09-55](https://user-images.githubusercontent.com/67378322/118933171-92201e00-b951-11eb-9870-15e682246e9f.png)
![2021-05-20_09-56](https://user-images.githubusercontent.com/67378322/118933225-9f3d0d00-b951-11eb-9187-f0de761d1ac5.png)

**Comment by Diana-Cherry-8** [comment]
Comments may not be displayed on feed and modal windows

https://user-images.githubusercontent.com/67378322/121006199-4a92f200-c799-11eb-955b-dd19179cadd4.mp4

**Comment by YaroslavSemeniuk** [comment]
The calculation is correct, but for a faster data update, we created a separate handler that waits for a more recent version of Node

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
