### ISSUE TITLE
Fix notification text about power up

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2624]
**Back-task** https://github.com/Waiviogit/waivio/issues/2623
**Steps to reproduce**:

1. Log in as hive-user
2. Open wallet
3. Click on Power up button
4. Do operation

**Expected result**: {userName} initiated 'Power Up' on {number} HIVE
**Actual result**: {userName} sent to {userName} {number} HIVE

Comment: key "transfer_to_vesting": "{from} sent to {to} {amount}",

![2021-05-22_12-39](https://user-images.githubusercontent.com/67378322/119221997-d3076680-bafa-11eb-9847-c2ab08b9c408.png)

**Comment by YaroslavSemeniuk** [comment]
The type "transfer_to_vesting " is processed as a "transfer" type, but needs to be as follows: "{userName} initiated 'Power Up' on {amount}"
![image](https://user-images.githubusercontent.com/73386293/119488356-1b28c200-bd63-11eb-926c-36f1b310df26.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
