### ISSUE TITLE
Add translation for website notification about events of decrease in its balance

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2625]
**Front-task** https://github.com/Waiviogit/waivio/issues/2626

**Steps to reproduce**: User has sites 
(Notifications:

По мере сокращения баланса, начинаем слать notifications: за 3 мес, за 2 мес, за 1 мес, за 3 недели, за 2 недели, за 1 неделю, потом каждый день. После возникновения отрицательной задолженности, шлем уведомление об остановке сайта каждый день 7 дней. На этом перестаем слать уведомления.

Warning: website account balance may run out in 3 months

Attention! All your websites are now suspended due to the negative balance on your website account.

(click on notifications takes user to Tools / Websites / Manage)

**Expected result**: Notification is displayed in the user's locale
**Actual result**: Notification is displayed in the only in english locale
![2021-05-22_12-50](https://user-images.githubusercontent.com/67378322/119222583-c9333280-bafd-11eb-923c-d776406189ea.png)
**Comment: during the execution of the task, tell me in what form to give the translations. I will write** (Diana)

**Comment by YaroslavSemeniuk** [comment]
estimate: 3h

**Comment by Diana-Cherry-8** [comment]
Нужно цифру которая написана словом, заменить на цифру (как на фронте)
![2021-12-09_14-17](https://user-images.githubusercontent.com/67378322/145398148-437e7b89-e432-47bb-835a-9b2b9e07474b.png)
![2021-12-09_14-17_1](https://user-images.githubusercontent.com/67378322/145398150-bdfc378e-16d7-43aa-8263-7a6e456e00f4.png)
![2021-12-09_14-40](https://user-images.githubusercontent.com/67378322/145398221-c2f8be00-b2cd-400c-8acf-a49c000cfabf.png)

**Comment by Diana-Cherry-8** [comment]
**Production checked**
