### ISSUE TITLE
[My Feed / Users] I follow 238 users, and the list shows counters only for users whose name begins with the letter "@a .." Yes, and it is necessary to sort not by name, but by expertise

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2642]
yammer 1388
My Feed / Users

I follow 238 users, and the list shows counters only for users whose name begins with the letter "@a .." Yes, and it is necessary to sort not by name, but by expertise
![2021-05-27_10-05](https://user-images.githubusercontent.com/67378322/119780929-13882b00-bed3-11eb-9f49-2d69f2e3a7d3.png)

**Comment by AnnBaidakova** [comment]
List shows correct counters of users, but sort not by expertise work is not correct 

![MyCollages](https://user-images.githubusercontent.com/85672959/123957061-09ff5080-d9b4-11eb-8037-076f5bc543b4.jpg)

**Comment by AnnBaidakova** [comment]
Staging checked

**Comment by Diana-Cherry-8** [comment]
**Production checked**
