### ISSUE TITLE
Add translation for checkbox "I have read and agree to the terms and conditions of the" or add key in default locale file, Create Websites tab

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2643]
**Severity**: Trivial
**Precondition**: hive-user

**Steps to reproduce**:
1. Log in as hive-user
2. Open Tools tab
3. Open Create tab

**Expected result**: Add translation for checkbox "I have read and agree to the terms and conditions of the" or add key in default locale file, Create Websites tab
**Actual result**: The checkbox text is translated only into Russian, in all other languages English is displayed

![2021-05-27_11-37](https://user-images.githubusercontent.com/67378322/119794166-f7d75180-bedf-11eb-8f37-e8745bb40b5b.png)

**Comment by LucyHrinishyna** [comment]
added translate for ukranian

**Comment by Diana-Cherry-8** [comment]
website_create_alerts_info

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
