### ISSUE TITLE
[daily.dining / Shares] for external indexing (including on Facebook) of the home page * .dining.giftts, you can use the desktop icon as a picture

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2652]
yammer 1390
daily.dining / Shares

for external indexing (including on Facebook) of the home page * .dining.giftts, you can use the desktop icon as a picture
![2021-05-31_09-00](https://user-images.githubusercontent.com/67378322/120146990-a20bed80-c1ee-11eb-8b91-1634543950ec.png)

**Comment by WaivioLabs** [comment]
Opengraph meta tags can be used to improve social sharing on FB, TW and other networks 

![image](https://user-images.githubusercontent.com/42100432/120556744-c6fc8e00-c3b1-11eb-8eed-e33ce76ab2c2.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
