### ISSUE TITLE
[Wallet / Advanced] when choosing the From date at the bottom, you need to change Today to Account creation, so that you can select the date of account creation with one click (-1). If there are several accounts, the earliest date.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2655]
**Front-task** https://github.com/Waiviogit/waivio/issues/2656

yammer 1393
Wallet / Advanced

when choosing the From date at the bottom, you need to change Today to Account creation, so that you can select the date of account creation with one click (-1). If there are several accounts, the earliest date.
![2021-05-31_09-23](https://user-images.githubusercontent.com/67378322/120149114-ec429e00-c1f1-11eb-9850-106ac43b804f.png)

**Comment by Fesmofet** [comment]
https://waiviodev.com/api/docs/#/user/get_api_user__userName__creation_date

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
