### ISSUE TITLE
[Object / New post] when clicking on Write a new review the editor should be pre-populated with Title and object links (including parent)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2660]
yammer 1397
Object / New post

when clicking on Write a new review the editor should be pre-populated with Title and object links (including parent)
![2021-05-31_09-13](https://user-images.githubusercontent.com/67378322/120148195-81449780-c1f0-11eb-8ebb-5d75eecf1301.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
At the moment, the order is opposite, first comes primary object, then secondaries
![2021-06-09_15-38](https://user-images.githubusercontent.com/67378322/121355832-f757a580-c938-11eb-8959-3607de26774b.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by AnnBaidakova** [comment]
Production checked
