### ISSUE TITLE
[Editor / Add photos] when adding a subset of photos, they should all be close. Now the first photo is in the right place, and the rest go to the end of the post.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2671]
yammer 1404
Editor / Add photos

when adding a subset of photos, they should all be close. Now the first photo is in the right place, and the rest go to the end of the post.
![2021-05-31_17-47](https://user-images.githubusercontent.com/67378322/120210243-3f3f4400-c238-11eb-8295-85aa6c7498b7.png)

**Comment by Diana-Cherry-8** [comment]
Картинка добавленная 1я должна отображаться в самом верху 
![2021-06-21_14-39](https://user-images.githubusercontent.com/67378322/122756095-a16ef000-d29e-11eb-8ce3-546f38582b60.png)
![2021-06-21_14-40](https://user-images.githubusercontent.com/67378322/122756101-a338b380-d29e-11eb-8512-263f0a6f3207.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by AnnBaidakova** [comment]
Production checked
