### ISSUE TITLE
[dining.gifts / Sign in] change Sign In window design to dining.gifts

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2715]
yammer 1422
dining.gifts / Sign in

change Sign In window design to dining.gifts
![2021-06-09_09-02](https://user-images.githubusercontent.com/67378322/121301814-6d401a80-c901-11eb-998d-89dd91ef0515.png)

**Comment by LucyHrinishyna** [comment]
6h

**Comment by Diana-Cherry-8** [comment]
The close button isn't clickable
![2021-07-19_16-00](https://user-images.githubusercontent.com/67378322/126163526-a772e068-e0df-486a-985e-12440a4af5e6.png)

**Comment by Diana-Cherry-8** [comment]
Null in link, when log in thought facebook

https://user-images.githubusercontent.com/67378322/126165027-a7dbfa05-147e-40f4-9ac8-ff461d0921f3.mp4

**Comment by Diana-Cherry-8** [comment]
add some space
![2021-07-19_17-02](https://user-images.githubusercontent.com/67378322/126172429-dd234521-9c57-4cc7-a7d2-cbee61fd804b.png)

**Comment by Diana-Cherry-8** [comment]
Fix text about terms and conditions 

**Expected result:** By using this service, you agree to our Terms & Conditions, our Privacy Policy, and our Cookies Policy

**Actual result:** 
![2021-07-19_17-13](https://user-images.githubusercontent.com/67378322/126174148-d12d66c1-81fa-46bc-9b4a-846dd88ed727.png)

**Comment by Diana-Cherry-8** [comment]
Add dots in titles
![2021-07-19_17-26](https://user-images.githubusercontent.com/67378322/126176243-fe29531e-7dc3-4330-937c-3707f1a8ac91.png)

**Comment by Diana-Cherry-8** [comment]
Цвет текста на кнопках можно попробовать #000000bd
![2021-07-19_17-31](https://user-images.githubusercontent.com/67378322/126176920-0444dca6-8e7c-4807-85b6-3d7c41c133b3.png)

**Comment by Diana-Cherry-8** [comment]
У обычной моделке на кнопки нужно много раз нажать, чтобы авторизоваться и добавляется лишнее http в ссылке (например, при авторизации через hive)
![2021-07-20_09-11](https://user-images.githubusercontent.com/67378322/126270630-6a308a27-9ce3-4ad8-be13-1f7b4197419e.png)

**Comment by Diana-Cherry-8** [comment]
Ширину модалки можно уменьшить до 440 px
![2021-07-21_10-04](https://user-images.githubusercontent.com/67378322/126446129-36432cbd-4a4d-45eb-8b95-39f97195f80e.png)

**Comment by Diana-Cherry-8** [comment]
Большие отступы 
![2021-07-22_09-52](https://user-images.githubusercontent.com/67378322/126600143-9c9344f0-8cec-433b-9847-d40d509f8647.png)

Нужно добавить отступы в названии ссылки Terms & Conditions
![2021-07-22_09-54](https://user-images.githubusercontent.com/67378322/126600198-b21c8ccb-93b1-49a8-8d5d-89b7350bcffb.png)

**Comment by Diana-Cherry-8** [comment]
Title "Get a free beginner..." немного затемнить #000000cf
![2021-07-22_09-59](https://user-images.githubusercontent.com/67378322/126600814-ada18c08-a509-43b2-a963-80c3ea6c77b5.png)

**Comment by Diana-Cherry-8** [comment]
Ссылки нужно поправить чтобы они были на dining.pp.ua (dining.gifts)
![2021-07-22_10-10](https://user-images.githubusercontent.com/67378322/126601849-e49bd661-b83a-4eb8-80a9-5737638fd71a.png)

**Comment by Diana-Cherry-8** [comment]
Новая модалка не открывается на dining.pp.ua (на сайте там kind.dining.pp.ua - открывается)
![2021-07-22_12-18_1](https://user-images.githubusercontent.com/67378322/126616550-41b6b26d-c1a6-4816-bbdf-3169fa48b47c.png)
![2021-07-22_12-18](https://user-images.githubusercontent.com/67378322/126616559-9678f044-6c31-409d-8b9d-6a992d7fd078.png)

**Comment by Diana-Cherry-8** [comment]
Авторизация через новую модалку не работает, не через hive, не google, не facebook
везде лишнее http//

https://user-images.githubusercontent.com/67378322/126632482-fc73cc54-b8f6-4ee3-a599-c1920c4718f8.mp4

**Comment by Diana-Cherry-8** [comment]
![2021-07-22_16-24](https://user-images.githubusercontent.com/67378322/126646310-b1bde9ad-7648-4d4f-813f-4736609cb4e4.png)

**Comment by Diana-Cherry-8** [comment]
На мобилке новая модалка смещена и отображается крестик с другой модалки
![2021-07-23_09-09](https://user-images.githubusercontent.com/67378322/126743573-1db973ac-c928-462b-abe6-e75c82aad50a.png)

**Comment by Diana-Cherry-8** [comment]
Плывет верстка у iphone 6/7/8
![2021-07-23_09-42](https://user-images.githubusercontent.com/67378322/126746076-295e745d-d988-4b81-8393-dc27252b1a09.png)

**Comment by Diana-Cherry-8** [comment]
ipad модалка располагается с боку
![2021-07-23_09-54](https://user-images.githubusercontent.com/67378322/126747320-987e5ec4-e231-4a7c-a651-2a64185d11d8.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
