### ISSUE TITLE
[Review / Referral] for some unknown reason grampo is listed as referral by review, although grampo 1. has no referrals and 2. the website has been down for a long time.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2726]
yammer 1426
Review / Referral

for some unknown reason grampo is listed as referral by review, although grampo 1. has no referrals and 2. the website has been down for a long time.
https://www.waivio.com/@waivio_irenok/6q6udm-review-cactus-club-cafe-richmond-modern-bowl
![2021-06-10_09-10](https://user-images.githubusercontent.com/67378322/121473710-bd83af00-c9cb-11eb-835f-5697b590ffc5.png)

**Comment by Fesmofet** [comment]
пост опубликован с dining.gifts, все отработало корректно согласно yammer 1160

**Comment by Diana-Cherry-8** [comment]
**NOT A BUG**
