### ISSUE TITLE
Add notification when user saving hashtags on tools page on object filters tab

### ISSUE THREAD

**Issue by AnnBaidakova** [Waiviogit/waivio#2730]
**To do:**   Add notification that changes were saved. When user saving hashtags on tools page 
**Task goal:**  User can clearly understand that changes were edited or saved
**Acceptance criteria:** Notification "Object filters update successfully" appear after adding new hashtag and clicking on save button
![improve](https://user-images.githubusercontent.com/85672959/121550865-cb5f2180-ca17-11eb-978e-af5d2d1fb530.png)

![image](https://user-images.githubusercontent.com/85672959/121892773-d5d62f80-cd25-11eb-9e23-e3e1a41ff96a.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
