### ISSUE TITLE
Frontend error on object page, in edit mode in map setting, when enter to latitude field invalid data

### ISSUE THREAD

**Issue by AnnBaidakova** [Waiviogit/waivio#2731]
**Severity:** Critical
**Precondition:** wiv01 stage

**Steps to reproduce:**

 1. Log in as wiv01
 2. Open object page
 3. Click button "edit"
 4. Click "+" near map
 5. Input to latitude field "2544" 
 
**Expected result:** Appear notification "Should be number more than -85 and less then 85"
**Actual result:** Frontend error page appear

 https://user-images.githubusercontent.com/85672959/121542768-13c71100-ca11-11eb-88e1-4958b46957fc.mp4

![image](https://user-images.githubusercontent.com/85672959/121552814-6dcbd480-ca19-11eb-82e4-57b11b30af72.png)

**Comment by Diana-Cherry-8** [comment]
In progress

**Comment by Diana-Cherry-8** [comment]
The map does not close completely, small size, after reopening the modal window

https://user-images.githubusercontent.com/67378322/122178925-b4915280-ce8f-11eb-8f28-73fac20b6951.mp4

**Comment by Diana-Cherry-8** [comment]
https://github.com/Waiviogit/waivio/issues/2745 Last comment in task

**Comment by Diana-Cherry-8** [comment]
**Production checked**
