### ISSUE TITLE
All requests with waivio must go through dining.gifts

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2739]
**Back-task** https://github.com/Waiviogit/waivio/issues/2738

Since closed commercial networks block waivio (like a decentralized system), and sending requests through diving should solve this problem

**Comment by Fesmofet** [comment]
dining.pp.ua connected api:
/api
/auth
/campaigns-api
/currencies-api
/object-bot
/notifications-api

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
