### ISSUE TITLE
The character set of the place of the link is displayed if the link to the object is edited

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2747]
**Severity**: Minor
**Precondition**: Post, link to object

**Steps to reproduce**:
1. Log in
2. Open post
3. Left comment with link to object
4. Refresh page
5. Edit link in comment

**Expected result**: Link displayed
**Actual result**: The character set of the place of the link is displayed if the link to the object is edited

https://user-images.githubusercontent.com/67378322/122419963-fd323400-cf93-11eb-9c11-81f47412742a.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by AnnBaidakova** [comment]
Production  checked
