### ISSUE TITLE
[dining.gifts / Menu] on dining.gifts the Menu button is visible, but on * .dining.gifts sites this button is not

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2748]
yammer 1432
dining.gifts / Menu

on dining.gifts the Menu button is visible, but on * .dining.gifts sites this button is not
https://daily.dining.gifts/object/yhp-cactus-club-cafe-richmond

![2021-06-18_09-36](https://user-images.githubusercontent.com/67378322/122517470-bcc8c980-d018-11eb-9147-e2fbe8c11628.png)

**Comment by Diana-Cherry-8** [comment]
**Production checked**

**Comment by AnnBaidakova** [comment]
Production checked
