### ISSUE TITLE
[dining.gifts / Lists] the restaurant has an empty menu, but waivio.com displays everything correctly - this affects all dining.gifts sites

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2749]
yammer 1434
dining.gifts / Lists

the restaurant has an empty menu, but waivio.com displays everything correctly - this affects all dining.gifts sites
https://www.waivio.com/object/esg-milltown-bar-and-grill/menu#kbf-delicious-milltown-menu
![2021-06-21_08-46](https://user-images.githubusercontent.com/67378322/122712772-2c36f700-d26d-11eb-8be9-3529bda6b2ed.png)

**Comment by Diana-Cherry-8** [comment]
**Production checked**

**Comment by AnnBaidakova** [comment]
Production checked
