### ISSUE TITLE
Guest posts cannot be liked

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2758]
**Severity**: Major
**Precondition**: Guest user wrote a post

**Steps to reproduce**:
1. Log in like hive
2. Open guest feed or find guest post
3. Like post

**Expected result**: Guest posts can be liked
**Actual result**: Guest posts cannot be liked
![2021-06-21_13-27](https://user-images.githubusercontent.com/67378322/122748234-a2028900-d294-11eb-8055-4607ffb5d97f.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by AnnBaidakova** [comment]
Production tested
