### ISSUE TITLE
[List / Custom sort] if there is room in the line, then there is no need to trim the names of objects

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2760]
yammer 1436
List / Custom sort

if there is room in the line, then there is no need to trim the names of objects
https://www.waivio.com/object/qyo-pasta/updates/sortCustom
![2021-06-22_09-08](https://user-images.githubusercontent.com/67378322/122872656-6cfc4200-d339-11eb-8d47-25c88b5cde94.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by AnnBaidakova** [comment]
Production checked
