### ISSUE TITLE
[List / Custom sort] when forming the first Custom sort, objects must be sorted by the time the object was added to the list. This will greatly simplify the work of operators (objects are usually added in the order they want to see it). Subsequent updates should be done taking into account active custom sorting.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2761]
yammer 1437
List / Custom sort

when forming the first Custom sort, objects must be sorted by the time the object was added to the list. This will greatly simplify the work of operators (objects are usually added in the order they want to see it). Subsequent updates should be done taking into account active custom sorting.
![2021-06-22_09-10](https://user-images.githubusercontent.com/67378322/122872830-aaf96600-d339-11eb-80ff-f4a54a9172ec.png)

**Comment by Diana-Cherry-8** [comment]
Switching sorts does not change

https://user-images.githubusercontent.com/67378322/123766110-0ba31880-d8cf-11eb-8602-a4c10db14f16.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by AnnBaidakova** [comment]
Production checked
