### ISSUE TITLE
[List / Dedicated view] the list is shown correctly inside the object, but if you open it in a separate window, the parent links on the objects are wrong (in this example, the icons are also wrong)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2762]
yammer 1438
List / Dedicated view

the list is shown correctly inside the object, but if you open it in a separate window, the parent links on the objects are wrong (in this example, the icons are also wrong)
https://www.waivio.com/object/cug-trattoria-italian-kitchen-restaurant/menu#nqb-menu/cgk-lunch-and-dinner/qxi-sides
![2021-06-22_09-12](https://user-images.githubusercontent.com/67378322/122873006-f0b62e80-d339-11eb-8637-f55ed540ffeb.png)

**Comment by LucyHrinishyna** [comment]
битая картинка в обеих кейсах

**Comment by Diana-Cherry-8** [comment]
**Production checked**
