### ISSUE TITLE
Frontend error, when opening history/message tab in rewards 

### ISSUE THREAD

**Issue by AnnBaidakova** [Waiviogit/waivio#2764]
**Severity:** Critical
**Precondition:** wiv01 stage

**Steps to reproduce:**

1. Log in as wiv01
2. Open rewards
3. Open history/message tab

**Expected result**: Appear complete page with content 
**Actual result** Front crash 

https://user-images.githubusercontent.com/85672959/122894998-62997280-d350-11eb-9b1d-a38dd51b3d53.mp4

![image](https://user-images.githubusercontent.com/85672959/122895173-86f54f00-d350-11eb-89a3-a559aab39265.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Не загружается кампания для просмотра, в Manage

https://user-images.githubusercontent.com/67378322/123062140-eae14b80-d414-11eb-87f4-768475da7788.mp4

**Comment by AnnBaidakova** [comment]
Production checked
