### ISSUE TITLE
Visibility of name of users on administrators/moderators/authorities tabs on dark theme

### ISSUE THREAD

**Issue by AnnBaidakova** [Waiviogit/waivio#2765]
**Severity:** Trivial 

**Precondition:** 
1. Log in
2. Create web site

**Steps to reproduce:**
1. Open "Tools" tab
2. Open created website -> Administrators/Moderators/Authorities tab
3. Choose user 
4. Click on "Add" button
_____________________________________________________________________________________________________
1. Open "Advanced reports" 
2. Choose user in "Find user field"

**Expected result:** Chosen user card appear in a black color 

**Actual result:** Chosen user card is white   

https://user-images.githubusercontent.com/85672959/122912687-46520180-d361-11eb-87c5-fbfafa1e1306.mp4

![1212](https://user-images.githubusercontent.com/85672959/124110170-a2f3a180-da70-11eb-9f57-7b8b476b66b5.png)

![Screenshot from 2021-06-22 13-52-36](https://user-images.githubusercontent.com/85672959/122912603-29b5c980-d361-11eb-878f-1dadf768fe2a.png)

![image](https://user-images.githubusercontent.com/85672959/122913610-51596180-d362-11eb-8bc6-e4a208707cd0.png)

**Comment by Diana-Cherry-8** [comment]
Example
![2021-09-10_11-13](https://user-images.githubusercontent.com/67378322/132822401-39d198f6-0f4a-4ba0-91ea-db911ab4ac65.png)

**Comment by Diana-Cherry-8** [comment]
Fix background for "No authorities added." and "No moderators added." for tabs Authorities, Moderators for night mode
![2021-09-14_11-44](https://user-images.githubusercontent.com/67378322/133226174-01cd583b-8e99-44f5-8b7a-1b8418b2b208.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
