### ISSUE TITLE
[Ratings / Personalization] ratings should be grayed out, and only your votes should be shown in orange. The voting process itself is reduced to 1 click.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2773]
yammer 1440
Ratings / Personalization

ratings should be grayed out, and only your votes should be shown in orange. The voting process itself is reduced to 1 click.
https://github.com/Waiviogit/waivio/issues/2772

**Comment by LucyHrinishyna** [comment]
6h

**Comment by Diana-Cherry-8** [comment]
Неавторизованный пользователь (чисто интерфейсно) может ставить рейтинги - может рейтинги для неавторизованного пользователя пусть будут не кликабельны?

https://user-images.githubusercontent.com/67378322/148064140-cfc65f7f-22ba-46bb-9e14-66a08f50329b.mp4

**Comment by Diana-Cherry-8** [comment]
Падает фронт у https://dinings.club/object/equ-arbys-restaurant
![2022-01-04_15-12](https://user-images.githubusercontent.com/67378322/148064283-3acb4de6-0579-4fa5-b2f5-a6784a3cdef5.png)

**Comment by Diana-Cherry-8** [comment]
Нужно в карточках на карте поменять местами звездочки и название рейтинга
![2022-01-04_15-15_1](https://user-images.githubusercontent.com/67378322/148064724-02e97fb1-5926-4b92-9265-64144a522360.png)

**Comment by Diana-Cherry-8** [comment]
Если поставить рейтинг, а потом убрать его, то звездочки отображаются как пустые, то есть рейтинг очистился, а не тёмно-серым (с рейтингом других пользователей) 

https://user-images.githubusercontent.com/67378322/148065121-54cad095-159c-4806-bf4d-930711f906a0.mp4

**Comment by Diana-Cherry-8** [comment]
https://github.com/Waiviogit/waivio/issues/3088 это задача перестала работать

https://user-images.githubusercontent.com/67378322/148176665-e06047f9-e954-44be-b296-ffaaa07b3190.mp4

**Ожидаемый результат:**

https://user-images.githubusercontent.com/67378322/148176758-3d81f786-2cf6-4bc0-9887-8c3b054ea75f.mp4

**Comment by Diana-Cherry-8** [comment]
Имя рейтинга на новой строке в карточке на карте
![2022-01-05_11-09](https://user-images.githubusercontent.com/67378322/148191313-351b392d-392b-413b-b8a5-6167f84d7569.png)

**Comment by Diana-Cherry-8** [comment]
На карте одно имя рейтинга с новой строки, в поисковой панели
![2022-01-05_11-10](https://user-images.githubusercontent.com/67378322/148191527-b3392b79-4d73-40cb-a7e3-5b3b5e5eb10c.png)

**Comment by Diana-Cherry-8** [comment]
> #3088 это задача перестала работать
> 
>  vokoscreen-2022-01-05_09-22-33.mp4 
> **Ожидаемый результат:**
> 
>  vokoscreen-2022-01-05_09-23-16.mp4
----------------------
При уменшении экрана нужно убирать 1й столбик чтобы второй отображался. На Rewards отображается 1я колонка
**Актуальный результат:**
![2022-01-05_11-13](https://user-images.githubusercontent.com/67378322/148191901-ebaf69b8-a373-4fa3-a408-c112b84074cc.png)


**Ожидаемый результат:**
![2022-01-05_11-12](https://user-images.githubusercontent.com/67378322/148191918-7bf5859c-85fb-49df-8b06-3b833ad7fc85.png)

**Comment by Diana-Cherry-8** [comment]
В идеале, уже при разрешении width: 1070px; height: 850px;  убирать 1ю колонку рейтингов
![2022-01-05_11-20](https://user-images.githubusercontent.com/67378322/148192900-f6111f57-b181-4529-a26a-cbfc2916acf8.png)

**Comment by Diana-Cherry-8** [comment]
Добавить немного отступа перед рейтингами
![2022-01-05_11-22](https://user-images.githubusercontent.com/67378322/148193294-7d25f7d6-e065-4ea4-9bcf-12d271fc1d9b.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
