### ISSUE TITLE
[Rewards / Payouts sorting] cont 1318: with payouts sorting, a restaurant with 3 reviews is higher than a restaurant with 20 reviews and a big reward - this is probably not correct

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2779]
yammer 1444
Rewards / Payouts sorting

cont 1318: with payouts sorting, a restaurant with 3 reviews is higher than a restaurant with 20 reviews and a big reward - this is probably not correct
![2021-06-29_08-59](https://user-images.githubusercontent.com/67378322/123745017-52394880-d8b8-11eb-9a80-02d60e2abbbb.png)

**Comment by YaroslavSemeniuk** [comment]
sorting works correctly, is calculated as follows:
**_count of paid campaigns * reward * commissionAgreement_**
if there are no paid campaigns, then:
**_reward * commissionAgreement_**

**Comment by Diana-Cherry-8** [comment]
**Not a bag**
