### ISSUE TITLE
[Post / New object] if you create a new object (page), then it is added to the post (correct), but the link from the card leads to the home page instead of the permlink object

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2780]
yammer 1445
Post / New object

if you create a new object (page), then it is added to the post (correct), but the link from the card leads to the home page instead of the permlink object
![2021-06-29_09-03](https://user-images.githubusercontent.com/67378322/123745369-dbe91600-d8b8-11eb-8381-60cb650bd9b1.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by AnnBaidakova** [comment]
**Production checked**
