### ISSUE TITLE
[Rewards / Create] add Base currency selection when creating rewards campaigns. This is necessary to ensure a stable price in a given currency.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2786]
**Front-task** https://github.com/Waiviogit/waivio/issues/2782

yammer 1447
Rewards / Create

add Base currency selection when creating rewards campaigns. This is necessary to ensure a stable price in a given currency.

Base currency
Disclaimer: Exchange rates are provided by third parties and may not be accurate.
![2021-06-29_09-06](https://user-images.githubusercontent.com/67378322/123745730-5b76e500-d8b9-11eb-8807-cdfc7b3f60fd.png)

**Comment by Fesmofet** [comment]
estimate: 9

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
