### ISSUE TITLE
Down vote of the post is recorded, is sent as a like if the user has disabled the slider

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2791]
**Severity**: Minor
**Precondition**: The user has disabled the slider in Settings

**Steps to reproduce**:
1. Log in as hive user 
2. Click on Tree dots button on post
3. Click Flag post

**Expected result**: Down voice of the post is recorded, is sent as a down vote if the user has disabled the slider
**Actual result**: Down voice of the post is recorded is sent as a like if the user has disabled the slider

https://user-images.githubusercontent.com/67378322/123801897-5f275d80-d8f3-11eb-9848-b2b619966bc3.mp4

![2021-06-29_16-00](https://user-images.githubusercontent.com/67378322/123801681-2f785580-d8f3-11eb-91be-2419206247a9.png)

**Comment by AnnBaidakova** [comment]
Staging checked

**Comment by Diana-Cherry-8** [comment]
**Production checked**
