### ISSUE TITLE
Text display as a single string with slider in review editing mode when opens preview

### ISSUE THREAD

**Issue by AnnBaidakova** [Waiviogit/waivio#2798]
**Severity:** Major

**Steps to reproduce:**
1. Log in 
2. Create review 
3. Edit created review 
4. Write a text  with spaces between 
5. Open preview of the edited post 

**Expected result:**  
Text display as it was wrote in edit mode 

**Actual result:** 
Text display as a single string and appear slider 

https://user-images.githubusercontent.com/85672959/124107564-07613180-da6e-11eb-915c-0b3cb6388082.mp4

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
