### ISSUE TITLE
[Posts / Unavailable] relisted 1443: showing rewards for an unavaiable object was adjusted when showing the article in the window, but in the main view of the article reward continues to be shown

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2805]
yammer 1451
Posts / Unavailable

relisted 1443: showing rewards for an unavaiable object was adjusted when showing the article in the window, but in the main view of the article reward continues to be shown
![2021-07-02_10-04](https://user-images.githubusercontent.com/67378322/124234618-ef94b680-db1c-11eb-9c01-3870a36a72a4.png)

**Comment by Fesmofet** [comment]
estimate: 2

**Comment by YaroslavSemeniuk** [comment]
failed to reproduce the bug

**Comment by YaroslavSemeniuk** [comment]
Information about display campaign for the current user is stored in the "assigned" field in propositions objects. The frontend should consider this flag.
![assigned](https://user-images.githubusercontent.com/73386293/130040133-e78b4123-5495-46ad-b6d8-7b6f978bca02.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
