### ISSUE TITLE
[Rewards / Reports] when generating financial reports on Waivio, you must allow the selection of all supported currencies

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2811]
**Front-task** https://github.com/Waiviogit/waivio/issues/2812

yammer 1456
Rewards / Reports

when generating financial reports on Waivio, you must allow the selection of all supported currencies
![2021-07-02_10-15](https://user-images.githubusercontent.com/67378322/124235805-62eaf800-db1e-11eb-84ae-3d8833b27601.png)

**Comment by Diana-Cherry-8** [comment]
при смени валюты, колонка Balance по нулям
![2021-07-14_17-15](https://user-images.githubusercontent.com/67378322/125637486-19681803-e301-4b5c-a610-1678ce84a8d7.png)

**Comment by Diana-Cherry-8** [comment]
In payables tables with 0

https://user-images.githubusercontent.com/67378322/125740316-d9f83679-5ba7-43f5-86f8-6cedb6629ee6.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by OleksandrMosiichuk** [comment]
**Production checked**
