### ISSUE TITLE
[Rewards / Reports] when generating financial reports on Waivio, you must allow the selection of all supported currencies

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2812]
**Back-task** https://github.com/Waiviogit/waivio/issues/2811

yammer 1456
Rewards / Reports

when generating financial reports on Waivio, you must allow the selection of all supported currencies
![2021-07-02_10-15](https://user-images.githubusercontent.com/67378322/124235805-62eaf800-db1e-11eb-84ae-3d8833b27601.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by OleksandrMosiichuk** [comment]
**Production checked**
