### ISSUE TITLE
[Notifications / Replies] diningguide commented on the post and then the author replied. We need to change the message for diningguide to "[user] has replied to your comment" and also fix the link

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2816]
**Front-task** https://github.com/Waiviogit/waivio/issues/2817

yammer 1460
Notifications / Replies

diningguide commented on the post and then the author replied. We need to change the message for diningguide to "[user] has replied to your comment" and also fix the link
https://www.waivio.com/@diningguide/re-carolynstahl-tofu-with-miso-maple-ginger-sauce-hive-top-chef-20210702t033016537z
![2021-07-02_10-22](https://user-images.githubusercontent.com/67378322/124236674-5c10b500-db1f-11eb-8284-66130598b95a.png)

**Comment by YaroslavSemeniuk** [comment]
awaiting change of comment text at the front

**Comment by Diana-Cherry-8** [comment]
**Check on prod**

**Comment by Diana-Cherry-8** [comment]
**Production checked**

**Comment by Diana-Cherry-8** [comment]
в телеграмме нужно добавить слово has
![2021-07-15_17-41](https://user-images.githubusercontent.com/67378322/125807318-0e842b07-612d-4cba-b596-ca5c753818c1.png)

**Comment by YaroslavSemeniuk** [comment]
fixed

**Comment by Diana-Cherry-8** [comment]
Check on prod

**Comment by Diana-Cherry-8** [comment]
не залито
![2021-07-28_16-27](https://user-images.githubusercontent.com/67378322/127331613-5658aaaf-e528-41e2-82a7-2faf83d49cad.png)

**Comment by Diana-Cherry-8** [comment]
**Production checked**
