### ISSUE TITLE
[Notifications / Replies] diningguide commented on the post and then the author replied. We need to change the message for diningguide to "[user] has replied to your comment" and also fix the link

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2817]
**Back-task** https://github.com/Waiviogit/waivio/issues/2816

yammer 1460
Notifications / Replies

diningguide commented on the post and then the author replied. We need to change the message for diningguide to "[user] has replied to your comment" and also fix the link
https://www.waivio.com/@diningguide/re-carolynstahl-tofu-with-miso-maple-ginger-sauce-hive-top-chef-20210702t033016537z
![2021-07-02_10-22](https://user-images.githubusercontent.com/67378322/124236674-5c10b500-db1f-11eb-8284-66130598b95a.png)

**Comment by YaroslavSemeniuk** [comment]
the front should display the following message: "[user] has replied to your comment" in case the recipient of this message is the author of the comment to which reply.

**Comment by Diana-Cherry-8** [comment]
![2021-07-14_09-44](https://user-images.githubusercontent.com/67378322/125575782-62736115-065b-4b50-a57d-fc7db0355d87.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
