### ISSUE TITLE
Result of search displays in a wrong way, when enter 250 characters to search field 

### ISSUE THREAD

**Issue by AnnBaidakova** [Waiviogit/waivio#2824]
**Severity:** Minor

**Precondition:** Log in as a Hive user 

**Steps to reproduce:**
1. Enter 250 characters into search field 
2. Click show all results 

**Expected result:** Entered result displays in a column 

**Actual result:** Entered result displays as a single string 

![unknown](https://user-images.githubusercontent.com/85672959/124612270-dcfee200-de7a-11eb-8e6f-2a1a422eb562.png)

**Comment by Diana-Cherry-8** [comment]
**CAN'T REPRODUCE**
