### ISSUE TITLE
Error message of comparing Campaign budget and Reward values works incorrectly at Create tab

### ISSUE THREAD

**Issue by OleksandrMosiichuk** [Waiviogit/waivio#2832]
**Severity:** Minor
**Precondition:** Hive user is logged in

**Steps to reproduce:**

1. Open Rewards tab
2. Open Create tab from Campaigns bar
3. Enter any number (less than HIVE wallet balance) in Reward field
4. Enter any greater number than in previous step (but less than HIVE wallet balance) in Campaign budget field

**Expected result:** Error message "The reward should not exceed the budget" disappeared 
**Actual result:** Error message "The reward should not exceed the budget" didn't disappear 

_The similar defect exists in reverse situation, for example:_
1. Enter in the Campaign budget field "50"
2. Enter in the Reward field "20"
3. Change the value of Campaign budget field to "10"

**Expected result:** Error message "The reward should not exceed the budget" appeared 
**Actual result:** Error message "The reward should not exceed the budget" didn't appear

![CreateTabFields](https://user-images.githubusercontent.com/87119098/124926235-f4b6a180-e005-11eb-92c0-7390dd488ee4.png)
![CreateTabFieldsNoError](https://user-images.githubusercontent.com/87119098/124926250-f97b5580-e005-11eb-8a96-b977f940780d.png)

**Comment by Diana-Cherry-8** [comment]
https://user-images.githubusercontent.com/67378322/132352237-d58ee0ad-5a8a-4d1f-9fb5-972c4dcf8432.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
