### ISSUE TITLE
[Pages / Images] on some older Page objects, pictures stopped showing

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2834]
yammer 1461
Pages / Images

on some older Page objects, pictures stopped showing
https://www.waivio.com/object/ylr-waivio/page#mwt-about-waivio

![2021-07-09_09-01](https://user-images.githubusercontent.com/67378322/125030768-4e65ad00-e094-11eb-9cc1-87024ff52c32.png)

**Comment by Fesmofet** [comment]
image links lead to busy.org - domen is not available

**Comment by Diana-Cherry-8** [comment]
Раньше картинки были на busy.org надо найти ссылку с hive

**Comment by YaroslavSemeniuk** [comment]
estimate: 6h

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
В постах апдейтах, отображаются ломанные картинки

https://user-images.githubusercontent.com/67378322/127015033-781470ee-b771-4922-8c3a-fcbefab612bf.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
