### ISSUE TITLE
The search does not send the "@" character 

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2840]
**Severity**: Minor
**Precondition**: email addresses info@bitemore.ca or info@glowbal.ca or ...

**Steps to reproduce**:
1. Write an email address in main search

**Expected result**: The search sends the "@" character
**Actual result**: The search does not send the "@" character 
![2021-07-09_11-23](https://user-images.githubusercontent.com/67378322/125048353-7eb74680-e0a8-11eb-9e97-f3d10a392223.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by OleksandrMosiichuk** [comment]
**Production checked**
