### ISSUE TITLE
Undefined in the link name, in broadcast request, after the review or post with objects was published

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2842]
**Severity**: Major

**Steps to reproduce**:
1. Log in
2. Write review or post with object's link
3. Publish the post
4. Open the request broadcast (if it is hive user)

**Expected result**: App name (or something else) in the link name, in broadcast request, after the review was published
**Actual result**: Undefined in the link name, in broadcast request, after the review was published

https://user-images.githubusercontent.com/67378322/125071367-d9a96780-e0c1-11eb-8295-42686b66b170.mp4

![2021-07-09_14-22](https://user-images.githubusercontent.com/67378322/125071382-dd3cee80-e0c1-11eb-922b-e48f42fefa8f.png)

**Comment by AndreyBelichenko** [comment]
1.5 hours

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
