### ISSUE TITLE
Sorting doesn't work correctly by payout at Trending tab (front-end)

### ISSUE THREAD

**Issue by OleksandrMosiichuk** [Waiviogit/waivio#2843]
**Severity:** Minor
**Precondition:** Hive user is logged in

**Steps to reproduce:**

1. Open Trending tab in Hive bar

**Expected result:** Posts are sorted by payout at front-end
**Actual result:** There are posts sorted in incorrect way at front-end

_*from back-end posts are sorted correctly by parameter net_rshares_

![TrendingTab](https://user-images.githubusercontent.com/87119098/125087946-a1138900-e0d5-11eb-9025-5bc8a83c79b6.png)

**Comment by Diana-Cherry-8** [comment]
Duplicate https://github.com/Waiviogit/waivio/issues/2906
