### ISSUE TITLE
[Drop down Menu] 1.Put Rewards second 2.Add a separate link to Drafts

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2848]
yammer 1470
Drop down Menu

1.Put Rewards second 
2.Add a separate link to Drafts
![2021-07-12_09-09](https://user-images.githubusercontent.com/67378322/125239088-d47e2f80-e2f0-11eb-84c6-ef2734ed5e07.png)

**Comment by AndreyBelichenko** [comment]
1h

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
