### ISSUE TITLE
State is displayed after postalCode in left sidebar on the object page 

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2849]
**Severity**: Minor
**Precondition**: 
1, Object with address  https://www.waivio.com/object/mgj-jitlada/updates/address

**Steps to reproduce**:
1. Open the object
2. Pay attention on the address in left sidebar

**Expected result**: The sequence is the same as in the post update, address street city state postalCode country
**Actual result**: State is displayed after postalCode in left sidebar on the object page 
![2021-07-12_10-25](https://user-images.githubusercontent.com/67378322/125248473-c0d8c600-e2fc-11eb-98d5-a21e11a7e392.png)

**Comment by LucyHrinishyna** [comment]
.2 h

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by OleksandrMosiichuk** [comment]
Production checked
