### ISSUE TITLE
[New: dining.gifts / Home page (Phase 1)]  the welcome wizard should be replaced with a permanent homepage that explains the concept in more detail

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2852]
yammer 1472
New: dining.gifts / Home page (Phase 1)

the welcome wizard should be replaced with a permanent homepage that explains the concept in more detail
https://github.com/Waiviogit/waivio/issues/2850

**Comment by LucyHrinishyna** [comment]
12h

**Comment by Diana-Cherry-8** [comment]
Увеличить шрифт Earn rewards к 40px, и чтобы новая строка начиналась со слов "your meal"  (чтобы слова не налазили на картинку слева)

![2021-07-22_10-24](https://user-images.githubusercontent.com/67378322/126603339-7975365e-4fb8-4c13-9478-e67f917ff0df.png)

**Comment by Diana-Cherry-8** [comment]
Увеличить лого и Eat out до 25px, а кнопки Sign in, Sign up, Find Rewards до 20px
![2021-07-22_10-33](https://user-images.githubusercontent.com/67378322/126604325-0c63cc01-8b35-49cc-929d-2ee8e86c0297.png)

**Comment by Diana-Cherry-8** [comment]
Подравнять высоту кнопок
![2021-07-22_10-39](https://user-images.githubusercontent.com/67378322/126604715-c40b2826-fdd1-4156-829f-58ffa730f030.png)

**Comment by Diana-Cherry-8** [comment]
После нажатия на Find restaurants (link to the map with open left bar on desktop) должно быть, но открывается карта с закрытой левой панелью, а если нажать на кнопку для открытия левой панели перебрасывает на home page

https://user-images.githubusercontent.com/67378322/126605342-5145334c-4e0b-409b-b1fd-573938d7b3a8.mp4

**Comment by Diana-Cherry-8** [comment]
Не правильная ссылка если нажать на Learn more в секции "It's as easy"
![2021-07-22_10-50](https://user-images.githubusercontent.com/67378322/126605900-bdc6e482-2518-4eaf-862f-4f96339d98af.png)
![2021-07-22_10-50_1](https://user-images.githubusercontent.com/67378322/126605910-da513141-d0c0-48e4-b606-d863aa80621c.png)

**Comment by Diana-Cherry-8** [comment]
Не правильная ссылка если нажать на Learn more в секции "Withdrawing your rewards"
![2021-07-22_10-52_2](https://user-images.githubusercontent.com/67378322/126606070-9dcffd15-4d71-4e7f-8b92-724f6aef592a.png)
![2021-07-22_10-52](https://user-images.githubusercontent.com/67378322/126606080-0ec74ea1-54d5-48df-a664-f678676a6435.png)

**Comment by Diana-Cherry-8** [comment]
Ссылка на github поставить https://github.com/Waiviogit/waivio

**Comment by Diana-Cherry-8** [comment]
Home - не кликабельна
![2021-07-22_11-03](https://user-images.githubusercontent.com/67378322/126607302-ac2e1b3e-f605-4606-808a-36530d9cdcce.png)

**Comment by Diana-Cherry-8** [comment]
Добавить отступ после линии на мобилке
![2021-07-22_11-09](https://user-images.githubusercontent.com/67378322/126608257-3787d7a5-a603-40c7-9139-3887628ed2d6.png)

**Comment by Diana-Cherry-8** [comment]
Добавить отступы побольше между карточками
![2021-07-22_11-11](https://user-images.githubusercontent.com/67378322/126608355-74529a34-4ed4-4865-8550-fec6b6e81012.png)

**Comment by Diana-Cherry-8** [comment]
В мобилке кнопку Find Rewards расположить под Sign Up
![2021-07-22_11-26](https://user-images.githubusercontent.com/67378322/126610246-50840223-f85a-4a7f-9a41-260e1799f149.png)
![2021-07-22_11-27](https://user-images.githubusercontent.com/67378322/126610274-cdbe9d32-4725-4722-ac8a-9da5e19683e1.png)

**Comment by Diana-Cherry-8** [comment]
В названии кнопок нужно чтобы второе слово начиналось с большой буквы: Sign In, Sign Up, Learn More

**Comment by Diana-Cherry-8** [comment]
Нехватает строки 
Dining.Gifts makes rewards fun, like they’re meant to be.

![2021-07-22_11-35](https://user-images.githubusercontent.com/67378322/126611320-3e380cb0-bebb-4c62-814d-f3a9e775e1a9.png)
![2021-07-22_11-36](https://user-images.githubusercontent.com/67378322/126611363-1489f119-8d9e-40a4-a142-93e6a1fdfeab.png)

**Comment by Diana-Cherry-8** [comment]
Картинки в карточках должны быть внутри
![2021-07-22_11-40](https://user-images.githubusercontent.com/67378322/126611828-7ec83896-0398-465e-b30f-68bf5bef6ebf.png)
![2021-07-22_11-40_1](https://user-images.githubusercontent.com/67378322/126611846-cfd6a8b5-3dae-464f-930a-501f1b0f3313.png)

**Comment by Diana-Cherry-8** [comment]
Текст в карточках 2 и 3 должен быть, как над карточкой: 
Reserve your reward
Share two photos of your dish & earn!
![2021-07-22_11-43](https://user-images.githubusercontent.com/67378322/126613357-2fd419e1-a829-4daf-a4f7-9e17615f6c4f.png)
![2021-07-22_11-54](https://user-images.githubusercontent.com/67378322/126613465-c34fee70-7d38-47f5-80e8-affe1a7399fc.png)

**Comment by Diana-Cherry-8** [comment]
Добавить отступ после названия шага и карточкой
![2021-07-22_11-57](https://user-images.githubusercontent.com/67378322/126614198-c921d474-25a1-47ab-802a-cdc08ebd3b7c.png)

**Comment by Diana-Cherry-8** [comment]
текст We let you более красным #e83c04
![2021-07-22_12-02](https://user-images.githubusercontent.com/67378322/126614631-b94557c8-5bd7-4715-802b-168fc1606acf.png)

**Comment by Diana-Cherry-8** [comment]
Dining.Gifts можно сделать font-weight: 500; (font-size будет 25px)
![2021-07-22_13-34](https://user-images.githubusercontent.com/67378322/126626268-b599d801-adcb-48d4-affa-4a1114e6015c.png)

**Comment by Diana-Cherry-8** [comment]
Немного нужно расширить отступ между строками главного тайтла Earn rewards - 40px
![2021-07-22_14-00](https://user-images.githubusercontent.com/67378322/126629275-3802a86f-c28e-4ac0-9c62-3d2665ac8927.png)

**Comment by Diana-Cherry-8** [comment]
Опечатка
![2021-07-22_16-15](https://user-images.githubusercontent.com/67378322/126644990-dfbf99bd-793e-46ed-9c7c-cbb4786e8e1b.png)

**Comment by Diana-Cherry-8** [comment]
Fix title
![2021-07-22_16-20](https://user-images.githubusercontent.com/67378322/126645902-22f5e2bc-b560-4650-8138-b84da80edd6b.png)

**Comment by Diana-Cherry-8** [comment]
Пустая поисковая панель, после нажатия на Find Rewards

https://user-images.githubusercontent.com/67378322/126648463-793e11d0-f764-4742-b565-8733baef266c.mp4

**Comment by Diana-Cherry-8** [comment]
Добавить треугольник выпадающий список меню на home page, для авторизованого пользователя
![2021-07-23_08-58](https://user-images.githubusercontent.com/67378322/126742784-942cd5fe-50b6-4433-89c9-be21d13ba875.png)
![2021-07-23_08-58_1](https://user-images.githubusercontent.com/67378322/126742803-623e88e6-ccde-414d-9652-0f01dc7730d1.png)

**Comment by Diana-Cherry-8** [comment]
На мобилке текст поднять выше чтобы кнопка не выходила за пределы картинки
![2021-07-23_09-08](https://user-images.githubusercontent.com/67378322/126743423-3c4316ae-66ca-45ef-bb38-308b527c78bb.png)

**Comment by Diana-Cherry-8** [comment]
На ipad срезает карточки
![2021-07-23_09-32](https://user-images.githubusercontent.com/67378322/126745383-eb7fae30-c5f9-4e79-9d40-d7f06e9f5d28.png)

**Comment by Diana-Cherry-8** [comment]
Плывет верстка у iphone 6/7/8
![2021-07-23_09-42](https://user-images.githubusercontent.com/67378322/126746076-295e745d-d988-4b81-8393-dc27252b1a09.png)

**Comment by Diana-Cherry-8** [comment]
ipad footer 2 колонки соединяются
![2021-07-23_09-51](https://user-images.githubusercontent.com/67378322/126746931-649d346a-9f79-4eab-99db-69c2f52d196c.png)

**Comment by Diana-Cherry-8** [comment]
Если перейти на другую страницу проскролить вниз и вернуться на home page, то home page откроется тоже проскролиная

https://user-images.githubusercontent.com/67378322/126747851-63577dc5-ad96-438c-8bfb-803be30aeb22.mp4

**Comment by Diana-Cherry-8** [comment]
В название вкладки добавить Dining.Gifts
![2021-07-23_11-15](https://user-images.githubusercontent.com/67378322/126755182-37fb33ac-3e91-4819-9754-101ad715e6f3.png)

**Comment by Diana-Cherry-8** [comment]
Sign in кнопка потеряла стиль
![2021-07-23_12-00](https://user-images.githubusercontent.com/67378322/126760047-ceb18b72-fbd1-40bd-bc42-f12a133134c1.png)
![2021-07-23_12-00_1](https://user-images.githubusercontent.com/67378322/126760114-3239dd15-b724-49cf-9f78-669b07566c60.png)

**Comment by Diana-Cherry-8** [comment]
Withdraw блок на всю страницу розтянулся
![2021-07-23_12-52](https://user-images.githubusercontent.com/67378322/126765931-bed44246-87d4-4956-ab22-ad68e8726a4a.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Нужно заменить картинки на те что в гите
https://user-images.githubusercontent.com/42100432/125363038-c518d980-e324-11eb-9695-d507fd517b2e.png
https://user-images.githubusercontent.com/42100432/125363053-cd711480-e324-11eb-992b-43954ac5364b.png
https://user-images.githubusercontent.com/42100432/125363074-d5c94f80-e324-11eb-845e-5134929b1f51.png

**Comment by Diana-Cherry-8** [comment]
Опечатка Sign

![2021-07-23_17-24](https://user-images.githubusercontent.com/67378322/126796609-fadca881-825a-495c-a161-04143f46360f.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**
