### ISSUE TITLE
Time changes when currency is changed in Reports tab

### ISSUE THREAD

**Issue by OleksandrMosiichuk** [Waiviogit/waivio#2857]
**Severity:** Minor
**Precondition:** User is logged in

**Steps to reproduce:**

1. Open Rewards tab
2. Open Reports tab from Campaigns bar
3. Change currency
4. Look at date and time in field "Till"

**Expected result:** Date and time didn't change
**Actual result:** Time changed

https://user-images.githubusercontent.com/87119098/125805291-1b7227e5-035d-4aa9-a0f5-1ee3c836147f.mp4

**Comment by Diana-Cherry-8** [comment]
**Not a bug**
