### ISSUE TITLE
[Editor / Search] increase the width of the window for displaying search results so that you can read the names of objects

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2858]
yammer 1474
editor / search

increase the width of the window for displaying search results so that you can read the names of objects
![2021-07-16_10-25](https://user-images.githubusercontent.com/67378322/125908934-e12f84f5-5f4c-4a65-8fcb-d79a62f49833.png)

(и надо вернуть типы)

**Comment by AndreyBelichenko** [comment]
1.5h

**Comment by Diana-Cherry-8** [comment]
Если поиск с решеткой вначале строки, то поле как впритык к краю экрана, на мобилке
![2021-07-22_12-44](https://user-images.githubusercontent.com/67378322/126619903-eaf4d695-71dc-4d73-80f6-dcc582d563a0.png) 
Если в конце то все норм
![2021-07-22_12-45](https://user-images.githubusercontent.com/67378322/126620009-2ba1304c-1e70-4e3b-9d32-c69855214597.png)

**Comment by Diana-Cherry-8** [comment]
Прям в самом начале если поставить воспроизводится 
![2021-07-28_15-37](https://user-images.githubusercontent.com/67378322/127323468-cf63d070-62e1-422c-bcbf-345b43207423.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
