### ISSUE TITLE
In request https://waiviodev.com/api/user/{userName}/userMetadata you need to send all information about the object

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2860]
On get and put you need to send all information about the object
![2021-07-16_14-21](https://user-images.githubusercontent.com/67378322/125940082-ff63285a-fb4a-4877-9c81-91ddf7c216dd.png)

**Comment by YaroslavSemeniuk** [comment]
It makes no sense to save the entire object, since we have a separate request _(/api/wobject)_ that can return all information on the requested objects
https://waiviodev.com/api/docs/#/wobject/post_api_wobject

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
