### ISSUE TITLE
[dining.gifts / Home page] (Phase 2) - add homepage selections to dining.gifts

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2879]
**Front-task** https://github.com/Waiviogit/waivio/issues/2878

yammer 1482
dining.gifts / Home page

(Phase 2) - add homepage selections to dining.gifts
https://github.com/Waiviogit/waivio/issues/2876

**Comment by YaroslavSemeniuk** [comment]
Getting cities with a counter of objects in each: https://waiviodev.com/api/docs/#/wobject/get_api_wobject_count_by_area
Create new prefetch: https://waiviodev.com/api/docs/#/sites/post_api_sites_prefetch
Get prefetches by app: https://waiviodev.com/api/docs/#/sites/get_api_sites_prefetch
Update prefetches in app: https://waiviodev.com/api/docs/#/sites/put_api_sites_prefetch
Get all prefetches: https://waiviodev.com/api/docs/#/sites/get_api_sites_all_prefetches

**Comment by Diana-Cherry-8** [comment]
Нет итальянского ресторана Italian Restaurants - https://dining.gifts/?searchString=italian - image: https://unsplash.com/photos/t8hTmte4O_g
![2021-08-31_16-41](https://user-images.githubusercontent.com/67378322/131513129-e04d1014-ee9e-4b92-a06d-54301f9264cf.png)

**Comment by Diana-Cherry-8** [comment]
Нужно присылать линки для городов
![2021-08-31_17-26](https://user-images.githubusercontent.com/67378322/131520639-1a25281a-35ac-432c-a27d-34ff0e3fddc0.png)

**Comment by Diana-Cherry-8** [comment]
in request prefetch?types=restaurant  limit = 30

**Comment by Diana-Cherry-8** [comment]
Добавить скобки в мобильной версии блока географии
![2021-08-31_18-39](https://user-images.githubusercontent.com/67378322/131533226-7220cb2b-d5e3-45ee-805a-d81ac43fb8ce.png)

**Comment by Diana-Cherry-8** [comment]
Change name to city
![2021-09-01_14-49](https://user-images.githubusercontent.com/67378322/131666362-c4407634-098b-4ced-a34f-e38d4fa983ed.png)

**Comment by Diana-Cherry-8** [comment]
Подравнять для 2х выборок, чтобы ссылка как везде
![2021-09-01_15-07](https://user-images.githubusercontent.com/67378322/131668541-5cc5b51a-6dce-4a31-8cad-9b696889fb9d.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Produciton checked**

**Comment by Diana-Cherry-8** [comment]
Fix route for gluten-free
![2021-09-02_11-45](https://user-images.githubusercontent.com/67378322/131812927-ad05d41f-c4d0-49d0-932d-d4ee643f48c2.png)

**Comment by Diana-Cherry-8** [comment]
Категория Category для dish должна быть для 
Vegan - "vegan" - https://unsplash.com/photos/4MEL9XS-3JQ
Vegetarian - "vegetarian" - https://unsplash.com/photos/IGfIGP5ONV0
Gluten Free - "gluten-free" - https://unsplash.com/photos/-DsFf2weXHc
Sushi - "sushi" - https://unsplash.com/photos/iy_MT2ifklc
BBQ - "bbq" - https://unsplash.com/photos/vNk1zc3tjVA

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
