### ISSUE TITLE
New endpoint for object page with anyx information

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2926]
get_reward_fund
get_current_median_history_price

**Comment by Fesmofet** [comment]
added 3 new endpoints
https://waiviodev.com/api/docs/#/hive/get_api_hive_reward_fund
https://waiviodev.com/api/docs/#/hive/get_api_hive_current_median_history
https://waiviodev.com/api/docs/#/hive/get_api_hive_block_num

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
