### ISSUE TITLE
Nan and undefined displayed for the newest user. Need to receive the default currency USD

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2975]
**Severity**: Major
**Precondition**: New user 

**Steps to reproduce**:
1. Sign in on waivio

**Expected result**: USD by default
**Actual result**: Nan and undefined displayed for the newest user
![2021-08-17_15-08](https://user-images.githubusercontent.com/67378322/129729829-4e6aab03-5769-4ce5-880e-8c8a86663d31.png)
![2021-08-17_15-08_1](https://user-images.githubusercontent.com/67378322/129729833-866458aa-6d93-4524-bb75-4eded6217ef7.png)

**Comment by Diana-Cherry-8** [comment]
У нового аккаунта пока что Nan 

https://user-images.githubusercontent.com/67378322/134511120-f89e089f-7d5e-411c-a3cd-42931a932068.mp4

**Comment by YaroslavSemeniuk** [comment]
fixed

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
