### ISSUE TITLE
No buttons are pressed in the authorization modal window in incognito mode

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2988]
![2021-08-19_18-16_1](https://user-images.githubusercontent.com/67378322/130095036-bf7970de-2e38-4919-aa41-f080e7fb421c.png)

**Comment by AndreyBelichenko** [comment]
Когда включена блокировка куки в инкогнито в настройках браузера, залипает фронт на гугл авторизации. Сделал, что когда первый раз нажимаем кнопку гугл авторизации и куки заблокированны, то показывается сообщение с ошибкой, второй раз кнопка просто задизейблена

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
