### ISSUE TITLE
Can't find the object https://waiviodev.com/object/for-testing/updates

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#2989]
**Severity**: Major
**Precondition**: Object https://waiviodev.com/object/for-testing

**Steps to reproduce**:
1. Enter in search for_testing

**Expected result**: Can find the object https://waiviodev.com/object/for-testing/updates
**Actual result**: Can't find the object https://waiviodev.com/object/for-testing/updates
![2021-08-20_09-57](https://user-images.githubusercontent.com/67378322/130193272-f45d82bb-8df1-4927-bb5d-d495137dcce5.png)

**Comment by Diana-Cherry-8** [comment]
Can't find on staging
![Uploading 2021-09-08_16-10.png…]()

**Comment by YaroslavSemeniuk** [comment]
fixed

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
