### ISSUE TITLE
[Profile / Images] on the Appreciator profile: 1. pictures in posts are not shown and 2. there is no background profile (another standard?)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3004]
yammer 1508
Profile / Images

on the Appreciator profile: 1. pictures in posts are not shown and 2. there is no background profile (another standard?)
![2021-08-31_09-34](https://user-images.githubusercontent.com/67378322/131453700-731d0e43-9ec3-4702-a905-733fd5e43194.png)

**Comment by YaroslavSemeniuk** [comment]
There is no problem on the backend. We need to create a task for the frontend.
Links:
https://waivio.com/@appreciator - problem with background (on prod & staging) + problem with images on posts (on prod)
https://www.waivio.com/@waivio - problem with 2 last post (on prod)
![appreciator](https://user-images.githubusercontent.com/73386293/132858444-13d4ae11-58fc-46e7-91c8-cdfb58f9b13c.png)
![waivio](https://user-images.githubusercontent.com/73386293/132858458-267e8905-ae61-4ea9-b731-90abaddb7dff.png)
