### ISSUE TITLE
[profiles / mana] some profiles show incorrect data (upvoting mana, resource credits, post rewards)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3012]
yammer 1514
profiles / mana

some profiles show incorrect data (upvoting mana, resource credits, post rewards)
![2021-09-01_09-52](https://user-images.githubusercontent.com/67378322/131625513-3406f542-32ad-4e2b-9ca1-86bbca7303a1.png)

**Comment by Fesmofet** [comment]
пост флагнут вейлом поэтому 0. upvoting mana && rc иногда не отправляется запрос rc_api.find_rc_accounts поэтому тоже 0

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
