### ISSUE TITLE
Understand the logic of payment proposals for the tokenfunds contract

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3029]

**Comment by Fesmofet** [comment]
Логика выплат по proposals:
выбираются записи и сортируем по 2 критериям: 1) weight 2) creation time
proposal с самым большим weight получает преимущество в выплате (Max Payment Per Day = 100 proposal1 per day = 80; weight 100  proposal2 per day = 80; weight 99, proposal1 получает 80 proposal2 20)
В случае если weight одинаковый преимущество получает proposal который создан раньше

Max Payment Per Day: 
если нет активных proposal  новые токены не issue
если есть активный(е) proposal и их суммарный per day < Max Payment Per Day, допустим  sum всех proposal 70, а Max Payment Per Day 100, будет issued 70 токенов

**Comment by Diana-Cherry-8** [comment]
issue - это выпуск токена

**Comment by Diana-Cherry-8** [comment]
https://github.com/Waiviogit/waivio/wiki/About-token

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
