### ISSUE TITLE
Search and filters

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3041]
Add on waivio and dining.gifts search by  :
- title 
- description
- tags

Exclude on dining.gifts search by :
- email
- phone number
- address

Поиск по фильтру на dining.gifts имеется ввиду слово фильтра добавляет как and параметр в верхнюю строку.
При этом исключать адрес.
Фильтр должен давать не меньше результатов чем обычный поиск стрингой.

**Баг посмотреть:** Фильтр vegan или tuna -> результатов меньше и они другие чем с поиском со стрингой. Те точки которые есть при фильтре, нет при обычном поиске

**Comment by Diana-Cherry-8** [comment]
Потом нужно будет проверить, что после выбора фильтра отображается по 3 варианта с dish или drink от каждого ресторана (с самым большим weight)
![2021-09-13_14-27](https://user-images.githubusercontent.com/67378322/133075846-3854448a-3325-4f3e-863d-54f01d308c30.png)

**Comment by Diana-Cherry-8** [comment]
Не понятно почему на стейджине рестораны
![2021-09-17_11-48](https://user-images.githubusercontent.com/67378322/133753905-efe3bec3-7ff3-4618-8e0b-3d293ec24465.png)

**Comment by Diana-Cherry-8** [comment]
Запрос wobjectSearch теперь отрабатывает 5 секунд, на проде 1
![2021-09-17_12-58](https://user-images.githubusercontent.com/67378322/133764630-814c85e6-e7b7-4968-83dd-32a8ce4536cc.png)

**Comment by Diana-Cherry-8** [comment]
На waivio запрос generalSearch также стал отрабатывать дольше 
![2021-09-20_13-15](https://user-images.githubusercontent.com/67378322/133986887-e4d44ed8-87c2-4e25-b5b2-f89f2599d7ba.png)

**Comment by Diana-Cherry-8** [comment]
Длинную серч стрингу идет как флешбеками до того как будет окончательный вариант

https://user-images.githubusercontent.com/67378322/134024030-af022b71-ec37-4aff-b4b9-b3346bc606a1.mp4

**Comment by Diana-Cherry-8** [comment]
Поиск по search String ухудшился 
![2021-09-21_09-58](https://user-images.githubusercontent.com/67378322/134126178-5ea3ad33-c064-450e-a67f-36673ace6427.png)

при вводе слова pork на странице объекта нет этого слова нигде
https://waiviodev.com/object/gov-meat-platter-for-two/updates
https://dining.pp.ua/map?type=dish&showPanel=true&center=49.2268638%2C-123.1288576&zoom=12&Ingredients=chicken&searchS
![2021-09-21_10-20_1](https://user-images.githubusercontent.com/67378322/134128543-a26c1eb8-304d-49f3-a2b9-fcdc9637a9c2.png)
tring=pork
![2021-09-21_10-20](https://user-images.githubusercontent.com/67378322/134128535-63e33227-7bba-4793-9e15-25938322a97a.png)

**Comment by Diana-Cherry-8** [comment]
https://dining.pp.ua/object/ybf-saganaki

![2021-09-21_10-28](https://user-images.githubusercontent.com/67378322/134129476-fc6d30bd-11de-4dfc-9620-218df9f20fe7.png)
![2021-09-21_10-28_1](https://user-images.githubusercontent.com/67378322/134129484-f77db5e0-f6b6-48c1-adb1-a0c45870b42d.png)

**Comment by YaroslavSemeniuk** [comment]
При вводе строки отправляется очень много запросов (практически на каждый вводимый символ). Необходимо увеличить задержку при вводе символов.

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Не исключали:

- email
- phone number
- address

**Production checked**
