### ISSUE TITLE
[notifications / route] when assigning a withdraw route, 1. the notification text should be 'waivio.match set withdraw route to waivio' 2. this notification did not appear in the waivio.match history

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3054]
**Front-task** https://github.com/Waiviogit/waivio/issues/3055

yammer 1527
notifications / route

when assigning a withdraw route, 
1. the notification text should be 'waivio.match set withdraw route to waivio' 
2. this notification did not appear in the waivio.match history
![2021-09-10_09-05](https://user-images.githubusercontent.com/67378322/132807501-88aa16bc-29a0-41de-b624-e513d8440488.png)

**Comment by Fesmofet** [comment]
https://hiveblocks.com/tx/3d89725c196f4d2dcb8da35ed6b98abf805f33a0

**Comment by YaroslavSemeniuk** [comment]
Sent the same notification (withdraw_route), only with percent > zero

**Comment by Diana-Cherry-8** [comment]
Отправитель с получателем отображаются наоборот:

Account daine-cherry2(получатель) registered withdraw route for wiv01(отправитель) account 
 **Ожидаемый результат:** наоборот - Account wiv01(отправитель) registered withdraw route for  daine-cherry2(получатель) account
![2021-09-29_13-49](https://user-images.githubusercontent.com/67378322/135254914-67c66c59-e98e-480e-89fc-83383682535f.png)

**Comment by Diana-Cherry-8** [comment]
Получателю не пришло сообщение в телеграм
Только отправителю 
![2021-09-29_13-49](https://user-images.githubusercontent.com/67378322/135255148-1913b38e-8169-4a1a-942a-854d555bd87d.png)

**Comment by Diana-Cherry-8** [comment]
и в целом поменять текст на {отправитель} set withdraw route to {получатель}
![2021-09-29_13-56](https://user-images.githubusercontent.com/67378322/135255589-f9f48445-0d37-448f-85ff-30564bbdc407.png)

**Comment by Diana-Cherry-8** [comment]
Сообщения об route и set, и cancel должны отображаться и в Wallet как на peakd  https://peakd.com/@daine-cherry2/wallet
Сам текст может быть в виде
![2021-09-29_15-03](https://user-images.githubusercontent.com/67378322/135264751-d9b23b60-e43f-4a5c-a740-1acf1fb2a200.png)


![2021-09-29_15-01](https://user-images.githubusercontent.com/67378322/135264627-745c34a1-1376-4b61-a5c2-848755058e08.png)
![2021-09-29_15-02](https://user-images.githubusercontent.com/67378322/135264668-55eb63cb-d286-4c30-880e-6645ff421981.png)

**Comment by YaroslavSemeniuk** [comment]
Notofication's text will be correct when the task is uploaded to production

**Comment by Diana-Cherry-8** [comment]
Нотификации приходят только отправителю
![2021-09-30_09-32](https://user-images.githubusercontent.com/67378322/135399874-7862b6b9-df67-4f78-8e2e-c5b14f40e538.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**
