### ISSUE TITLE
[notifications / route] when canceling a withdraw route, 1. the notification must be "vancouverdining canceled withdraw route to waivio.acc" 2. this notification must be included in the notifications list for vancouverdining

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3056]
**Front-task** https://github.com/Waiviogit/waivio/issues/3057

yammer 1528
notifications / route

when canceling a withdraw route, 1. the notification must be "vancouverdining canceled withdraw route to waivio.acc" 2. this notification must be included in the notifications list for vancouverdining
![2021-09-10_09-08](https://user-images.githubusercontent.com/67378322/132807764-f4ec8c7c-cba8-4fb2-8209-b865f56ab7ce.png)

**Comment by Fesmofet** [comment]
https://hiveblocks.com/tx/97703688dec66ff7ed63b4e9073cbd6682dea8eb

57278054

**Comment by YaroslavSemeniuk** [comment]
The backend sends a message to the front-end and telegram:
![3056](https://user-images.githubusercontent.com/73386293/134313458-84d7e05a-1cc2-4855-8743-a10ded2270dd.jpg)

**Comment by YaroslavSemeniuk** [comment]
The return type has been changed (returned two arrays), it must be synchronized with the front.
Before:
![old](https://user-images.githubusercontent.com/73386293/135453596-fab7d2de-1624-48a1-af23-b3209cdc03a0.png)
Now:
![upd-notification-on-withdraw](https://user-images.githubusercontent.com/73386293/135453615-2af8f049-4a37-49df-a278-fb26e1339cde.png)

**Comment by YaroslavSemeniuk** [comment]
Also added an entry with the type: "set_withdraw_vesting_route" on the transfers_history request.
![transfers history request](https://user-images.githubusercontent.com/73386293/135457486-3cce8aa0-ec97-4079-96b6-0c815db0e56a.png)
