### ISSUE TITLE
[notifications / route] when canceling a withdraw route, 1. the notification must be "vancouverdining canceled withdraw route to waivio.acc" 2. this notification must be included in the notifications list for vancouverdining

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3057]
**Back-task** https://github.com/Waiviogit/waivio/issues/3056

yammer 1528
notifications / route

when canceling a withdraw route, 
1. the notification must be "vancouverdining canceled withdraw route to waivio.acc" 
2. this notification must be included in the notifications list for vancouverdining
![2021-09-10_09-08](https://user-images.githubusercontent.com/67378322/132807764-f4ec8c7c-cba8-4fb2-8209-b865f56ab7ce.png)

**Comment by YaroslavSemeniuk** [comment]
The backend sends a "withdraw_route" notification type to the front-end.
On **percent = zero** - you should write "${from_account} **canceled** withdraw route to ${to_account}"
On **percent > zero** - "${from_account} **set** withdraw route to ${to_account}"

**Comment by Diana-Cherry-8** [comment]
https://hive.blog/hive-148441/@sacrosanct/how-do-i-set-the-withdrawal-of-my-powered-down-hive-automatically-credited-to-a-hive-account-different-from-my-hive-account

https://hivesigner.com/signs

**Comment by Diana-Cherry-8** [comment]
Должен быть текст об отмене
![2022-03-24_14-53](https://user-images.githubusercontent.com/67378322/159920512-3f70d28f-a2a7-4323-8eb2-6691d70671d6.png)

**Comment by Diana-Cherry-8** [comment]
Все линки и внешний вид нотификаций как в последних комментариях для  #3055

**Comment by Diana-Cherry-8** [comment]
Поправить текст в нотификации для того кто устанавливал и отменял (daine-cherry2)
Ожидаемый результат: You canceled withdraw vesting to daine-cherry
Актуальный результат: Withdraw vesting route is canceled to daine-cherry

![2022-04-07_11-35](https://user-images.githubusercontent.com/67378322/162157254-a2901950-ea89-400f-9835-f49c3c96d5cb.png)

**Comment by Diana-Cherry-8** [comment]
Поправить текст в нотификации для того **кому** устанавливал и отменял (daine-cherry)
**Ожидаемый результат:** daine-cherry2 canceled withdraw vesting to you
**Актуальный результат:** Withdraw vesting route is canceled from daine-cherry2
![2022-04-07_11-38](https://user-images.githubusercontent.com/67378322/162157916-2506f919-13d0-4e66-a3e1-04dfc9e77dbe.png)

**Comment by Diana-Cherry-8** [comment]
Если это cancel показывать проценты не нужно
![2022-04-07_11-42](https://user-images.githubusercontent.com/67378322/162158596-04676109-4356-41d6-8cf8-912b153a45f0.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
