### ISSUE TITLE
[object card / narrow] when the width of the card decreases, the ratings cease to fit, you need to remove the first column of ratings so that the second column is shown without clipping descriptions.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3088]
yammer 1539
object card / narrow

when the width of the card decreases, the ratings cease to fit, you need to remove the first column of ratings so that the second column is shown without clipping descriptions.
![2021-09-20_09-08](https://user-images.githubusercontent.com/67378322/133962398-59c40120-ee71-454b-b75a-bb594f3d24f9.png)

**Comment by Diana-Cherry-8** [comment]
The long name of the rating can go beyond the map
![2021-09-23_11-37](https://user-images.githubusercontent.com/67378322/134477812-b04bb939-a5df-4df8-b849-8fec50b12d3f.png)
![2021-09-23_11-39](https://user-images.githubusercontent.com/67378322/134477819-c81f33c6-2392-4a59-987b-73a6636867e3.png)

**Comment by otoradze** [comment]
исправил , запулил

**Comment by Diana-Cherry-8** [comment]
Need to fix on iPad and iPad Pro, for primary and secondary 
![2021-09-24_10-26](https://user-images.githubusercontent.com/67378322/134635242-f738612b-9887-413a-8038-e2fd899b5dd1.png)

**Comment by Diana-Cherry-8** [comment]
For iPad hide Details link (like for mobile)
![2021-09-24_10-43](https://user-images.githubusercontent.com/67378322/134637557-719752ea-c0c0-40bd-8dc2-0a7376385951.png)
![2021-09-24_10-44](https://user-images.githubusercontent.com/67378322/134637605-9c45384e-9eff-4113-a257-e62672c23d42.png)

**Comment by Diana-Cherry-8** [comment]
Try the option if the name in the second column is less than 4 characters long, then remove the 1sr column and leave the 2d
![2021-09-24_10-53](https://user-images.githubusercontent.com/67378322/134638737-d0ff66ae-7a74-492f-ac17-3823e469b1bd.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**
