### ISSUE TITLE
[wallet / HE] in the Hive Engine wallet, the first 4 positions are given to the specified SWAP tokens, then all HE tokens, where the user does not have a zero balance, go

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3179]
**Back-task** https://github.com/Waiviogit/waivio/issues/3178

yammer 1563
wallet / HE

in the Hive Engine wallet, the first 4 positions are given to the specified SWAP tokens, then all HE tokens, where the user does not have a zero balance, go
![2021-10-19_09-06](https://user-images.githubusercontent.com/67378322/137853037-f670f600-67a8-4ae7-ade9-b385f4307809.png)

**Comment by LucyHrinishyna** [comment]
Без сортировки SWAP токенов, на коле уточним у Александра

**Comment by Diana-Cherry-8** [comment]
https://waiviodev.com/@dining.gifts/transfers?type=ENGINE вечный спиннер крутиться у пользователя dining.gifts на Hive engine кошельке
![2021-12-15_13-08](https://user-images.githubusercontent.com/67378322/146175954-5ee6fe29-e30d-432d-8f67-d82e18a68439.png)

**Comment by Diana-Cherry-8** [comment]
Если ломаный аватар, то лучше без текст, просто чтобы пустая ломаная картинка отображалась SWAP.ETH
https://waiviodev.com/@flowmaster/transfers?type=ENGINE ->
![2021-12-15_13-14](https://user-images.githubusercontent.com/67378322/146176725-c15f82d6-362f-45ea-8138-bb5360d4fea2.png)

**Comment by Diana-Cherry-8** [comment]
У токена Bee отличается value на waivio с peakd
![2021-12-15_13-19](https://user-images.githubusercontent.com/67378322/146177793-29582b9e-2be5-48f3-8409-a7497a525359.png)

**Comment by Diana-Cherry-8** [comment]
Очень много запросов летит на кошельке, при скролле вниз https://waiviodev.com/@dia-monds/transfers?type=ENGINE

https://user-images.githubusercontent.com/67378322/146181743-42e26648-635a-467a-a2aa-b952826ee545.mp4

**Comment by Diana-Cherry-8** [comment]
Нужно скрыть кошелек для гостевых пользователей
![2021-12-15_14-10](https://user-images.githubusercontent.com/67378322/146184324-a86436b8-2f28-4b67-9b54-d582ddffb54e.png)

**Comment by Diana-Cherry-8** [comment]
Промежуточный экран при загрузке hive engine кошелька, если открыть кошелек, перейти на другого пользователя и у другого пользователя перед тем как загрузиться его кошелек, мигает промежуточным экраном кошелек первого пользователя

https://user-images.githubusercontent.com/67378322/146194461-dfe28aa8-e849-4ac6-af27-e165202dd42e.mp4

**Comment by Diana-Cherry-8** [comment]
Есть расхождения в value у HUSTLER, на других токенах тоже встречаются небольшие расхождения (BEE)
![2021-12-16_10-29](https://user-images.githubusercontent.com/67378322/146335786-66f27c38-c6c7-4ed0-8f7e-b2e731937471.png)

**Comment by Diana-Cherry-8** [comment]
У blocktrades падает фронт на hive engine кошельке
https://waiviodev.com/@blocktrades/transfers?type=ENGINE 
![2021-12-16_10-54](https://user-images.githubusercontent.com/67378322/146347543-b438a68a-da55-43ac-a88e-d23571eebb53.png)

**Comment by Diana-Cherry-8** [comment]
у 1х 4 позиций свапов, такое впечатление, что всегда 0.00 value
https://waiviodev.com/@aggroed/transfers?type=ENGINE
https://waiviodev.com/@alexna/transfers?type=ENGINE
![2021-12-16_11-50](https://user-images.githubusercontent.com/67378322/146348919-3f16c574-fb69-4791-850c-5a9bff07700d.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Картинки некоторых валют не отображаются хотя они есть
![2021-12-16_14-39](https://user-images.githubusercontent.com/67378322/146373978-c84d03bc-2101-4136-b5c8-101380462d7a.png)

**Comment by Diana-Cherry-8** [comment]
На hive wallet пропала верхняя граница в темной теме
![2021-12-16_14-46](https://user-images.githubusercontent.com/67378322/146374819-a38c4d46-f9c1-4dec-9fea-97f05c07ccd3.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**
