### ISSUE TITLE
[wallet / advanced] reports are generated only if the user is logged in. Anonymous users should see the same as others, but excluded entries are not saved for them.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3212]
yammer 1575
wallet / advanced

reports are generated only if the user is logged in. Anonymous users should see the same as others, but excluded entries are not saved for them
![2021-10-27_09-03](https://user-images.githubusercontent.com/67378322/139008712-86028b43-5728-4ede-aa85-d49328290b0e.png)

**Comment by AlisherNurlybaev** [comment]
You need to fix the front end, if the user is not autorized, you don't need to send "user" to heareds.
![3212](https://user-images.githubusercontent.com/93185393/140505003-8af74c00-c2e9-4952-b383-7ee6310a5d67.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
