### ISSUE TITLE
[wallet / WAIV chart] add the WAIV exchange rate (USD and HIVE) to the right column. Show the dynamics for the week when opened. For HBD, remove the comparison with BTC.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3244]
**Front-task** https://github.com/Waiviogit/waivio/issues/3243

yammer 1577
wallet / WAIV chart

add the WAIV exchange rate (USD and HIVE) to the right column. Show the dynamics for the week when opened. For HBD, remove the comparison with BTC.

![2021-11-03_16-56](https://user-images.githubusercontent.com/67378322/140084740-09a3fc9b-6799-4898-b977-87034505c931.png)

**Comment by Fesmofet** [comment]
https://waiviodev.com/currencies-api/docs/#/market/get_currencies_api_engine_rates

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Отрицательные цены в графике Waiv -6, -0.3. И в целом подозрительные цены у вейва

https://user-images.githubusercontent.com/67378322/142163600-1b4c8d5a-de1b-412e-baf5-3e29e42653d6.mp4

![2021-11-17_10-33](https://user-images.githubusercontent.com/67378322/142164153-925e642a-ff4d-4e33-beef-788085438306.png)

**Comment by Diana-Cherry-8** [comment]
**Production checked**
