### ISSUE TITLE
[dining.gifts / wizard] search dishes should not be case sensitive

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3316]
yammer 1589
dining.gifts / wizard

search dishes should not be case sensitive
![2021-11-19_11-00](https://user-images.githubusercontent.com/67378322/142595161-f20cebbe-12ed-4447-9f36-3f73a484f5a1.png)

**Comment by AlisherNurlybaev** [comment]
Надо подправить поиск на фронте, так как в response прилетает  целый объект, далее обработка на стороне фронта 
![коммент](https://user-images.githubusercontent.com/93185393/142609125-e72b9760-6ce7-411b-8a12-9a265263af0c.jpg)

**Comment by Diana-Cherry-8** [comment]
**Production checked**
