### ISSUE TITLE
[wallet / WAIV] in the history it is necessary to show: 1. airdrop 2. swap transactions

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3350]
**Front-task** https://github.com/Waiviogit/waivio/issues/3351

yammer 1598
wallet / WAIV

in the history it is necessary to show: 
1. airdrop 
2. swap transactions
![2021-11-25_09-13](https://user-images.githubusercontent.com/67378322/143396227-b4fdcc15-1ea8-4ae1-8021-2c5b1e5f83c0.png)

**Comment by AlisherNurlybaev** [comment]
11087076 - start airdrop 
11089191-end airdrop
11729880 - start swap

**Comment by AlisherNurlybaev** [comment]
http://localhost:8099/campaigns-api/api-docs/#/Account-history/post_hive_engine_account_history

**Comment by Diana-Cherry-8** [comment]
https://github.com/Waiviogit/waivio/issues/3373#issuecomment-1004659054

**Comment by Diana-Cherry-8** [comment]
Swap транзакции других токенов не отображаются в истории: например, Swap.Hive -> Bee

https://user-images.githubusercontent.com/67378322/148215357-828f9c4a-5744-4ea3-aec7-9099316f164e.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
