### ISSUE TITLE
Need to update library - franc-min. Because, set the random language for the review, if user writes a review via quick modal. 

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3397]
**Severity**: Minor

**Steps to reproduce**:
1. Open a review https://dining.gifts/@ctrl-news/review-el-furniture-warehouse-warehouse-poutine
or
1. Open dining.gifts
2. Write a review via quick submit photo modal window

**Expected result**: Review in English 
**Actual result**: Review with French
https://user-images.githubusercontent.com/67378322/145174326-d8e7cc3d-007b-4006-a521-3dd627ba8322.mp4

https://user-images.githubusercontent.com/67378322/145174329-ae687b33-b971-434b-b33c-82c2b706e0c7.mp4

![2021-12-08_10-35](https://user-images.githubusercontent.com/67378322/145175881-7fe4063a-354a-4e5e-9984-fa9941702a26.png)
![2021-12-08_14-13](https://user-images.githubusercontent.com/67378322/145206655-646065b8-f2b5-4a71-9b25-b8ba32a73d4b.png)

**Comment by AlisherNurlybaev** [comment]
I tried to update the frech library, it did not give any result, I searched and tested what other libraries you can use, "LanguageDetect" - defines it better, but one of the posts was defined as FR, "cld" - also works incorrectly. Only "langdetect" detects correctly, but does not support all languages from our list

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
