### ISSUE TITLE
[post / rewards] when the user made a post, the rewards were listed at $ 10. Then, he edited the post and after that there was $ 0. In Receivables, the amount is correct.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3420]
yammer 1517
post / rewards

when the user made a post, the rewards were listed at $ 10. Then, he edited the post and after that there was $ 0. In Receivables, the amount is correct.
https://www.waivio.com/@waivio_beer
![2021-12-15_09-11](https://user-images.githubusercontent.com/67378322/146140147-e7ce361c-d3b6-4fda-9824-7a254a306604.png)

**Comment by Fesmofet** [comment]
campaignId removed while editing from json_metadata

**Comment by ubitinonevami** [comment]
на 10.03
branch - bugfix/WAIV-3420-lost-rewards-after-edit
решена проблема того, что не передавалось в запросе campaignId, reservation_permlink 
но проблему обнуления rewards это не решает

**Comment by ubitinonevami** [comment]
протестировано еще раз, рабоьтает корректно

**Comment by Diana-Cherry-8** [comment]
Модальное окно с проверкой требований не подтягивает ссылки объектов, хотя они по умолчанию добавляются. Нельзя опубликовать ревью обычным способом, через waivio
![2022-03-10_16-41](https://user-images.githubusercontent.com/67378322/157685740-cd79f2bd-6d9b-4a8b-a9ba-c919127382d8.png)

https://user-images.githubusercontent.com/67378322/157685774-afb67023-7fe4-4607-932d-1fb2f48187f3.mp4

**Comment by Diana-Cherry-8** [comment]
Ревью опубликованное через dinings.club не записалось как ревью, у спонсора его нет
![2022-03-10_16-52](https://user-images.githubusercontent.com/67378322/157687812-e9b4543f-1bc4-4e92-a1b1-0966782a618c.png)
![2022-03-10_16-52_1](https://user-images.githubusercontent.com/67378322/157687816-34fd52ec-a6e6-4562-beee-c6a94529fd57.png)

**Comment by ubitinonevami** [comment]
Не уверена, что проблема на фронте
я локально переключилась на ветку, на которой не было моих изменений, создала review, в rewards не появилось 

@mnbmnb87/review-el-furniture-warehouse-mushroom-swiss-burger - review 

данные при создании 
* author: "mnbmnb87"
* body: "<p>User mnbmnb87 (@mnbmnb87) has reserved the rewards of 1.107 HIVE for a period of 7 days to write a review of <a href=\"/object/ufi-mushroom-swiss-burger\">Mushroom Swiss Burger</a>, <a href=\"/object/wjv-el-furniture-warehouse\">El Furniture Warehouse</a></p>\n    <p><b>User eligibility requirements:</b></p>\n<p>Only users who meet all eligibility criteria can participate in this rewards campaign.</p>\n<ul>\n    <li>Minimum Waivio expertise: 0</li>\n    <li>Minimum number of followers: 0</li>\n    <li>Minimum number of posts: 0</li>\n</ul>  <ul><li>User account is not blacklisted by <a href='/@wiv01'>wiv01</a> or referenced accounts.</li></ul> <p><b>Post requirements:</b></p>\n<p>For the review to be eligible for the award, all the following requirements must be met:</p>\n<ul><li>Minimum 1 original photos of <a href=\"/object/undefined\">Mushroom Swiss Burger</a></li>  <li>Link to <a href='/object/undefined'>Mushroom Swiss Burger</a></li>\n<li>Link to <a href=\"/object/wjv-el-furniture-warehouse\">[object Object]</a></li></ul>   <p>Sponsor reserves the right to refuse the payment if review is suspected to be fraudulent, spam, poorly written or for other reasons as stated in the agreement.</p> <p><b>Reward:</b></p>\n<p>The amount of the reward is determined in HIVE at the time of reservation. The reward will be paid in the form of a combination of upvotes (Hive Power) and direct payments (liquid HIVE). Only upvotes from registered accounts (<a href='/@wiv01'>wiv01</a>  ) count towards the payment of rewards. The value of all other upvotes is not subtracted from the specified amount of the reward.</p> <p><b>Legal:</b></p>\n<p>By making the reservation, you confirm that you have read and agree to the <a href=\"/object/xrj-terms-and-conditions/page\">Terms and Conditions of the Service Agreement</a> </p> "
* json_metadata:{"waivioRewards":{"type":"waivio_assign_campaign","approved_object":"ufi-mushroom-swiss-burger","currencyId":"622b3c717a126a57b7de3763"}}
* parent_author: "wiv01"
* parent_permlink: "activate-monterey-4uqiipspnfh"
* permlink: "reserve-7uz5rsd0txt"
* title: "Rewards reservations"

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
