### ISSUE TITLE
[posts / delete] allow users to delete their posts (Guest part)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3438]
**Front-task** https://github.com/Waiviogit/waivio/issues/3439 https://github.com/Waiviogit/waivio/issues/3501

yammer 1529
posts / delete

allow users to delete their posts
![2022-01-04_09-20](https://user-images.githubusercontent.com/67378322/148023223-2d9bdaff-d525-4447-ac4b-dc3ec5a17445.png)

**Comment by Diana-Cherry-8** [comment]
Должностные обязательства не пропали после удаления поста у https://www.waivio.com/@ctrl-news (спонсор - wiv01)

https://user-images.githubusercontent.com/67378322/150166667-b4b121d2-76b6-489d-befc-1d9aac22a99c.mp4

**Comment by Diana-Cherry-8** [comment]
**Production checked**

**Comment by Diana-Cherry-8** [comment]
For Guest

**Comment by AlisherNurlybaev** [comment]
Request data expamle for WaivioAuth servise:
{"id":"waivio_guest_delete_comment","data":{"root_author":"guest07","permlink":"4cxzcn-my-firs"},"userName":"waivio_example"}

**Comment by Diana-Cherry-8** [comment]
Посты удаляются, но ответ выглядит так
![2022-02-16_09-30](https://user-images.githubusercontent.com/67378322/154224523-e2e60e2a-0470-40d2-9009-d4bc710fa122.png)
