### ISSUE TITLE
[waiv / history] this account had transactions older than 18 days (transfer, diesel pool launch), but they are not visible in history

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3443]
yammer 1532
waiv / history

this account had transactions older than 18 days (transfer, diesel pool launch), but they are not visible in history
https://www.waivio.com/@waiv.defi/transfers?type=WAIV
![2022-01-06_09-02](https://user-images.githubusercontent.com/67378322/148342433-4fa61784-3ded-40a2-84d9-fe2421cd3232.png)

**Comment by lucykolosova** [comment]
я запрашиваю 10, транзакций мне приходит 9 - я больше не запрашиваю.

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
