### ISSUE TITLE
[posts / odyssey] add support for odyssey videos when creating posts

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3444]
yammer 1533
posts / odyssey

add support for odyssey videos when creating posts
![2022-01-06_09-04](https://user-images.githubusercontent.com/67378322/148342654-4d151b3e-75d1-4843-98e9-32700f524742.png)

**Comment by Diana-Cherry-8** [comment]
Другие ресурсы видео которые мы поддерживаем https://github.com/Waiviogit/waivio/issues/2164
https://rumble.com/embed/v8ca18/?pub=4
https://www.bitchute.com/video/9hZ91UDX0V8/
https://vimeo.com/519189256
youtube
https://3speak.tv/

**Comment by ubitinonevami** [comment]
Сейчас у  Odysee нет открытого api для интеграции, iframe блокируется 
есть платформа lbry, которая имеет возможность парсить видео с этой платформы
нужен дополнительный ресерч, как правильно интегрировать

**Comment by Diana-Cherry-8** [comment]
Если пользователь был авторизован на odysee, и копирует ссылку, то у нас видео не загружается - отображается ошибка, так как в ссылке добавляется дополнительный параметр

Ссылка с авторизацией
https://odysee.com/@mises:1/the-unseen-costs-of-covid-policies-per:e?r=6g5L6P4Myuyi5Y2LZNoxfaqYP8vLX1g5

Ссылка без авторизации
https://odysee.com/@mises:1/the-unseen-costs-of-covid-policies-per:e

https://user-images.githubusercontent.com/67378322/164032466-a0f65c25-baab-45c1-9467-9f5278b5050a.mp4

**Comment by Diana-Cherry-8** [comment]
В превью видео с параметрами не подтягивается, а отображается ссылка-текст
![2022-04-20_18-18](https://user-images.githubusercontent.com/67378322/164264938-32630f54-c710-4f67-9acf-9ec2eb786175.png)

**Comment by Diana-Cherry-8** [comment]
Кнопка плюс должна быть около курсора, после вставки видео (например, как при вставке видео с ютуба -> кнопка плюс также падает вниз к курсору)

https://user-images.githubusercontent.com/67378322/164266021-1380048c-cbcb-4d05-a574-ba15aca03fc3.mp4

**Comment by Diana-Cherry-8** [comment]
**Staging checked**
