### ISSUE TITLE
Record address generation for deposit and withdraw

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3464]
**Front-task** https://github.com/Waiviogit/waivio/issues/3368

So we can keep track of who, to whom and when made transactions

**Comment by Fesmofet** [comment]
https://waiviodev.com/api/docs/#/hiveEngine/post_api_hive_engine_deposit_withdraw

**Comment by Diana-Cherry-8** [comment]
После нажатия на Done летит запрос для записи информации о депозите в блокчейн, чтобы мы потом могли это отображать и в истории (эта дополнительная запись только для deposit)
