### ISSUE TITLE
Add notifications in telegram and bells, about delegation, undelegation, power up, power down for other tokens

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3487]
**Front task** https://github.com/Waiviogit/waivio/issues/3525

Add notifications in telegram and bells: 
- delegation 
- undelegation 
- power up 
- power down 
for other tokens

**Comment by AlisherNurlybaev** [comment]
(undeleagte WAIV)
[
  [
    "dia-monds",
    {
      "timestamp": 1643892913,
      "type": "unDelegateFrom",
      "amount": "10 WAIV",
      "memo": "",
      "to": "ctrl-news"
    }
  ],
  [
    "ctrl-news",
    {
      "timestamp": 1643892942,
      "type": "undelegate",
      "amount": "10 WAIV",
      "from": "dia-monds",
      "memo": ""
    }
  ]
]

(delegate WAIV)
 [
  [
    "dia-monds",
    {
      "timestamp": 1643893378,
      "type": "delegateFrom",
      "amount": "10 WAIV",
      "memo": "",
      "to": "ctrl-news"
    }
  ],
  [
    "ctrl-news",
    {
      "timestamp": 1643893385,
      "type": "delegate",
      "amount": "10 WAIV",
      "from": "dia-monds",
      "memo": ""
    }
  ]
]



(delegation HIVE)
[
  [
    "flowmaster",
    {
      "timestamp": 1643893837,
      "type": "delegateFrom",
      "amount": "2 HIVE",
      "memo": "",
      "to": "dia-monds"
    }
  ],
  [
    "dia-monds",
    {
      "timestamp": 1643893840,
      "type": "delegate",
      "amount": "2 HIVE",
      "from": "flowmaster",
      "memo": ""
    }
  ]
]

(undelegate hive)[
  [
    "flowmaster",
    {
      "timestamp": 1643895684,
      "type": "delegate_vesting_shares",
      "amount": "0.000000 VESTS",
      "to": "dia-monds"
    }
  ],
  [
    "dia-monds",
    {
      "timestamp": 1643895688,
      "type": "delegate_vesting_shares",
      "amount": "0.000000 VESTS",
      "from": "flowmaster",
      "memo": ""
    }
  ]
]

**Comment by Fesmofet** [comment]
Сделать отдельно delegation/undelegation hive engine
Hive : if 0 = 100% undelegation а если больше 0 тогда нужно писать "update delegation on 7 HP on some account"

**Comment by Diana-Cherry-8** [comment]
Есть еще действие отмены power down для токенов на hive engine
![2022-02-09_11-14](https://user-images.githubusercontent.com/67378322/153163523-49b547fc-4712-4f42-bb31-d1d0871621ca.png)

![2022-02-09_11-13](https://user-images.githubusercontent.com/67378322/153163146-b59b7da9-c770-449b-87dc-caf4fbb8c583.png)
Нужно будет добавить для этого действие тоже нотификацию в колокольчик и телеграмм. 
Отмена действия только для данного пользователя. Поэтому в колокольчик:
телеграмм:
![2022-02-09_11-21](https://user-images.githubusercontent.com/67378322/153164687-5bce2ad8-9b0e-4fc4-b73b-f7f6876d4ed4.png)


колокольчик:

![2022-02-09_11-19_1](https://user-images.githubusercontent.com/67378322/153164707-73e7bfd1-22e3-4944-8de2-9ca0c99822a4.png)

**Comment by Diana-Cherry-8** [comment]
Для hive при отмене power down отправляются 0 vest, поэтому оно отображается так (то есть нотификация есть)
![2022-02-09_11-41](https://user-images.githubusercontent.com/67378322/153169999-abcbec89-9368-4a59-8c68-3a9fc737216b.png)

**Comment by AlisherNurlybaev** [comment]
cancelUnstake
[
  "username",
  {
    "timestamp": 1644400570,
    "type": "cancelUnstake",
    "account": "username",
    "amonut": "4 WAIV"
  }
]

**Comment by Diana-Cherry-8** [comment]
Опечатки в названиях поля amount ("type": "cancelUnstake", "power_down")
![2022-02-09_16-30](https://user-images.githubusercontent.com/67378322/153222223-2203b3c9-3468-4329-b2ec-697268a0c677.png)

**Comment by Diana-Cherry-8** [comment]
**Production checked**
