### ISSUE TITLE
[wallet / delegations] when you click on the HP delegation, you must show the details of the received and outgoing delegations (for both HIVE and WAIV)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3489]
**Front-task** https://github.com/Waiviogit/waivio/issues/3396

We need 2 endpoints:
- Connect to mysql server - hivesql to make a request from it that will return users who delegated hp;
- endpoint for api, for user - return depositTo, deposit From;  get request;

**Comment by Diana-Cherry-8** [comment]
Fix for vesting_shares: 0. We don't need to show users with vesting_shares: 0
![2022-01-31_09-14](https://user-images.githubusercontent.com/67378322/151752878-65c550d1-4d0d-4262-97a5-38981253ba04.png)

**Comment by Diana-Cherry-8** [comment]
Опечатка в Received
![2022-01-31_09-18_1](https://user-images.githubusercontent.com/67378322/151753409-3e37a90c-7f74-4165-9b58-f7f278d55b9a.png)

**Comment by Diana-Cherry-8** [comment]
В Received должно отображаться не кому делегировано, а от кого (from)
![2022-01-31_09-21](https://user-images.githubusercontent.com/67378322/151753633-b3ac4add-84dc-4aa6-9590-ac4a1f7129a9.png)

**Comment by AlisherNurlybaev** [comment]
request data example for waivioAuth servise:
 {"id":"waivio_guest_delete_comment","data":{"root_author":"guest07","permlink":"4cxzcn-my-firs"},"userName":"waivio_example"}

**Comment by Diana-Cherry-8** [comment]
@Fesmofet  expiring аккаунты нужно показывать, после обычных, тоже от больших до маленьких
https://peakd.com/@zasktrader/wallet
![2022-01-31_15-14](https://user-images.githubusercontent.com/67378322/151801896-ab3a91a6-ef74-4277-800d-51d4ec5033a6.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
