### ISSUE TITLE
[search / results] sometimes, when quickly and correctly typing in a username search, erroneous results are shown, and the user is missing

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3552]
yammer 1663
search / results

sometimes, when quickly and correctly typing in a username search, erroneous results are shown, and the user is missing
![2022-02-10_09-09](https://user-images.githubusercontent.com/67378322/153355804-7ef73994-94b6-477f-a4be-2ecf1569e0b7.png)

**Comment by AlisherNurlybaev** [comment]
Баг со стороны фронта, так как последний результат запроса(https://www.waivio.com/api/users/search) выдает только одного пользователя, но фронт не обновляет список, и выводит результат предыдущего запроса.
![image](https://user-images.githubusercontent.com/93185393/154073147-596ea4ce-02f3-4afd-919c-cd71734f0f2f.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
