### ISSUE TITLE
[guest / posts] The guest post does not include a sponsor and the amount is not included in the reward. In payables, the post is processed correctly.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3639]
yammer 1680
guest / posts

The guest post does not include a sponsor and the amount is not included in the reward. In payables, the post is processed correctly.
https://www.waivio.com/@waivio_how-daryl-rolls
![2022-03-04_09-32](https://user-images.githubusercontent.com/67378322/156719406-f8a54892-4863-4552-a5c0-b819acb94fcf.png)

**Comment by Fesmofet** [comment]
i need campaignId in json_metadata to show sponors obligations

**Comment by Diana-Cherry-8** [comment]
Problem connected to  https://github.com/Waiviogit/waivio/issues/3420

**Comment by Diana-Cherry-8** [comment]
https://www.waivio.com/@waivio_how-daryl-rolls for post we don't have flag active_votes -> sponsor: true

**Comment by Waiviogit** [comment]
check front to send campaignId in json_metadata!!!!!

**Comment by Diana-Cherry-8** [comment]
**Production checked**
