### ISSUE TITLE
Research about what features our editor has supported already

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3752]
Research about what features our editor has supported already, so we can add it in interface
Work with table and numbered list, underline should already work e.t.

**Comment by CodeChel** [comment]
we can add such features:
 1. insert table and lists, labeled and numbered, example: http://samypesse.github.io/draft-js-table/
 2. Underline and strikethrough text, text color, text size
 3. text alignment (left, center, right)
 4. emoji picker, example: https://jpuri.github.io/react-draft-wysiwyg/#/
 5. button for remove text-styles.
