### ISSUE TITLE
[wallet / multi-step] first complex withdraw operation WAIV > LTC (3 steps written in one json). As development progresses, more options will appear in the Withdraw dialog (HIVE, HBD, BTC, ETH).

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3803]
**Front-task** #3804 

yammer 1704
wallet / multi-step

first complex withdraw operation WAIV > LTC (3 steps written in one json). As development progresses, more options will appear in the Withdraw dialog (HIVE, HBD, BTC, ETH).
![2022-04-19_13-05](https://user-images.githubusercontent.com/67378322/163980692-52eb25a4-75fa-4135-a9e4-80468b5de619.png)

**Comment by Waiviogit** [comment]
to deploy 
api, hive, engine parser, objects bot
