### ISSUE TITLE
Display waiv wallet and history for guest user

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3937]
https://waiviodev.com/api/docs/#/user/get_api_user__userName__guest_wallet
https://waiviodev.com/api/docs/#/user/get_api_user__userName__guest_balance

waiv guest balance
https://waiviodev.com/objects-bot/docs/#/object/post_objects_bot_guest_transfer

![2022-05-17_16-08](https://user-images.githubusercontent.com/67378322/168818690-e01a2c9a-264e-466c-9920-e4476e6daba5.png)

**Comment by Waiviogit** [comment]
https://waiviodev.com/api/docs/#/user/get_api_user__userName__guest_wallet

https://waiviodev.com/api/docs/#/user/get_api_user__userName__guest_balance

**Comment by Diana-Cherry-8** [comment]
Убрать Rebalancing вкладку и сам запрос для гостя
![image](https://user-images.githubusercontent.com/67378322/197792081-8f7b9a3e-204b-438b-a10f-78369627fd9a.png)

**Comment by Diana-Cherry-8** [comment]
В нотификации трансфера написано имя waivio.hive вместо имени гостя, от пользователя который отправлял гостю 
![image](https://user-images.githubusercontent.com/67378322/197793042-06b51f4a-55fa-4638-8ec3-826005de0cfe.png)

**Comment by Diana-Cherry-8** [comment]
Гостю нотификация о трансфере не пришла
![image](https://user-images.githubusercontent.com/67378322/197793358-76d8ada4-5b7c-42a1-8906-cc684b44b754.png)

**Comment by Diana-Cherry-8** [comment]
У гостя модалка не закрылась, после нажатия на Continue
![image](https://user-images.githubusercontent.com/67378322/197794632-30536efd-7e8d-4fe1-bf31-c5141a93d7e9.png)

**Comment by Diana-Cherry-8** [comment]
Время отправки отображается неправильно (53 years)
![image](https://user-images.githubusercontent.com/67378322/197795203-65660196-bec1-4fff-8a20-4ec23ab7629b.png)

**Comment by Diana-Cherry-8** [comment]
Нет нотификации у гостя об отправки 
![image](https://user-images.githubusercontent.com/67378322/197795558-75580756-350b-4ea2-853a-6d76f22c0604.png)

**Comment by Diana-Cherry-8** [comment]
При получении от гостя, должно быть написано имя гостя от кого, а не waivio.hive
![image](https://user-images.githubusercontent.com/67378322/197796333-913f995e-521b-47ae-8597-b8b021e3edc3.png)

**Comment by Diana-Cherry-8** [comment]
У гостя был 1 waiv, он его отправил, теперь вместо нуля отображается 0E-8
![image](https://user-images.githubusercontent.com/67378322/197796826-3782dd0e-97da-4548-81a8-203423f68802.png)

**Comment by Diana-Cherry-8** [comment]
Отображается баланс не гостя, а пользователя на чей странице он находится
Шаги воспроизведения:
1. Login гостем
2. Открыть страницу любого пользователя
3. Нажать на Transfer
4. Обратить внимание на Your balance


https://user-images.githubusercontent.com/67378322/197800366-ecbfd5d1-57ab-4d44-bbb4-69a515c5e47d.mp4

**Comment by Diana-Cherry-8** [comment]
**HIVE!**
На **хайве** в истории отображается waiv.hive, и в нотификации гость -> хайв пользователь
(это давно сломалось)
![image](https://user-images.githubusercontent.com/67378322/197950849-87846509-0c79-4a79-aa27-f0f9c15ad94b.png)

**Comment by Diana-Cherry-8** [comment]
**HIVE**
Запрос delegation 500 - если открыть страницу гостя хайв кошелек
Для гостя не нужно отправлять, делегаций на госте нету
![image](https://user-images.githubusercontent.com/67378322/197955134-d04bc90d-fcd3-4bcf-9477-d73dc4a9ad91.png)

**Comment by Diana-Cherry-8** [comment]
История у гостя отображается от самой старой записи до новой, должно быть наоборот, самые новые вверху
![image](https://user-images.githubusercontent.com/67378322/198000274-11f9b4c6-238f-4c85-bdd0-ecace97db8d5.png)

**Comment by Diana-Cherry-8** [comment]
При отправки число округляется, получается может отправляться сума больше чем есть
![image](https://user-images.githubusercontent.com/67378322/198006055-5f4e1196-be94-48ca-ac9b-cf7e9858deb8.png)

**Comment by Diana-Cherry-8** [comment]
Кнопка max всегда подтягивает hive balance
![image](https://user-images.githubusercontent.com/67378322/198009482-99c480e5-28f5-48a6-9595-903e0db8807b.png)

**Comment by Diana-Cherry-8** [comment]
Оплата за ревью гостю выглядит как обычное ревью (wiv01 -> waivio_dianach)
![image](https://user-images.githubusercontent.com/67378322/198016324-3aad6dd2-3220-4286-980a-4a23733cd57b.png)

**Comment by Diana-Cherry-8** [comment]
Для трансфера отображается report и reservation, и сумма положительная
![image](https://user-images.githubusercontent.com/67378322/198039133-18034766-ef44-4a74-aabb-51d1c4536275.png)

--> 
![image](https://user-images.githubusercontent.com/67378322/198016562-79e0e1de-7b4d-4aeb-9392-d19be1303192.png)

**Comment by Diana-Cherry-8** [comment]
Округляет у гостя, и не отправляется
![image](https://user-images.githubusercontent.com/67378322/198040100-25db61f7-975f-49ea-a3f1-8d4f979884f4.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
