### ISSUE TITLE
Add possibility for guest user to transfer waiv to hive account

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3939]
Guest -> hive account
id = transferFromGuest
Send via https://waiviodev.com/auth-service/docs/#/Operation/post_guest_operations

Hive account -> guest
id = transferToGuest

Guest user can send only **HIVE** or **WAIV**, we do not support the rest

In wallet history we need to write the guest name (not a bot name)
![2022-05-17_16-20](https://user-images.githubusercontent.com/67378322/168820810-cbbec173-838f-4496-9925-eff33ec90f26.png)

**Comment by Waiviogit** [comment]
1 request on auth guest operations id: transferFromGuest
body from docs below

https://waiviodev.com/objects-bot/docs/#/object/post_objects_bot_guest_transfer

**Comment by Diana-Cherry-8** [comment]
**Production checked**
