### ISSUE TITLE
[dining.gifts / wizard] dish exists, but the wizard does not find it (everything works in a normal search)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#3963]
yammer 1735
dining.gifts / wizard

dish exists, but the wizard does not find it (everything works in a normal search)

![2022-05-20_11-40](https://user-images.githubusercontent.com/67378322/169489665-c5185ff3-3639-4303-bdf9-0f58564c07c9.png)

**Comment by Diana-Cherry-8** [comment]
Поле для поиска блюда, не показывает варианты блюд, если просто курсор в строку поставить, и если попытаться найти блюда (объекты - Not bad advice, Closed panda)
![image](https://user-images.githubusercontent.com/67378322/177269368-327d722c-6f86-4bae-9069-ff2d0bb56eef.png)

**Comment by Diana-Cherry-8** [comment]
@lucykolosova 
Если выбрать объект для которого нет кампании, то поиск не подтянет нужные варианты, поиск не работает по диш\дринк

https://user-images.githubusercontent.com/67378322/178199421-eb4b298e-be26-4258-b7bb-722ada9c2d7a.mp4

![image](https://user-images.githubusercontent.com/67378322/178199507-c4ab0c18-3962-4c8b-98fc-d0dbbb0d0cec.png)

**Comment by Diana-Cherry-8** [comment]
Не все объекты можно найти

![image](https://user-images.githubusercontent.com/67378322/178200364-546189f9-634c-4dc4-b411-2e5a5ee38781.png)
![image](https://user-images.githubusercontent.com/67378322/178200398-709b8672-d947-453f-9879-ab96a713a2e6.png)

**Comment by katerynapadafa** [comment]
на деве все блюда ищутся и курсор в строку поставить тоже

**Comment by Diana-Cherry-8** [comment]
**Staging checked**
