### ISSUE TITLE
Fix wallet price in dollar

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4169]
**Front-task** https://github.com/Waiviogit/waivio/issues/4188

Нужно брать курс с пуллов

**Comment by Waiviogit** [comment]
https://waiviodev.com/currencies-api/docs/#/rate/get_currencies_api_engine_pools_rate

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
