### ISSUE TITLE
[notifications / powered tokens] when the tokens are transferred to the power up state, the notification text should be the same as in the "Power up from pgm-curator" wallet. Otherwise, the user is afraid that someone has done a power up on his behalf.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4245]
**Back-task** https://github.com/Waiviogit/waivio/issues/4247

yammer 1842
notifications / powered tokens

when the tokens are transferred to the power up state, the notification text should be the same as in the "Power up from pgm-curator" wallet. Otherwise, the user is afraid that someone has done a power up on his behalf.

![image](https://user-images.githubusercontent.com/67378322/183582776-49e6d3d7-e636-446b-939c-eb73d7ead7a1.png)

**Comment by katerynapadafa** [comment]
Waiting for backend

**Comment by Diana-Cherry-8** [comment]
wiv01 сделал power up daine-cherry
у daine-cherry должно быть "to you" вместо "daine-cherry"

![image](https://user-images.githubusercontent.com/67378322/183939802-f35e8e46-c6d2-4555-9cec-79ba95515c55.png)

**Comment by Diana-Cherry-8** [comment]
Текст не тот wiv01
wiv01 -> daine-cherry
**Expected result:** wiv01 initiated 'Power Up' on 1 WAIV to you
You initiated 'Power Up' on 1 WAIV to daine-cherry
![image](https://user-images.githubusercontent.com/67378322/184109569-30db04ff-8445-46e5-ade2-5dd2b58fe056.png)

**Comment by Diana-Cherry-8** [comment]
Если сам себе Power up, то должно быть как раньше
![image](https://user-images.githubusercontent.com/67378322/184110157-5f61019a-73bd-4fe0-bd57-87fa2a573742.png)

**Comment by Diana-Cherry-8** [comment]
wiv01 -> daine-cherry
у wiv01 в колокольчики ссылки на нотификации должны ввести на страницу daine-cherry
и аватары тоже от daine-cherry

![image](https://user-images.githubusercontent.com/67378322/184125179-1878c183-865f-4332-ad5e-4efc99ce3f8a.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
