### ISSUE TITLE
Object import 

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4253]
при делегации указывается минимальная сила голоса

1. сделать эндпоинт сам файл принимается + валидируется то что у юзера есть waiv стейкнутый  1 голос 1 цент апрува минимум и проверять что он делегировал posting 
authorities на нашего бота(для тестов любой акк) + тип объекта (book)

2. json записывается в коллекцию import objects в ней все поля идентичны datafinity + к этому есть поле юзера и типа объекта (book)
когда записали в базу => response 200 скоро импорт начнется

3. или emit или subscriber начать импорт по юзеру

4. импорт объекта, когда он создан лайк по филдам по всем которые ты создала
 надо следить если сила голоса опускается ниже установленной приостанавливать импорт
и если цена 100% голоса опускается ниже цента приостанавливать импорт
? как возобновлять надо подумать

5.после импорта объект из базы надо удалять.

**Comment by MashaYakovenko** [comment]
object-import-service: https://github.com/Waiviogit/object-import-service/pull/2
waivio-node-parser: https://github.com/Waiviogit/waivio-node-parser/pull/434
objects-bot: https://github.com/Waiviogit/objects-bot/pull/42

**Comment by MashaYakovenko** [comment]
merged PR with dockerfile and docker-compose.yml: https://github.com/Waiviogit/object-import-service/pull/6/files

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
