### ISSUE TITLE
Object book. General info + fields

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4270]
**Back-task** https://github.com/Waiviogit/waivio/issues/4277

**Back documentation:** https://github.com/Waiviogit/objects-bot/blob/dev/docs/objectFields.md

Fields:

- [x] ageRange https://github.com/Waiviogit/waivio/issues/4271
- [x] language https://github.com/Waiviogit/waivio/issues/4273
- [x] publicationDate https://github.com/Waiviogit/waivio/issues/4272
- [x] publisher https://github.com/Waiviogit/waivio/issues/4274
- [x] author https://github.com/Waiviogit/waivio/issues/4280
- [x] weight https://github.com/Waiviogit/waivio/issues/4275
- [x] dimensions https://github.com/Waiviogit/waivio/issues/4276
- [x] groupId https://github.com/Waiviogit/waivio/issues/4286  (сначала нужно Options)
- [x] printLength https://github.com/Waiviogit/waivio/issues/4322

Options:
- [x] format https://github.com/Waiviogit/waivio/issues/4285

Add new fields to the About block.
Place "Author" after "Name", all other fields after "Product ID".
![image](https://user-images.githubusercontent.com/67378322/184599067-34b47785-5b41-496f-a62a-27cb42104bf9.png)
![image](https://user-images.githubusercontent.com/67378322/184599105-6c4b596d-9360-4277-9a16-7131d5851ea5.png)

**Comment by Waiviogit** [comment]
https://github.com/Waiviogit/objects-bot/blob/dev/docs/objectFields.md
