### ISSUE TITLE
[object / linking] a comment was added to the post with a link to the object, the object was tied to the post, but the post is not displayed on the object

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4365]
yammer 1869
object / linking

a comment was added to the post with a link to the object, the object was tied to the post, but the post is not displayed on the object
https://www.waivio.com/@chentebass/why-i-like-this-song-or-welcome-home-sanitarium-metallica

![image](https://user-images.githubusercontent.com/67378322/189285737-4a74a0fa-f458-4477-991d-8b0092a79b82.png)

**Comment by Fesmofet** [comment]
Post in Spanish, if you add Spanish in the language settings, the post will be displayed on the object

**Comment by Diana-Cherry-8** [comment]
Подумать о постах с двумя языками

**Comment by Diana-Cherry-8** [comment]
**DONE**
