### ISSUE TITLE
[payable / pay] Add button "Pay all" on Payable tab (for new rewards)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4396]
**Front-task** #4397 

yammer 1880
payable / pay

So that the user can pay for all campaigns at once, add a button "Pay all"
![image](https://user-images.githubusercontent.com/67378322/190961443-f68af1e3-ff33-4d0e-9d61-6ed37413979c.png)

**Comment by Waiviogit** [comment]
This is the job for frontend, reassign. Need to take into account a different memo for guests
