### ISSUE TITLE
[Settings / Shop] By default, the Shop section also displays objects that are linked from the user's posts (or linked to objects through first-level comments). An option is needed in Settings to not show such objects.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4485]
**Back-task** #4484 

yammer 1903
Settings / Shop

By default, the Shop section also displays objects that are linked from the user's posts (or linked to objects through first-level comments). An option is needed in Settings to not show such objects.

Shop
You can manage your public shopping list in the profile. 
__ Do not show objects linked in posts

![image](https://user-images.githubusercontent.com/67378322/196103208-de91c648-6524-48e9-9526-f9c7adb73b47.png)

**Comment by Waiviogit** [comment]
user_metadata.settings.shop.hideLinkedObjects - Boolean

**Comment by Diana-Cherry-8** [comment]
В settings нет этого блока
![image](https://user-images.githubusercontent.com/67378322/220615177-f8594f45-8f0b-475f-a97f-8480cb274284.png)

**Comment by Diana-Cherry-8** [comment]
В мобильной версии, если нажать на сердечко, то будет отображаться подсказка
![image](https://user-images.githubusercontent.com/67378322/220625533-0ac34647-468f-4b9f-8e9e-bb196061e0be.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**
