### ISSUE TITLE
[*.dining.gifts / configuration] add a Website header block, where the user can redefine the site name, message and set the site start page

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4649]
**Back-task** #4648 

yammer 1972
*.dining.gifts / configuration

add a Website header block, where the user can redefine the site name, message and set the site start page

![image](https://cdn.discordapp.com/attachments/537744716066848819/1049422844062339082/image.png)

**Comment by Waiviogit** [comment]
configuration.header = {
  name: { type: String },
  message: { type: String },
  startup: { type: String },
}

**Comment by Diana-Cherry-8** [comment]
В модалке шрифт для названий поля по 16 (сейчас около 18)
И отступ межу полями тоже
![image](https://user-images.githubusercontent.com/67378322/219039356-eea0c1bc-6f7e-4fc3-9902-b7c671ddb92e.png)

**Comment by Diana-Cherry-8** [comment]
Падает фронт на configuration
на ctrl-news
После сохранения нового имени и текста
https://waiviodev.com/123456.dinings.pp.ua/configuration

**Comment by Diana-Cherry-8** [comment]
На dinings.pp.ua падает фронт
https://dinings.pp.ua/
![image](https://user-images.githubusercontent.com/67378322/219040023-d0bd887b-a00b-42cd-b469-8e782587850c.png)

**Comment by Diana-Cherry-8** [comment]
Добавить ограничения по количеству символов для ввода имени и message сайта до 100 символов

**Comment by Diana-Cherry-8** [comment]
В имени сайта нужно будет отбражать текст как в оригинале в поле было введено, а не capslock
![image](https://user-images.githubusercontent.com/67378322/219064101-2cb13162-1435-49ef-9ca9-2bb9890892c2.png)

**Comment by Diana-Cherry-8** [comment]
На странице configuration, отображается название в капслоке и точка после имени
![image](https://user-images.githubusercontent.com/67378322/219293798-fe462f08-05cb-4363-ba7c-40f1d6487fe1.png)
![image](https://user-images.githubusercontent.com/67378322/219293997-c7b7916a-7cb9-43f9-865d-8c75dc770440.png)

**Comment by Diana-Cherry-8** [comment]
Максимальное количество символов 50 для полей имени и меседжа, желательно добавить ошибку, что вы не можете ввести больше 50 символов
![image](https://user-images.githubusercontent.com/67378322/219294587-bf07b805-a9e7-4a37-83d2-c6312608df1e.png)

**Comment by Diana-Cherry-8** [comment]
Для десктопа нужно подправить верстку чтобы уменьшать месседж, доставлять три точки чтобы меню помещались
![image](https://user-images.githubusercontent.com/67378322/219294861-6e8869a6-0cb2-4957-af28-f5c672e2b4ea.png)

**Comment by Diana-Cherry-8** [comment]
Полоску нужно в нужное место

![image](https://user-images.githubusercontent.com/67378322/219295851-c1418c3d-4906-4440-af25-2257366bb973.png)

**Comment by Diana-Cherry-8** [comment]
Точка в конце добавляется
![image](https://user-images.githubusercontent.com/67378322/219313674-95a25cfa-a92e-4647-be33-6fd589582fd3.png)

**Comment by Diana-Cherry-8** [comment]
Если сайт деактивирован нужно глобал открывать

![image](https://user-images.githubusercontent.com/67378322/219359954-066de517-c811-423a-9570-23a8ecca9ad8.png)

**Comment by Diana-Cherry-8** [comment]
Полоска внизу карты увеличилась
![image](https://user-images.githubusercontent.com/67378322/219413283-d308405e-91bf-4918-ad61-b7af7912f35c.png)

**Comment by Diana-Cherry-8** [comment]
Если выбрать About, то будет открываться home page dining gifts
![image](https://user-images.githubusercontent.com/67378322/219643296-aa9d9d3a-e3ee-49c6-a545-96f806885003.png)
![image](https://user-images.githubusercontent.com/67378322/219643372-66ac2260-2bd1-46fd-9324-958d60957e2c.png)

**Comment by Diana-Cherry-8** [comment]
Отступ между дроп-дауном и выпадающим меню для startup page

![image](https://user-images.githubusercontent.com/67378322/219644847-d0f9e884-cbe2-4d2c-a564-f9056cac80cb.png)

**Comment by Diana-Cherry-8** [comment]
Fix опечатку добавить t в Starup -> Startup в модалке
![image](https://user-images.githubusercontent.com/67378322/219645361-60061c42-bcd5-4910-a6f5-7691c41842bd.png)

**Comment by Diana-Cherry-8** [comment]
- Если поле About page не заполнено, то в модалке нужно не показывать About или блокировать Map чтобы нельзя было выбрать About
- И если about страница была удалена, то нужно настройки тоже менять под Map
![image](https://user-images.githubusercontent.com/67378322/219645506-d842584c-c372-4576-9476-60c1f67171b2.png)
![image](https://user-images.githubusercontent.com/67378322/219645945-f980ce67-1bb8-4543-afcc-6c7f2b98b688.png)

**Comment by Diana-Cherry-8** [comment]
Отложили Startup page
