### ISSUE TITLE
[*.social.gifts / products] presentation of products on websites

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#5142]
yammer 2162
*.social.gifts / products

presentation of products on websites
https://github.com/Waiviogit/waivio/issues/5127

_____
Новый вид нужно для типов product и book

**Comment by Diana-Cherry-8** [comment]
Новый вид нужно для типов product и book

**Comment by Diana-Cherry-8** [comment]
Style price:
- по жирности и размеру можно попробовать под имя объекта
- покрасить в цвет сайта
![image](https://github.com/Waiviogit/waivio/assets/67378322/5351b057-a305-4d3d-8192-74f4adc233fe)
(примерный вариант)
![image](https://github.com/Waiviogit/waivio/assets/67378322/71a554af-248c-48f6-8c79-0cd7c9330fe4)

**Comment by Diana-Cherry-8** [comment]
Тайтл можно просто черным, оно ярче получается
![image](https://github.com/Waiviogit/waivio/assets/67378322/77294daa-ddf6-4e06-aa83-6fc6c634e5c2)
![image](https://github.com/Waiviogit/waivio/assets/67378322/bd7b75e1-661c-4f93-9acb-eb908ff32d93)

**Comment by Diana-Cherry-8** [comment]
Отображается только один рейтинг (должно быть два)
https://waiviodev.com/object/rjt-missufe-womens-short-sleeve-ruched-casual-sundress-midi-bodycon-t-shirt-dress
https://dia.socialgifts.pp.ua/object/product/rjt-missufe-womens-short-sleeve-ruched-casual-sundress-midi-bodycon-t-shirt-dress
![image](https://github.com/Waiviogit/waivio/assets/67378322/cdc8ccde-2056-4df9-9026-70093a54809b)
![image](https://github.com/Waiviogit/waivio/assets/67378322/bcb0e635-e5ab-4349-ba8c-dcd02ce26580)

**Comment by Diana-Cherry-8** [comment]
Style buy it on
- добавить uppercase
- цвет стандартный серый (#99aab5)
![image](https://github.com/Waiviogit/waivio/assets/67378322/98f8603e-b1d5-4455-8008-c5e4c57bde58)

**Comment by Diana-Cherry-8** [comment]
Style options name как рейтинг
- font-size 18px
- color black
![image](https://github.com/Waiviogit/waivio/assets/67378322/7573ccb5-85ea-4df9-a189-09c8ed41c600)

**Comment by Diana-Cherry-8** [comment]
Стиль для имени самой опции:
- покрасить в цвет опции

![image](https://github.com/Waiviogit/waivio/assets/67378322/cb0552bc-83ad-44d5-b77e-4434abaab4a2)

**Comment by Diana-Cherry-8** [comment]
Тайтлы разделов покрасить в черный цвет
![image](https://github.com/Waiviogit/waivio/assets/67378322/345997d9-dff1-42e9-8f51-e2ee1698955f)

**Comment by Diana-Cherry-8** [comment]
Пока можно убрать полоски между разделами
![image](https://github.com/Waiviogit/waivio/assets/67378322/f860cf35-4421-43ce-b1ed-8365f1650db7)

**Comment by Diana-Cherry-8** [comment]
Product details можно попробовать завернуть в рамку
- размер рамки подстраивается под количество контента (не на всю ширину страницы)
- края закругленные
- можно добавить box shadow как на secondary карточках rewards box-shadow: 2px 2px 8px -2px var(--website-color);
![image](https://github.com/Waiviogit/waivio/assets/67378322/08ff8902-63c9-4652-a9a8-f486948f31af)

**Comment by Diana-Cherry-8** [comment]
Добавить пробел перед / в BOUGHT TOGETHER/ ADD-ONS
![image](https://github.com/Waiviogit/waivio/assets/67378322/e3e96780-bd35-463c-be2c-a9b62321695d)

**Comment by Diana-Cherry-8** [comment]
Карточки в притык (Add-ons)
![image](https://github.com/Waiviogit/waivio/assets/67378322/ff50a3e8-af44-40a5-bcbf-4d6ec17cce18)

**Comment by Diana-Cherry-8** [comment]
Амазон иконки сдвинулись влево в Add-ons
![image](https://github.com/Waiviogit/waivio/assets/67378322/fa052a2c-643a-49fe-a810-32c078f4b9ba)

**Comment by Diana-Cherry-8** [comment]
После нажатия на карточку в Add-ons нужно скролить вверх, а то переход по объектам незаметный


https://github.com/Waiviogit/waivio/assets/67378322/ce6fcfd2-b59a-43d3-82a8-87813275c1a5

**Comment by Diana-Cherry-8** [comment]
Нет блоков Related и Similar (если они должны быть)
https://waiviodev.com/object/rjt-missufe-womens-short-sleeve-ruched-casual-sundress-midi-bodycon-t-shirt-dress
![image](https://github.com/Waiviogit/waivio/assets/67378322/b3d330e0-cfdc-4e79-a813-486ac8b13f14)

**Comment by Diana-Cherry-8** [comment]
Название рейтинга очень высоко находиться
![image](https://github.com/Waiviogit/waivio/assets/67378322/3c6dc9a4-84a1-473b-a27e-9299b8145922)

**Comment by Diana-Cherry-8** [comment]
Запятую можно убрать в тег категориях (даже если ее ближе поставить оно не очень)
![image](https://github.com/Waiviogit/waivio/assets/67378322/fc0449ef-9cab-4f0b-b1fd-8fc590132487)

**Comment by Diana-Cherry-8** [comment]
Стиль для тегов, в цвет сайта

![image](https://github.com/Waiviogit/waivio/assets/67378322/28b079b7-0222-443a-850d-bac8df816a0f)

**Comment by Diana-Cherry-8** [comment]
Стиль для блока тегов
- название Tags
- добавить бордер под цвет сайта
https://camping.social.gifts/object/product/rjt-missufe-womens-short-sleeve-ruched-casual-sundress-midi-bodycon-t-shirt-dress
![image](https://github.com/Waiviogit/waivio/assets/67378322/a010d5c0-85a4-430c-929d-51d49bb2d3fb)

**Comment by Diana-Cherry-8** [comment]
Нужно добавить хлебные крошки
![image](https://github.com/Waiviogit/waivio/assets/67378322/eec9f2ad-25fa-48de-bacd-315da76118fe)

**Comment by Diana-Cherry-8** [comment]
Между блоками подравнять отступы, везде должен быть одинаковый
![image](https://github.com/Waiviogit/waivio/assets/67378322/17580369-06da-4262-857b-311067203295)

**Comment by Diana-Cherry-8** [comment]
Поправить департаменты на десктопе, они выстраиваются в колонки, а не в строку
![image](https://github.com/Waiviogit/waivio/assets/67378322/0822071e-3b21-400d-975c-1cb200abb5f5)

**Comment by Diana-Cherry-8** [comment]
При обновлении страницы, много запросов летит (в 2 раза больше)
![image](https://github.com/Waiviogit/waivio/assets/67378322/fc87e071-f245-4a99-8a89-f4747a075937)

**Comment by Diana-Cherry-8** [comment]
Имя рейтинга все еще высоко
https://ddd.socialgifts.pp.ua/object/product/kxr-body-kindness---by--rebecca-scritchfield-paperback
![image](https://github.com/Waiviogit/waivio/assets/67378322/ebe1a6ce-664e-4b9c-a7bf-e1a2c558400f)

**Comment by katerynapadafa** [comment]
on mobile option click!

**Comment by katerynapadafa** [comment]
description spaces

**Comment by Diana-Cherry-8** [comment]
Увеличить шрифт для описания на продукте

**Comment by Diana-Cherry-8** [comment]
Similar, Related, Add-on при нажатии на стрелочку нужно чтобы менялся весь ряд, а не одна карточка

**Comment by Diana-Cherry-8** [comment]
Поиск сделать немного заметнее (то ли в цвет сайта, то ли немного серым)
![image](https://github.com/Waiviogit/waivio/assets/67378322/a9878541-c899-4740-a4b3-3df1f15bf275)

**Comment by Diana-Cherry-8** [comment]
Текст о rewards немного уменьшить 
![image](https://github.com/Waiviogit/waivio/assets/67378322/90ca98d4-204c-4288-8fb2-ea83cbeea53f)

**Comment by Diana-Cherry-8** [comment]
Экспертизу на вейвио, оставить в стиле как было
![image](https://github.com/Waiviogit/waivio/assets/67378322/307971c5-a959-4556-9b26-2e9f8adecde9)
![image](https://github.com/Waiviogit/waivio/assets/67378322/a4ce60c0-2903-4b68-8513-20ad6e5cab4c)

**Comment by Diana-Cherry-8** [comment]
1й рейтинг нужно поставить Value
![image](https://github.com/Waiviogit/waivio/assets/67378322/0f6d38ab-c026-4efc-a542-df7a11b185c4)

**Comment by Diana-Cherry-8** [comment]
Цена тоже должна сохранять отступы, пустые строки (как на вейвио)
![image](https://github.com/Waiviogit/waivio/assets/67378322/d94aa660-03f8-4fe6-9624-dd49731cf720)

![image](https://github.com/Waiviogit/waivio/assets/67378322/93206ba4-056d-494d-bf54-7cc67bfb6c60)

**Comment by Diana-Cherry-8** [comment]
Тайтл на мобилке в виде обычного текста

![image](https://github.com/Waiviogit/waivio/assets/67378322/9803000a-c1f5-4f12-a75e-75face96e51a)

**Comment by Diana-Cherry-8** [comment]
На мобилке для тегов, можно добавить побольше отступ между ними
![image](https://github.com/Waiviogit/waivio/assets/67378322/1073bdde-756f-47ab-ba79-f626e1d0ffa8)

**Comment by Diana-Cherry-8** [comment]
Для опшинов на мобилке, можно попробовать как на амазон
- увеличить картинки (в целом раза в два)
- края в виде круга
- все карточки в один ряд (как для related/similar), нужно свапать чтобы посмотреть
- по дефолту при заходе на страницу, оно будет проскраливаться к нужно опции
https://www.amazon.com/dp/B0BY185RD1?th=1&psc=1
![image](https://github.com/Waiviogit/waivio/assets/67378322/97af4e42-fc59-4ab8-8a26-b165a20c1395)


https://github.com/Waiviogit/waivio/assets/67378322/936bed5e-1d3a-48e8-af27-168c11ff1f6a

**Comment by Diana-Cherry-8** [comment]
На стейджине вейвио открывается сошал сайт
![image](https://github.com/Waiviogit/waivio/assets/67378322/23cbc94c-45cb-43b2-b7fc-34ea58bca1c0)

**Comment by Diana-Cherry-8** [comment]
Мобилка. Картинки не по центру в related/similar
![image](https://github.com/Waiviogit/waivio/assets/67378322/ff3e4339-3a4a-46f7-90e9-26ca21605804)

**Comment by Diana-Cherry-8** [comment]
Мобилка. Если много объектов в related (например), то активная точка перестанет показываться
https://ddd.socialgifts.pp.ua/object/product/ueq-charlotte-s-beautiful-skin-foundation
https://github.com/Waiviogit/waivio/assets/67378322/c2ed3574-37fe-4bfc-88f9-940149c1c5c8

**Comment by Diana-Cherry-8** [comment]
При переходе с поиска нужно показывать product / book в новом виде

https://github.com/Waiviogit/waivio/assets/67378322/796fce69-c899-4b1f-b553-30395e90e4e1

**Comment by Diana-Cherry-8** [comment]
Бордер для картинок покрасить в бледный цвет 
![image](https://github.com/Waiviogit/waivio/assets/67378322/6f47c128-0fc9-446a-b818-028a3ecd8a8d)
____
![image](https://github.com/Waiviogit/waivio/assets/67378322/c475dfbc-03c1-4ce6-a5b3-065252590b13)

**Comment by Diana-Cherry-8** [comment]
Добавить кликабельность для большой картинки, чтобы на весь экран открывалось
![image](https://github.com/Waiviogit/waivio/assets/67378322/99ea3027-8d23-4da5-bf2e-c070e1cdda17)

**Comment by Diana-Cherry-8** [comment]
Для блоков related/similar/add-on не нужно в "круговую" повторять объекты, да конца дошли и все, стрелочка пропадает

https://github.com/Waiviogit/waivio/assets/67378322/eeb8604a-8382-406a-b326-f873ae29f253

**Comment by Diana-Cherry-8** [comment]
Текст для рейтингов сделать более ярким, получиться просто черный цвет (сейчас он бледноват)
![image](https://github.com/Waiviogit/waivio/assets/67378322/e6b18946-91c9-49a5-a7d9-921b42f70160)

**Comment by Diana-Cherry-8** [comment]
На ...dining.gifts сайтах primary карточки не отображаються
![image](https://github.com/Waiviogit/waivio/assets/67378322/86b24c36-d27c-4cc5-8e42-943c8272b16d)
![image](https://github.com/Waiviogit/waivio/assets/67378322/0a85a3fe-cd72-4458-9294-481f27f4e933)

**Comment by Diana-Cherry-8** [comment]
В кареселе, по ховер на картинки она должна отображаться на месте большой
![image](https://github.com/Waiviogit/waivio/assets/67378322/68a987f4-1f61-4b74-a849-8c3affccb10b)

**Comment by Diana-Cherry-8** [comment]
При переходе между опциями, скролить вверху нужно до второго меню (с menu items), после баннера
 (при переходе между объектами, там с realted/similar/addOnn тоже чтобы до этого меню скролило вверх)
https://github.com/Waiviogit/waivio/assets/67378322/86e44220-b254-4daf-963f-10d55ec0daf1

**Comment by Diana-Cherry-8** [comment]
В карусели отображается дополнительное пустое место перед правой стрелкой
![image](https://github.com/Waiviogit/waivio/assets/67378322/0222a3e1-40ba-42ea-869b-6f3dce536767)

**Comment by Diana-Cherry-8** [comment]
В каруселе картинки не нужно замыкать, дошли до последней и все
https://wiv.socialgifts.pp.ua/object/product/gsr-la-pavoni-europiccola-chrome-epc-8-espresso-machine

![image](https://github.com/Waiviogit/waivio/assets/67378322/ee47bef0-67e8-4d7c-b9d7-836ca01c904e)

**Comment by Diana-Cherry-8** [comment]
Карусель нужно центрировать по центру относительно большой картинки
https://wiv.socialgifts.pp.ua/object/product/rjt-missufe-womens-short-sleeve-ruched-casual-sundress-midi-bodycon-t-shirt-dress
![image](https://github.com/Waiviogit/waivio/assets/67378322/4cfb5991-7245-4ab1-8c84-130cd003e28a)

**Comment by Diana-Cherry-8** [comment]
Related/Similar/Add-ons если пальцем свапать, то должна свапать только одна карточка, а не весь ряд.
Весь ряд меняется только если нажимать на стрелочки

https://github.com/Waiviogit/waivio/assets/67378322/591e9176-a86d-4eaa-8d76-44633834a5fc

**Comment by Diana-Cherry-8** [comment]
1й меню item показывать в раскрытом виде

**Comment by Diana-Cherry-8** [comment]
Дискрипшен нужно будет перемешивать с картинками с галерее, используя всю ширину, вставлять картинки внутри текста 
![image](https://github.com/Waiviogit/waivio/assets/67378322/3c160768-2cb2-4a92-b319-b89bb2bb8cc5)

**Comment by Diana-Cherry-8** [comment]
Левая стрелочка не кликабельна, ее можно убрать на блоках related/similar/addOnn, при 1м заходе, пока еще не нажималась правая стрелка
https://wiv.socialgifts.pp.ua/object/product/rjt-missufe-womens-short-sleeve-ruched-casual-sundress-midi-bodycon-t-shirt-dress
![image](https://github.com/Waiviogit/waivio/assets/67378322/dfbb53dc-842b-49d8-95a4-15ea2131ebcd)

**Comment by Diana-Cherry-8** [comment]
По нажатию на опшины, скролл идет в самый вверх, а не до 2 меню
   

https://github.com/Waiviogit/waivio/assets/67378322/45a50b73-769f-49ce-ab4f-ef936ab41aff

**Comment by Diana-Cherry-8** [comment]
Для каруселе картинок, тоже убирать стрелочки если они не кликабельные
- левую при 1м заходе
- правую если долистали до конца
![image](https://github.com/Waiviogit/waivio/assets/67378322/1d3678c1-4103-431a-9312-4ea01ec00675)

**Comment by Diana-Cherry-8** [comment]
Иконка в кнопке amazon слишком сдвинулась https://github.com/Waiviogit/waivio/issues/5501
![image](https://github.com/Waiviogit/waivio/assets/67378322/517dcb83-2cf4-4d5f-8fcc-04a0dff83d53)

**Comment by Diana-Cherry-8** [comment]
Mobile.
Кнопки амазона\волмарта\таргета очень маленькие в related/similar/addOn блоках, нужно сделать побольше так как тут места хватает
![image](https://github.com/Waiviogit/waivio/assets/67378322/ecd8591c-f21a-40b2-99ca-b5a6debdf7f6)

**Comment by Diana-Cherry-8** [comment]
Если нажимать на стрелочку, то карточки немного приподнимаются вверх (пока пролистывается ряд), а потом опускаются на место

https://github.com/Waiviogit/waivio/assets/67378322/91155d48-6b0f-458d-88a6-40ce99afe591

**Comment by Diana-Cherry-8** [comment]
Если нажимать на объекты с related/similar/addon блоков, то каждый раз скроллит в разные места, если у сайта есть баннер

https://github.com/Waiviogit/waivio/assets/67378322/62263436-baba-438e-a942-f0dd1162aa5b

**Comment by Diana-Cherry-8** [comment]
Когда долговато отбрабатывает, когда наводишь на опции - ховер и картинка не сразу меняется.
При переходе по опшинам, тоже долго новое подгружается
 

https://github.com/Waiviogit/waivio/assets/67378322/993c09ef-78d6-4f90-b878-1a127b9ee859

**Comment by Diana-Cherry-8** [comment]
Mobile. Для similar/related/addon попробовать показывать две карточки

**Comment by Diana-Cherry-8** [comment]
Для similar/related можно задать конкретное количество в 30 штук (для addOn нет, там как там мы только вручную можем добавлять, то есть нужно все показывать)

**Comment by Diana-Cherry-8** [comment]
Если мало текста в page, то размер все-равно должен быть как обычно
https://wiv.socialgifts.pp.ua/checklist/dvp-test-product-21060940-different-types
![image](https://github.com/Waiviogit/waivio/assets/67378322/48585d19-aa8b-4fba-b4b8-ddb673edf727)

**Comment by Diana-Cherry-8** [comment]
По нажатию на меню айтеми, в хлебные крошки добавляются эти ж элементы

https://github.com/Waiviogit/waivio/assets/67378322/d9f9eda1-18fc-4b51-8038-2d13351c111b

**Comment by Diana-Cherry-8** [comment]
Если меню айтем это ссылка на продукт, то типа рекурсии получается, вместо перехода по ссылке, тот же объект открывается заново
 https://wiv.socialgifts.pp.ua/checklist/dvp-test-product-21060940-different-types

https://github.com/Waiviogit/waivio/assets/67378322/45e82e1f-5f86-4ab6-923c-3a1c02415f8d

**Comment by Diana-Cherry-8** [comment]
Скрывать плюсик если эта ссылка на другие страницы
То есть по клику на плюсик все-равно внутри ничего не откроется, а перебросит сразу на другую страницу, поэтому можно скрыть плюсик
https://waiviodev.com/object/viv-matein-pink-travel-backpack-for-women-large-travel-backpack-airline-approved-expandable-carry-on-backpacks-35l-convertible-suitcase-weekender-back-pack-for-hiking-sport-gym-gift-for-traveler

https://wiv.socialgifts.pp.ua/checklist/mor-test-list-not-bad-advice#viv-matein-pink-travel-backpack-for-women-large-travel-backpack-airline-approved-expandable-carry-on-backpacks-35l-convertible-suitcase-weekender-back-pack-for-hiking-sport-gym-gift-for-traveler


![image](https://github.com/Waiviogit/waivio/assets/67378322/37470411-b2be-40a0-8ec8-f2ff25c9a53f)

**Comment by Diana-Cherry-8** [comment]
Нужно будет добавить блок с действиями (включая сердечко)
![image](https://github.com/Waiviogit/waivio/assets/67378322/ae645795-207e-401e-abfa-893cfc500c52)

**Comment by Diana-Cherry-8** [comment]
Если menu item это external link, то открывается undefined страница, и плюсик отображается https://wiv.socialgifts.pp.ua/checklist/mor-test-list-not-bad-advice#viv-matein-pink-travel-backpack-for-women-large-travel-backpack-airline-approved-expandable-carry-on-backpacks-35l-convertible-suitcase-weekender-back-pack-for-hiking-sport-gym-gift-for-traveler



https://github.com/Waiviogit/waivio/assets/67378322/ca38e76d-752d-4e58-b8db-aa676b08054d

**Comment by Diana-Cherry-8** [comment]
Мы на вейвио сделали чтобы картинки в лайтбоксе замыкались, на сайтах тоже это можно добавить
https://wiv.socialgifts.pp.ua/object/product/rjt-missufe-womens-short-sleeve-ruched-casual-sundress-midi-bodycon-t-shirt-dress

https://github.com/Waiviogit/waivio/assets/67378322/e2904ac5-149f-4f87-95b2-7561afc2a306

**Comment by Diana-Cherry-8** [comment]
Последняя картинка которая была пролистана в лайтбоксе, запоминается, если еще раз нажать на аватар


https://github.com/Waiviogit/waivio/assets/67378322/03b63e2e-9c21-493f-b963-1b6963835266

**Comment by Diana-Cherry-8** [comment]
Rewards block:
- если закрыть модалку требований, то кнопка submit заблокирована и с лоадером

https://github.com/Waiviogit/waivio/assets/67378322/ceb7607a-375a-4722-a06a-9e5e3dccbbe4

**Comment by Diana-Cherry-8** [comment]
Rewards block:
- пункт без количества дней в меню три точки
![image](https://github.com/Waiviogit/waivio/assets/67378322/4cd3a209-a7a1-4973-8358-ea0a4099a95c)

![image](https://github.com/Waiviogit/waivio/assets/67378322/2faf22f9-b722-4ea8-95bc-08b7b2005f0b)

**Comment by Diana-Cherry-8** [comment]
Сделать цвет для линий немного бледнее, длдя menu айтемов (оно так вроде аккуратней смотрится)
https://wiv2.socialgifts.pp.ua/object/product/dvp-test-product-21060940-different-types

![image](https://github.com/Waiviogit/waivio/assets/67378322/37a77fa9-3bf3-48cd-9298-fdb9b4a1b101)
(примерный вариант)
![image](https://github.com/Waiviogit/waivio/assets/67378322/fc03898b-9631-4c7d-b43a-bd82fc981cdf)

**Comment by Diana-Cherry-8** [comment]
Покрасить плюсики в главный цвет сайта (вроде неплохо выглядит)
![image](https://github.com/Waiviogit/waivio/assets/67378322/8c4a938c-0c8a-4b98-a4f6-c8c721c122f4)

**Comment by Diana-Cherry-8** [comment]
Если не авторизоваться, то много пустого место между названием и рейтингами
![image](https://github.com/Waiviogit/waivio/assets/67378322/07f15cfa-7331-4a4e-a3f6-9ede5c45caa3)

**Comment by Diana-Cherry-8** [comment]
Можно убрать красный ховер для колокольчика, чтобы было как для сердечка (для вейвио тоже)
И добавить всплывашку с текстом - Receive object news - (как у сердечка)


https://github.com/Waiviogit/waivio/assets/67378322/05c71f86-d90f-4a38-8961-b797b11b9bd5

**Comment by Diana-Cherry-8** [comment]
Пункт "Reserve the rewards for" стал открываться в правую строну, а не в левую

![image](https://github.com/Waiviogit/waivio/assets/67378322/c8f5137f-2def-4bc6-a388-138caa1e7d35)


![image](https://github.com/Waiviogit/waivio/assets/67378322/938958cd-651b-4e3b-b11d-29063b1ba362)

**Comment by Diana-Cherry-8** [comment]
Если открыть меню айтем лист, а потом другой, то в там где был лист будет надпись, что список пустой


https://github.com/Waiviogit/waivio/assets/67378322/9936b408-8096-401d-b940-85a2f1d166dd

**Comment by Diana-Cherry-8** [comment]
С подсказки колокольчика можно убрать слово object, будет просто Receive news
![image](https://github.com/Waiviogit/waivio/assets/67378322/f316261e-9560-41ed-ae4f-d28cb692c2d4)

**Comment by Diana-Cherry-8** [comment]
На вейвио посты есть, на сайтах нет
https://waiviodev.com/object/hcr-hario-v60-drip-coffee-scale-and-timer
https://wiv.socialgifts.pp.ua/checklist/mor-test-list-not-bad-advice#bev-test-list-not-bad-advice-2/hcr-hario-v60-drip-coffee-scale-and-timer

![image](https://github.com/Waiviogit/waivio/assets/67378322/eb2e7259-29d1-4fa1-8831-f659957cdb97)

**Comment by Diana-Cherry-8** [comment]
При загрузки страницы, она загружается как бы битая (User review), может повесить лоадер чтобы крутился
(на проде сейчас такого нет)

https://github.com/Waiviogit/waivio/assets/67378322/66581fe1-7947-4f22-8c7c-b975eb868a64

**Comment by Diana-Cherry-8** [comment]
Mobile
Добавить свап картинок для большой картинки
(тут порядок должен быть одинаковым, как картинки внизу показываються, так и при свайпе картинок) 

![image](https://github.com/Waiviogit/waivio/assets/67378322/6fe15728-ee34-465b-9795-4a8f4372a1c5)

**Comment by Diana-Cherry-8** [comment]
Текст кнопки Follow нужно под 2й цвет сайта, сейчас он получается всегда черный
![image](https://github.com/Waiviogit/waivio/assets/67378322/f2bdcafd-d9cb-4cd0-b556-860e7e4a1454)
![image](https://github.com/Waiviogit/waivio/assets/67378322/32cab08c-b3b5-412f-be13-94d09a25656c)

**Comment by Diana-Cherry-8** [comment]
У объекта аватар от parent не подтягивается на странице объекта
https://wiv.socialgifts.pp.ua/checklist/mor-test-list-not-bad-advice

![image](https://github.com/Waiviogit/waivio/assets/67378322/948cd879-cd7e-4fc7-a372-9c961bee3d64)
![image](https://github.com/Waiviogit/waivio/assets/67378322/93e4999d-5e24-4379-b05e-70547dcf4355)

**Comment by Diana-Cherry-8** [comment]
В целом для объектов без картинки, тоже можно оставить дефолтную вейвио картинку
https://wiv.socialgifts.pp.ua/checklist/mor-test-list-not-bad-advice

![image](https://github.com/Waiviogit/waivio/assets/67378322/93699536-a648-40c7-8cf0-8bc5346cc6b6)
![image](https://github.com/Waiviogit/waivio/assets/67378322/9ab877aa-4231-4d86-8b65-c83a22957cae)

**Comment by Diana-Cherry-8** [comment]
https://github.com/Waiviogit/waivio/issues/5595

**Comment by Diana-Cherry-8** [comment]
Для book на новой странице нет полей:
- author (наверно нужно куда-то вверх к тайтлу)
- publisher
- reading age
- language
- publication date
- print length

![image](https://github.com/Waiviogit/waivio/assets/67378322/7dc15f67-4bfa-45f1-8413-208fcd31b369)
![image](https://github.com/Waiviogit/waivio/assets/67378322/a1c5759c-634b-4d27-ae11-e299d58a80e5)

**Comment by Diana-Cherry-8** [comment]
Если фида пустая, то текст "Be the first to write a review" это та же линка что и Write review. Чтобы можно было нажать и оно перекидовала в едитор 
![image](https://github.com/Waiviogit/waivio/assets/67378322/8aeab754-d6b7-4f58-a044-c7950bb77f9e)

**Comment by Diana-Cherry-8** [comment]
Если перейти на объект Clean Girl Aesthetics, то там имя Shop и parent - Clean Girl Aesthetics, хотя на объекте на вейвио такого нет

https://wiv.socialgifts.pp.ua/checklist/mor-test-list-not-bad-advice
https://wiv.socialgifts.pp.ua/checklist/mor-test-list-not-bad-advice#tlc-clean-girl-aesthetics
https://waiviodev.com/object/tlc-clean-girl-aesthetics/reviews

https://github.com/Waiviogit/waivio/assets/67378322/5b22688c-7536-4269-90b8-341835cddc66

**Comment by Diana-Cherry-8** [comment]
На десктопе, если нажимать на стрелочки, главная картинка будет меняться
https://wiv.socialgifts.pp.ua/checklist/mor-test-list-not-bad-advice#jhf-test-product-23051329


https://github.com/Waiviogit/waivio/assets/67378322/49a70e89-3f5c-45ff-b1a7-c865844b90be

**Comment by Diana-Cherry-8** [comment]
Картинки в описании можно сделать кликабельными, что в лайтбоксе открывались, как на вейвио
![image](https://github.com/Waiviogit/waivio/assets/67378322/a59d30c8-3675-4aa4-9070-43064e542040)

**Comment by Diana-Cherry-8** [comment]
Главная картинка остается с предыдущего объекта, если 
Открыть объект -> нажать на его опцию -> нажать на объект в similar/related -> главная картинка от объекта опций

https://github.com/Waiviogit/waivio/assets/67378322/62f3d696-491c-4a4f-8b68-6d328525432e

**Comment by Diana-Cherry-8** [comment]
Может попробовать отцентровать текст относительно картинки. 
![image](https://github.com/Waiviogit/waivio/assets/67378322/7babcb77-9da4-4927-8893-c547eaa0adf0)
![image](https://github.com/Waiviogit/waivio/assets/67378322/876e9e8c-8a9e-495e-bb7d-5b5022bdc86c)

**Comment by Diana-Cherry-8** [comment]
Картинка добавленная в галерею, отображается как аватар на сайте, у объекта у которого аватар от parent тянется
https://wiv.socialgifts.pp.ua/object/product/iky-test-product-12071502
https://waiviodev.com/object/iky-test-product-12071502/description

![image](https://github.com/Waiviogit/waivio/assets/67378322/6f982a05-c25f-49a8-84ae-72e249b39d90)
![image](https://github.com/Waiviogit/waivio/assets/67378322/52c8e8bc-7229-443c-b644-b9a91fb852ae)

**Comment by Diana-Cherry-8** [comment]
Если menu item это тип объекта shop, то объект открывается как продукт, нужно чтобы открывался как новый вид шопа shop 
(и иконку минус показывать не нужно, как будто оно раскрыто)
https://wiv.socialgifts.pp.ua/checklist/mor-test-list-not-bad-advice#jhf-test-product-23051329

![image](https://github.com/Waiviogit/waivio/assets/67378322/5683451b-9958-4156-bce6-5e24b7c882b4)
![image](https://github.com/Waiviogit/waivio/assets/67378322/01ec1642-dd4f-4759-8f77-f9a2a7c0f785)

![image](https://github.com/Waiviogit/waivio/assets/67378322/1d43bdf7-0c32-4a60-ab47-0badb07eed5c)

**Comment by Diana-Cherry-8** [comment]
Fix style для write review на мобилке, предложение:
- сделать в lowercase
- убрать жирность
- убрать отступ справа, чтобы расстояние по боком было одинаковое

![image](https://github.com/Waiviogit/waivio/assets/67378322/f3141f12-5c19-4bc8-b42b-58084418bb68)

![image](https://github.com/Waiviogit/waivio/assets/67378322/c5e8107b-c05f-4fb5-bfbe-6ef1add0ca51)

**Comment by Diana-Cherry-8** [comment]
Стрелочки пропадают и появляются если нажимать на картинки в кареселе
https://wiv.socialgifts.pp.ua/checklist/mor-test-list-not-bad-advice#ysd-test-product-26041256

https://github.com/Waiviogit/waivio/assets/67378322/5a2b9116-e2fe-423c-88bc-9a041c0d7baf

**Comment by Diana-Cherry-8** [comment]
Имя автора далековато от By, нужно нменого ближе подвинуть, чтобы было как обычный текст

![image](https://github.com/Waiviogit/waivio/assets/67378322/9be86bae-27a1-4a4b-9c5a-f6ecf030473f)

**Comment by Diana-Cherry-8** [comment]
Картинки предыдущего объекта могут повторяться если переходить по опциям
https://wiv.socialgifts.pp.ua/object/product/rjt-missufe-womens-short-sleeve-ruched-casual-sundress-midi-bodycon-t-shirt-dress

https://github.com/Waiviogit/waivio/assets/67378322/56e6b657-c59a-42f0-940d-fc6ded3aba48

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
