### ISSUE TITLE
Write a request to check the user in order to see if the user in whitelist for adding update or no

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#5147]
**Front-task** #5146 

Поскольку мы будем менять  голос пользователя при добавления апдейтов в модалке, и будет только waiv учитываться.
То нужна проверка пользователя, чтобы пользователи которые в whitelist для добавления апдейтов могли добавлять апдейты с голосом меньше чем 0.001

**Comment by Waiviogit** [comment]
https://waiviodev.com/api/docs/#/user/get_api_user__userName__waiv_vote

https://waiviodev.com/api/docs/#/user/get_api_user__userName__white_list_object
