### ISSUE TITLE
[product / similar] Expanding Show more on similar, related and add-on should be done in the middle column so that you can see additional information about these products. Also, the "Show more" link should always be shown in the module (even if there are less than 5 objects).

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#5206]
yammer 2181
product / similar

Expanding Show more on similar, related and add-on should be done in the middle column so that you can see additional information about these products. Also, the "Show more" link should always be shown in the module (even if there are less than 5 objects).
https://www.waivio.com/object/vef-dash-drcm200gbaq04-mini-rice-cooker-with-keep-warm-2-cup-aqua

![image](https://cdn.discordapp.com/attachments/537744716066848819/1095768897275314196/image.png)

**Comment by Diana-Cherry-8** [comment]
Кнопка Show more должна отображаться всегда (даже если объектов меньше 5)
![image](https://user-images.githubusercontent.com/67378322/232719704-4a92dbb6-d714-4366-9f5c-457d478d1275.png)

**Comment by Diana-Cherry-8** [comment]
Сортировка не совпадает. Последний добавленный объект должен быть самым нижним. 
Not bad advice отображается самым 1м если Show more список открыть. И не самым последним в самой колонке
https://waiviodev.com/object/nbe-test-product-18041035/similar
![image](https://user-images.githubusercontent.com/67378322/232721074-6b1de6aa-ef52-42c8-9163-9d49bd4a6f9f.png)

**Comment by Diana-Cherry-8** [comment]
В целом порядок должен быть одинаковым в колонке, и в полном списке
![image](https://user-images.githubusercontent.com/67378322/232721879-63947849-8f63-4c49-ac41-3cf7e039113c.png)

**Comment by Diana-Cherry-8** [comment]
Нельзя поставить сердечко с полного списка, падает запрос
message: "\"parentAuthor\" is required"
![image](https://user-images.githubusercontent.com/67378322/232722235-cd71da2c-4f95-4c75-b961-7d0ece8ee4fd.png)

**Comment by Diana-Cherry-8** [comment]
Mobile. About вкладка
Experts нужно упустить в самый низ (чтобы порядок был как на десктопе)
![image](https://user-images.githubusercontent.com/67378322/232727394-475771d9-918f-4550-858d-22688ad62166.png)

**Comment by Diana-Cherry-8** [comment]
Mobile. About вкладка
Тайтлы колонок, это все равно что show more ссылка на десктопе, нужно открыть тоже полный список (возможно как на департаментах, похожим образом)
![image](https://user-images.githubusercontent.com/67378322/232728121-31aed059-4a5b-49ad-8a10-34caa76c7375.png)

**Comment by Diana-Cherry-8** [comment]
для объект "child" был добавлен "parent", у "parent" на странице, в колонке Related отображается один объект два раза
https://waiviodev.com/object/nbe-test-product-18041035/similar (parent)
https://waiviodev.com/object/gti-test-product-12041457 (child)

![image](https://user-images.githubusercontent.com/67378322/232745152-1c0be402-0ff9-4d1d-a68a-c0542d3ddd31.png)

**Comment by katerynapadafa** [comment]
> для объект "child" был добавлен "parent", у "parent" на странице, в колонке Related отображается один объект два раза https://waiviodev.com/object/nbe-test-product-18041035 (parent) https://waiviodev.com/object/gti-test-product-12041457 (child)
> 
> ![image](https://user-images.githubusercontent.com/67378322/232745152-1c0be402-0ff9-4d1d-a68a-c0542d3ddd31.png)

**Comment by katerynapadafa** [comment]
добавить в запрос parent permlinks, если нет добавленных related objects

**Comment by Diana-Cherry-8** [comment]
При возвращении назад на related, объекты, которые были добавлены не как апдейты, а как child для объекта, не отображаются в полном списке
https://waiviodev.com/object/nbe-test-product-18041035
https://user-images.githubusercontent.com/67378322/233064752-d1b2b667-de21-460a-a962-425365987698.mp4

**Comment by Diana-Cherry-8** [comment]
После добавления нового related пункты в блоке (child) также могут дублироваться

https://user-images.githubusercontent.com/67378322/233066244-2ee7e3d5-34d6-42fd-9155-488894cfcbf2.mp4

**Comment by Diana-Cherry-8** [comment]
На мобилке, во вкладке About, в Related, не отображаются объекты которые childы
Если перейти на другую вкладку, потом нажать на About еще раз
https://waiviodev.com/object/nbe-test-product-18041035/about

https://user-images.githubusercontent.com/67378322/233099123-3fd38509-4cf8-428a-9fbd-10f382644164.mp4

**Comment by Diana-Cherry-8** [comment]
При обновлении страницы на Related, если там childы, не будут отображаться в средней фиде

https://user-images.githubusercontent.com/67378322/233308151-cba7f4d4-06f7-4b49-9eae-80235c467ba5.mp4

**Comment by Diana-Cherry-8** [comment]
Мобилка. Если нажать на Related в About, то список будет без child объектов
https://waiviodev.com/object/nbe-test-product-18041035/about
![image](https://user-images.githubusercontent.com/67378322/233309257-1ed32884-6542-4b2e-a589-98c4136e9031.png)
![image](https://user-images.githubusercontent.com/67378322/233309322-ea6325b3-71e9-48c2-aee3-155941a2746e.png)

**Comment by Diana-Cherry-8** [comment]
Запрос wobject летит два раза, если нажать на Show more
https://waiviodev.com/object/mfr-test-product-20021029/related
![image](https://user-images.githubusercontent.com/67378322/233592527-3cca4d9b-6e80-458a-975b-7b41a62f7d90.png)

**Comment by Diana-Cherry-8** [comment]
> При обновлении страницы на Related, если там childы, не будут отображаться в средней фиде https://waiviodev.com/object/mfr-test-product-20021029
> 
>  vokoscreenNG-2023-04-20_11-30-42.mp4

Воспроизводиться

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
После добавлений объекта в Related, 1й (который child) задублировался
https://waiviodev.com/object/mfr-test-product-20021029/updates/related

https://waiviodev.com/object/mfr-test-product-20021029/updates/related

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
