### ISSUE TITLE
[data import / large file] an error occurs when uploading a file (35Mb)

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#5228]
yammer 2194
data import / large file

an error occurs when uploading a file (35Mb)
https://drive.google.com/file/d/1qBKruyCM_xPMTwbTGc7h1kRsIRKxt4Op/view?usp=sharing

![image](https://cdn.discordapp.com/attachments/537744716066848819/1097608537703723118/image.png)

**Comment by Waiviogit** [comment]
max size 50 mb

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
