### ISSUE TITLE
[data import / duplicates] there are many duplicates of the same book. This may have happened before updates were debugged. It is necessary to check once again, including the fact that the Group ID is correctly written for books.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#5300]
yammer 2207
data import / duplicates

there are many duplicates of the same book. This may have happened before updates were debugged. It is necessary to check once again, including the fact that the Group ID is correctly written for books.
https://www.waivio.com/discover-objects/book?search=Born%20a%20Crime

![image](https://cdn.discordapp.com/attachments/537744716066848819/1103412801072005181/image.png)

**Comment by Waiviogit** [comment]
all 6 has different product id

igg-born-a-crime-stories-from-a-south-african-childhood
B01DHWACVY

mwe-born-a-crime
1531865046

opn-born-a-crime-stories-from-a-south-african-childhood
1473635284

phd-born-a-crime-stories-from-a-south-african-childhood
9780399588198

log-born-a-crime-stories-from-a-south-african-childhood
B01IW9TM5O

rlh-born-a-crime-stories-from-a-south-african-childhood
9780399588174

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
