### ISSUE TITLE
Add Edit button for administrators and site owner to new product page

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#5578]
**Back-task** #5577 

Edit will be redirected to Waivio object page in edit mode

**Comment by Waiviogit** [comment]
![image](https://github.com/Waiviogit/waivio/assets/44571359/854ff186-161a-41d7-906e-7ef165690ef8)
added to site config

**Comment by Diana-Cherry-8** [comment]
Продукт не добавляеться в хлебные крошки, если это прям на 1м листе переход
https://wiv.socialgifts.pp.ua/checklist/mor-test-list-not-bad-advice

https://github.com/Waiviogit/waivio/assets/67378322/8f050194-691f-43dd-8e6d-d334db77ca95

**Comment by Diana-Cherry-8** [comment]
**Production checked**
