### ISSUE TITLE
[wallet / balances] on many transactions there is a significant delay in updating the user's balances. In this example, Power Up happened 50 seconds ago, but even after several page reloads, the balance is still showing the old one.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#5677]
yammer 2287
wallet / balances

on many transactions there is a significant delay in updating the user's balances. In this example, Power Up happened 50 seconds ago, but even after several page reloads, the balance is still showing the old one.

![image](https://cdn.discordapp.com/attachments/537744716066848819/1136005245726621777/image.png)

**Comment by Fesmofet** [comment]
response goes from Hive node history api

**Comment by Diana-Cherry-8** [comment]
**DONE**
