### ISSUE TITLE
[social.gifts / settings] allow website owners to restrict object edits by users

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#5735]
**Back-task** #5734 

yammer 3207
social.gifts / settings

allow website owners to restrict object edits by users
https://github.com/Waiviogit/waivio/issues/5728

**Comment by Fesmofet** [comment]
on settings add to request objectControl : boolean

**Comment by Diana-Cherry-8** [comment]
Добавить ":" в название блока
![image](https://github.com/Waiviogit/waivio/assets/67378322/e76c0db4-9e17-4cfb-86dc-dd45884276ff)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Prodcution checked**
