### ISSUE TITLE
[social.gifts / affiliate codes] on the TOOLS / Personal page allow editing personal affiliate codes

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#5770]
**Back-task** #5777 

yammer 3212
social.gifts / affiliate codes

on the TOOLS / Personal page allow editing personal affiliate codes

![image](https://cdn.discordapp.com/attachments/537744716066848819/1140044691077873735/image.png)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**

**Comment by Waiviogit** [comment]
https://waiviodev.com/api/docs/#/wobject/post_api_wobjects_search_default

its site -independent search and complete clone of https://waiviodev.com/api/docs/#/wobject/post_api_wobjectSearch

**Comment by Diana-Cherry-8** [comment]
Аффилиат объекты не находятся на сайтах (выше дока от бека)

![image](https://github.com/Waiviogit/waivio/assets/67378322/37f34abe-9e65-498f-8d0d-c55d899d92a1)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
