### ISSUE TITLE
[social.gifts / adsense] Add a new tab to the site configuration: AdSense ads

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#5802]
**Back-task** #5801 

yammer 3223
social.gifts / adsense

Add a new tab to the site configuration: AdSense ads
#5800 

_____
В дальнейшем код, который вставит user, нужно будет добавить в <head> для всех страниц сайта, где будем показывать рекламу.

To get your site ready to show ads, copy and paste this code between the `<head></head>` tags on each page of your site. [Learn more about the AdSense code](https://support.google.com/adsense/answer/9274634?hl=en_US)

**Comment by Waiviogit** [comment]
get adsense config 
https://waiviodev.com/api/docs/#/sites/get_api_sites_ad_sense

set code and lvl: 
broadcast custom_json:


`
{
    id: 'website_adsense',
    json: {
         code: string,
         level: string, // enum : minimal, moderate, intensive
         host: string,
    },
    required_posting_auths: [string],
}
`

**Comment by Diana-Cherry-8** [comment]
Add placeholder для level поля: Select level
![image](https://github.com/Waiviogit/waivio/assets/67378322/65b7a231-705c-4122-86af-bff42525bbbe)

**Comment by Diana-Cherry-8** [comment]
Если заполнить код, но левел пустой, то кнопка save станет активной 
![image](https://github.com/Waiviogit/waivio/assets/67378322/64f78f0d-cf2c-45d1-8c2d-f1e453008ddb)

**Comment by Diana-Cherry-8** [comment]
Fix text, добавить `<head></head>` в текст под полем:

![image](https://github.com/Waiviogit/waivio/assets/67378322/f2c679fd-a81e-4b7a-82be-05f5cb96f719)
![image](https://github.com/Waiviogit/waivio/assets/67378322/b15389d2-038e-4dd0-9980-aa3ca11b158d)

**Comment by Diana-Cherry-8** [comment]
Нельзя убрать Adsense code. Нужно возможность, чтобы если убрать код и сохранить, чтобы не показывать код. 
Как бы что был код, теперь его хотят отключить, то убирают и сохраняют 
![image](https://github.com/Waiviogit/waivio/assets/67378322/462fde65-a193-412f-ab51-25a69289d8e4)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Нужно добавить валидацию, чтобы проверять что это скрипт именно для гугл-аналитике, чтобы нельзя было добавить что-то другое.
Можно ошибку под полем по нажатию на кнопку Save - Invalid AdSense code entered. Please provide a valid script.

Пример валидного скрипта
```
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4624906456940175"
     crossorigin="anonymous"></script>
```

**Comment by Diana-Cherry-8** [comment]
**Production checked**
