### ISSUE TITLE
Approve/reject continue to display after the user removes it.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#5815]
**Severity:** Minor

**Step to reproduce:**
1. Log in
2. Add update to an object
3. Click on approve one more time (to cancel approve)

**Expected result:** Approve/reject are not displaying after user click on them one more time.
**Actual result:** Approve/reject continue to display after the user removes it.

https://github.com/Waiviogit/waivio/assets/67378322/2ec7f499-35df-46bc-8a28-4453620bc975

**Comment by burhanharoon** [comment]
Hy @Diana-Cherry-8, I'm really interested in working on this issue. Could I be assigned to this? Looking forward to contributing!

**Comment by Diana-Cherry-8** [comment]
> Hy @Diana-Cherry-8, I'm really interested in working on this issue. Could I be assigned to this? Looking forward to contributing!

Thank you so much for expressing interest in contributing to our project! We truly value and appreciate your enthusiasm.

Regarding the specific issue you've mentioned, I regret to inform you that it requires access to some private components of our project. Due to the nature of these components, we're unable to grant access at this time.

However, there are many other areas of our project where your contributions would be most welcome. Please feel free to explore other open issues or let us know if you have any other questions or ideas. We look forward to your participation in other aspects of our project.

Thanks again for reaching out and for your understanding.

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
