### ISSUE TITLE
[*.social.gifts / domains] If you enter a domain with the prefix "www.", an error occurs.  Without the prefix everything works correctly.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6034]
yammer 3275
*.social.gifts / domains

If you enter a domain with the prefix "www.", an error occurs.  Without the prefix everything works correctly.
https://www.coffeeshop.gifts/

![image](https://cdn.discordapp.com/attachments/537744716066848819/1162919713895100587/image.png?ex=653db061&is=652b3b61&hm=69232e6b512f41ad7eec210272914d670d964027e33a032dc957747c927c7988&)

**Comment by Waiviogit** [comment]
add page with redirect instructions
https://developers.cloudflare.com/pages/how-to/www-redirect/

**Comment by Diana-Cherry-8** [comment]
https://www.waivio.com/object/ckq-ensuring-smooth-redirects-manual-www-to-apex-domain-setup-on-cloudflare/page
