### ISSUE TITLE
[custom domain / https] When you go to the website coffeeshop.gifts, http://… (unsecure) opens.  If you type https:// by hand, then everything works correctly.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6035]
yammer 3276
custom domain / https

When you go to the website coffeeshop.gifts, http://… (unsecure) opens.  If you type https:// by hand, then everything works correctly.

![image](https://cdn.discordapp.com/attachments/537744716066848819/1163559581839003668/IMG_5126.png?ex=6540044e&is=652d8f4e&hm=7a5d45c4f0b71e23c070555e9e89ef13ab6bc098c9e06b204bac9d163dc0b065&)

![image](https://cdn.discordapp.com/attachments/537744716066848819/1163559582208106547/IMG_5127.png?ex=6540044e&is=652d8f4e&hm=17a2ed7d157086f541f4b9473198c9d86f0b488183f5f24fa7ef34323cd5262d&)

**Comment by Waiviogit** [comment]
add page with https instructions
![Безымянный](https://github.com/Waiviogit/waivio/assets/44571359/521f603a-693c-4675-9f50-e31618a9801a)
![Screenshot_1](https://github.com/Waiviogit/waivio/assets/44571359/1026b4f3-424a-41d0-b3cd-ccccea525e54)
![Screenshot_10](https://github.com/Waiviogit/waivio/assets/44571359/b1859002-e8fa-4cf0-be21-01b0fff33606)

**Comment by Diana-Cherry-8** [comment]
https://www.waivio.com/object/pvs-ensuring-secure-connections-manual-https-configuration-for-custom-domain-on-cloudflare/page
