### ISSUE TITLE
[profile / threads] the idea to add Threads not only to objects, but also to user profiles. By launching a new Thread, you can publicly communicate with this user. The new Thread must contain the name of the user to whom the question is addresse

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6048]
**Back-task** #6047 

yammer 3352
profile / threads 

the idea to add Threads not only to objects, but also to user profiles.  By launching a new Thread, you can publicly communicate with this user.  The new Thread must contain the name of the user to whom the question is addressed.
![image](https://github.com/Waiviogit/waivio/assets/67378322/1f13962b-b109-4f22-ac41-3654c871fe61)

**Comment by Diana-Cherry-8** [comment]
Можно чтобы placeholder показывал 
{object name} ... 

![image](https://github.com/Waiviogit/waivio/assets/67378322/70786105-d8f5-4284-ac63-36a4f52c6f1d)

**Comment by Diana-Cherry-8** [comment]
Fix placeholder чтобы был вместо "Write your thread..."
@{username} ...
@wiv01 ...
![image](https://github.com/Waiviogit/waivio/assets/67378322/1237ab63-5400-4a73-a38e-2f0a81d3147b)
![image](https://github.com/Waiviogit/waivio/assets/67378322/d7d03258-f183-44a1-858e-a0caefd5d35d)

**Comment by Diana-Cherry-8** [comment]
Добавить пробел после имени, когда оно автоматически добавляется если поставить курсор


https://github.com/Waiviogit/waivio/assets/67378322/a93fde71-4165-4c74-9b71-c363f603383a

**Comment by Diana-Cherry-8** [comment]
Posts 1го меню не подсвечивается оранжевым если открыта Threads вкладка
![image](https://github.com/Waiviogit/waivio/assets/67378322/b6f30922-963a-406d-be59-49d90e5ed45d)

**Comment by Diana-Cherry-8** [comment]
После публикации thread он не отображается в фиде, с бека приходит (wiv01 опубликовал thread для new-way)
https://waiviodev.com/@new-way/threads

![image](https://github.com/Waiviogit/waivio/assets/67378322/f8b4bef2-b108-474f-b167-b021555c4e72)
![image](https://github.com/Waiviogit/waivio/assets/67378322/6cf81e5b-2fe4-40f9-898c-6db27a57ef47)

**Comment by Diana-Cherry-8** [comment]
Меню не видно, если нажать на кнопку плюса
![image](https://github.com/Waiviogit/waivio/assets/67378322/738b032a-4acf-4abc-bc05-57f5e7df6781)

**Comment by Diana-Cherry-8** [comment]
Решетка не открывает поиск, чтобы найти объект


https://github.com/Waiviogit/waivio/assets/67378322/3044cf26-8901-49b6-901a-7cdb40fa96b7

**Comment by Diana-Cherry-8** [comment]
Поле для вставки ссылки не видно полностью

![image](https://github.com/Waiviogit/waivio/assets/67378322/4b061bff-14c5-4cce-9635-a9139deb008e)

![image](https://github.com/Waiviogit/waivio/assets/67378322/e2d75c70-ed8c-4687-a6a5-3e27a46ea89c)

**Comment by Diana-Cherry-8** [comment]
Если пользователь не залогинен, то можно не показывать поле для текста
![image](https://github.com/Waiviogit/waivio/assets/67378322/bd89f5be-64aa-4681-b3ea-b4eb8b980b98)

**Comment by Diana-Cherry-8** [comment]
Если поставить лайк, то лоадер будет долго крутиться, наверно нужно добавить технологию "quick like", как на постах или комментариях
like-post c 500 

https://github.com/Waiviogit/waivio/assets/67378322/52104136-a919-4e85-8e42-fc5a57aafcee

**Comment by Diana-Cherry-8** [comment]
Промежуточным экраном мигает сообщение "Be first...", может лоадер поставить, если публиковать тред или заходить на вкладку

https://github.com/Waiviogit/waivio/assets/67378322/14b651a5-651c-475e-9b1c-fb70717e227d

**Comment by Diana-Cherry-8** [comment]
Может добавить лоадер и на кнопку для отправки сообщения, чтобы пока сообщение не появится в фиде то крутиться его, например как при написании комментария


https://github.com/Waiviogit/waivio/assets/67378322/ffc2d066-3a92-4047-bd67-62cdc848e7ae

**Comment by Diana-Cherry-8** [comment]
Треды на сайтах не отображается
![image](https://github.com/Waiviogit/waivio/assets/67378322/f191869c-39b8-4488-b04f-3cd8379be3dd)

**Comment by Diana-Cherry-8** [comment]
Если авторизоваться new-way, то будет invalid date во всплывашки вознаграждений

https://waiviodev.com/@new-way/threads

![image](https://github.com/Waiviogit/waivio/assets/67378322/8ed12abd-c427-453b-aef7-7d2d044fb745)

**Comment by Diana-Cherry-8** [comment]
Нужно добавить share to facebook, share to X переходы


https://github.com/Waiviogit/waivio/assets/67378322/4f914de0-0ebd-4a8d-be13-171152c8ff54

**Comment by Diana-Cherry-8** [comment]
Если нажать на вкладку Posts, то запрос для leothreads также отправляется 


https://github.com/Waiviogit/waivio/assets/67378322/f64967b2-9576-4229-b444-85132ebd932c

**Comment by Diana-Cherry-8** [comment]
Приставка Waivio возле времени публикации, есть не всегда
https://waiviodev.com/@new-way/threads

![image](https://github.com/Waiviogit/waivio/assets/67378322/bb879359-3a75-46df-9128-5cba3c032a1e)

**Comment by Diana-Cherry-8** [comment]
Добавить валидацию, чтобы нельзя было отправить без @{username}


https://github.com/Waiviogit/waivio/assets/67378322/0103c3e1-4be2-46e6-b54a-ade19e707a98

**Comment by Diana-Cherry-8** [comment]
Добавить фильтрацию для удаленных тредов, чтобы не показывать их в фиде
![image](https://github.com/Waiviogit/waivio/assets/67378322/2f2840b6-a9b2-48c3-95aa-2577335bcb55)

**Comment by Diana-Cherry-8** [comment]
Сразу после публикации треда, там будет payout declined, но после обновления все нормально

https://github.com/Waiviogit/waivio/assets/67378322/a97476d2-4b61-4306-9767-d95b47c88b1f

**Comment by Diana-Cherry-8** [comment]
Может еще можно сделать публикацию треда более "гладкой"
Сейчас нажал отправить, крутиться лоадер, запрос отправился, а потом leothreads, user запросы и тут начинается крутиться лоадер фиды.

В идеале, нажать опубликовать -> крутиться лоадер на кнопке оправки -> запрос отправился, кнопка отправить уже не лоадер, но появляется лоадер в фиде, чтобы загрузиться новый тред. Возможно нужно чтобы user запрос отправлялся раньше чем leothread или паралельно.

Также после публикации каждый раз один запрос post-comment падает с 500

https://github.com/Waiviogit/waivio/assets/67378322/e26352c7-ee65-482e-82ed-9ee417511f12

**Comment by Diana-Cherry-8** [comment]
Ошибка валидации не пропадает после добавления имени пользователя и публикации треда


https://github.com/Waiviogit/waivio/assets/67378322/84d796ac-02d2-4627-8db4-2b03df8ebcaf

**Comment by Diana-Cherry-8** [comment]
Если сделать share через facebook, а потом нажать на тот же пост, то сейчас главная ссылка на @leothreads, и открывается главный пост леотред, а не как на вейвио
на facebook: https://waiviodev.com/@leothreads/leothread-2023-12-14-12-46?fbclid=IwAR3AG5tCpUnUJnZRA13Dm0042MRLIVl1s390G9_MqFvq6Ig1hi6IZv_zVEA
на вейвио: https://waiviodev.com/@wiv01/re-leothreads-leothread-2023-12-14-12-46-20231214t142354949z
![image](https://github.com/Waiviogit/waivio/assets/67378322/39dae970-0cb6-4aae-bfb0-ae70b2ec7929)
![image](https://github.com/Waiviogit/waivio/assets/67378322/df46e1fe-aa20-45e5-8eea-10222d299ce3)
![image](https://github.com/Waiviogit/waivio/assets/67378322/ccc57e14-6938-427e-a395-681457eb1e8c)
![image](https://github.com/Waiviogit/waivio/assets/67378322/cc089996-aac7-4d17-8b7c-59c9d4f1700e)

**Comment by Diana-Cherry-8** [comment]
Если share to X, то в посте будет только ссылка текст треда не подтянется 

![image](https://github.com/Waiviogit/waivio/assets/67378322/95c50c74-c623-4539-a18d-aa5c4b560778)

![image](https://github.com/Waiviogit/waivio/assets/67378322/dba1ee39-e59a-44e5-8b6f-c6e286b453c9)

**Comment by Diana-Cherry-8** [comment]
Запрос re-leothreads... (последний тред пользователя?) 
- отправляется на вкладках Post / Comments
- 2 раза отправляется на самой тред вкладки

https://github.com/Waiviogit/waivio/assets/67378322/7d5e7399-eadb-41d4-b572-dfaace30b8a3

**Comment by Diana-Cherry-8** [comment]
Если была открыта вкладка тредов и на жать на профайл, то не переключится на посты, а треды вкладка станет пустой

https://github.com/Waiviogit/waivio/assets/67378322/51cb809b-fb72-43a7-b361-f7581f8651e5

**Comment by katerynapadafa** [comment]
add signature

**Comment by Diana-Cherry-8** [comment]
Если опубликовать и нажать чтобы открылась модалка на том треде, то будет invalid date в модалке и This is a reply to: пустое

https://github.com/Waiviogit/waivio/assets/67378322/e6155afa-bd8d-4380-af5e-71b0a678c68c

**Comment by Diana-Cherry-8** [comment]
waivio после даты, отображается не всегда, иногда пропадает 

https://github.com/Waiviogit/waivio/assets/67378322/704f41d9-ec4a-4f0e-8eb8-0e13a29840b7

**Comment by Diana-Cherry-8** [comment]
Will release Invalid Date в всплывашке вознаграждений и модалке

https://waiviodev.com/@new-way/threads

![image](https://github.com/Waiviogit/waivio/assets/67378322/43d622a6-48e8-4182-b991-873c938c866c)
![image](https://github.com/Waiviogit/waivio/assets/67378322/3f059a70-282f-4142-a119-3a4cc1e69945)

**Comment by Diana-Cherry-8** [comment]
Если поставить лайк, то следующий запрос упадет like-post

https://github.com/Waiviogit/waivio/assets/67378322/b5a138a1-bbbc-4093-b8c3-dffc679acfde

**Comment by Diana-Cherry-8** [comment]
Посмотреть чтобы текст с поля убирался сразу после нажатия на кнопку отправить


https://github.com/Waiviogit/waivio/assets/67378322/47003184-f328-4b92-b216-0c603a50bab5

**Comment by Diana-Cherry-8** [comment]
Нотификашка появляется когда фида уже прогрузилась, если получится то нужно чтобы как только лоадеры начинаются крутиться ее отправлять. Или убрать совсем
![image](https://github.com/Waiviogit/waivio/assets/67378322/8efd62e7-d198-4e70-97fc-910593976add)

**Comment by Diana-Cherry-8** [comment]
На всякий случай проверить
Учитывая что у нас тут нет quick like, тут должен быть обычный механиз поставки лайк, когда мы подписываемся по веб-сокету на блок и ждем когда нам придет ответ (вроде так как-то), например как на апдейтах. Так вот нужно проверить что он тут есть

Пока что если ставишь лайк и долго ждешь, лайк не поставиться, будет крутиться лоадер

![image](https://github.com/Waiviogit/waivio/assets/67378322/a5cc65ac-4a3a-4b20-988b-468317831d9c)

**Comment by Diana-Cherry-8** [comment]
Падает фронт, если добавить emogi и нажать Enter в фиде тредов, или модалки треда


https://github.com/Waiviogit/waivio/assets/67378322/89cd672f-4e11-47d4-833d-a206150fb69a

**Comment by Diana-Cherry-8** [comment]
wiv01 following new-way, на треде в меню на объекте продолжает отображаться Follow вместо Unfollow (в тредах new-way все правильно Unfollow отображается)

https://waiviodev.com/object/pxx-test-product-08011528/threads


https://github.com/Waiviogit/waivio/assets/67378322/53b6d14e-28d5-43a7-822b-6e2cb5b2c00f

**Comment by Diana-Cherry-8** [comment]
Hide post скорее всего нужно убрать, так как оно у нас не работает для тредов

https://github.com/Waiviogit/waivio/assets/67378322/e4caf161-622d-4aa4-9521-d4a71f28f51b

**Comment by Diana-Cherry-8** [comment]
Для пунктов меню в тредах, лучше поменять пост на thread
![image](https://github.com/Waiviogit/waivio/assets/67378322/7ec1a2d2-c9cc-40c1-b21d-acc84d637c13)

**Comment by Diana-Cherry-8** [comment]
Если нажать Edit thread, то иногда ссылка undefined-edit


https://github.com/Waiviogit/waivio/assets/67378322/2818390e-7c23-4569-9f1e-ce6aa84a530c

**Comment by Diana-Cherry-8** [comment]
Падает фронт если ввести букву и нажать Enter под тредом

https://github.com/Waiviogit/waivio/assets/67378322/34fab782-0d8a-461e-af64-df39e991f031

**Comment by Diana-Cherry-8** [comment]
В модалке треда можно поправить слово post заменить на thread для пунктов меню
![image](https://github.com/Waiviogit/waivio/assets/67378322/809d749c-76e8-4c4d-96ca-e19424d18636)

**Comment by Diana-Cherry-8** [comment]
Если начать искать объект (с решетки, или menu object), то будет два меню отображаться

![image](https://github.com/Waiviogit/waivio/assets/67378322/749e31aa-ed83-4d52-aefc-0419b17d357e)
 

https://github.com/Waiviogit/waivio/assets/67378322/c33b39be-885a-4993-b2a9-d3584dca242c

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
quick like на постах не работает

![image](https://github.com/Waiviogit/waivio/assets/67378322/f3f9c42d-9491-4cec-959a-22e40dfc0609)

**Comment by Diana-Cherry-8** [comment]
**Production checked**
