### ISSUE TITLE
Add selection for primary canonical for all user's sites

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6183]
**Back-task** #6182 

yammer 3346
websites / canonical

Add a column titled "Primary Canonical" to the website management interface. This column should contain radio buttons, allowing only one selection across the entire column to designate the primary canonical site. By default, the site that is both active and was created first should be selected as the primary canonical.

In the event that the currently selected primary canonical site is deactivated or deleted, the system should automatically assign primary canonical status to another eligible site, if available. The active (selected) radio button must be displayed in orange for clear visibility.
 

![image](https://github.com/Waiviogit/waivio/assets/67378322/f36debab-7a98-4d64-bc92-1aea3bb1bcf1)

**Comment by Waiviogit** [comment]
to set canonical use custom_json:
id: 'website_canonical'
json: JSON.stringify({host: 'mysitehost.com'})

**Comment by Diana-Cherry-8** [comment]
Активная кнопка, немного "кривая", кружочек внутри не ровно стоит

![image](https://github.com/Waiviogit/waivio/assets/67378322/e02f399c-303d-4230-9768-9245ca726204)

**Comment by Diana-Cherry-8** [comment]
При деактивации сайта, который был выбран как каноникал, нужно переустанавливать primary каноникал на другой (если есть другой активный сайт)

![image](https://github.com/Waiviogit/waivio/assets/67378322/50dfce8e-db09-4efd-9948-2bd9565b279d)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**
