### ISSUE TITLE
[bots / curator] localguide has a curation bot activated to imitate campingchecklist votes. However, there are no votes for updates.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6332]
yammer 3600
bots / curator

localguide has a curation bot activated to imitate campingchecklist votes. However, there are no votes for updates.
https://www.waivio.com/@localguide/activity

![image](https://cdn.discordapp.com/attachments/537744716066848819/1199114777209880576/image.png?ex=65c15da9&is=65aee8a9&hm=cc7aaa9bdd3932739309145dc848c20384ca07f63cb32da510d08f2a8a76eb60&)

**Comment by Waiviogit** [comment]
vote for comments were disabled

**Comment by Diana-Cherry-8** [comment]
**NOT A BUG**
