### ISSUE TITLE
[social.gifts / language] The website https://hivesucre.social.gifts has switched to Spanish. Information about objects in English should not be lost, information in Spanish is simply given priority when it is available.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6595]
yammer 3712
social.gifts / language

The website https://hivesucre.social.gifts has switched to Spanish. Information about objects in English should not be lost, information in Spanish is simply given priority when it is available.

![image](https://waivio.nyc3.digitaloceanspaces.com/1712941976_f4b27cac-3223-40b4-b69e-30a34fe36e3e)

**Comment by Waiviogit** [comment]
objectControl enabled on https://hivesucre.social.gifts/
