### ISSUE TITLE
[waivio / assistant] Create waivio custom support bot using AI technology

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6613]
**Back-task** #5440 

yammer 3743
waivio / assistant

Create waivio custom support bot using AI technology
#6612

**Comment by Diana-Cherry-8** [comment]
Add "Contact" options for pre-prepared prompts. The contact option is a text and link to the Waivio object Threads: https://www.waivio.com/object/ylr-waivio/threads
![image](https://github.com/Waiviogit/waivio/assets/67378322/596f625f-83d1-4ade-b5ad-18725fceac0d)

**Comment by Diana-Cherry-8** [comment]
Подравнять кнопку, может тень добавить вокруг кнопки

![image](https://github.com/Waiviogit/waivio/assets/67378322/409346e7-85e7-418d-a4f3-4cf09b2b91b6)

**Comment by Diana-Cherry-8** [comment]
Нужно понимать url, и показывать ее. 
![image](https://github.com/Waiviogit/waivio/assets/67378322/4acb45af-cdc4-4775-8087-9609b4a406d3)

**Comment by Diana-Cherry-8** [comment]
Попробовать чтобы шрифт самого текста был как на постах 
![image](https://github.com/Waiviogit/waivio/assets/67378322/8f8a026e-df68-472e-b832-1a864534628e)
![image](https://github.com/Waiviogit/waivio/assets/67378322/57415aa4-843c-4f03-a29e-7556ca829fd8)

**Comment by Diana-Cherry-8** [comment]
Анимация на закрытие окошка не очень гладко, и оно медленно опускается вниз. 

https://github.com/Waiviogit/waivio/assets/67378322/b90e42c1-da11-4256-9b41-037d6cf69e7a

https://github.com/Waiviogit/waivio/assets/67378322/62c9be1e-3293-469c-a9ea-fc671efe6e9e

**Comment by Diana-Cherry-8** [comment]
Крестик в поле отображается, но ничего не происходит после нажатия

![image](https://github.com/Waiviogit/waivio/assets/67378322/e7e79f5d-d72b-43bc-8c5e-360da411969b)

**Comment by Diana-Cherry-8** [comment]
Длинный текст пишется в одну строку
![image](https://github.com/Waiviogit/waivio/assets/67378322/a5a78552-e369-46f6-bb5e-92eb34ec104e)

**Comment by Diana-Cherry-8** [comment]
Editor 
После нажатия на Publish AI chat показывается в раскрытом виде
![image](https://github.com/Waiviogit/waivio/assets/67378322/56755ac8-6017-48bb-a3a6-65ae73e775e0)

**Comment by Diana-Cherry-8** [comment]
Кнопку для send нужно поставить посередине высоты поля, сейчас она ближе к концу

![image](https://github.com/Waiviogit/waivio/assets/67378322/96f9aa33-8e3c-4446-8a95-58545987a992)

**Comment by Diana-Cherry-8** [comment]
Кнопка AI становиться прозрачной, при hover
![image](https://github.com/Waiviogit/waivio/assets/67378322/02e72423-edc8-4b3c-8ad2-4ff9d9adca84)

**Comment by Diana-Cherry-8** [comment]
Enter работает на отправку сообщение, но нужно чтобы перенос на новую строку был.
Или можно Shirt + Enter чтобы был перенос на новую строку

https://github.com/Waiviogit/waivio/assets/67378322/ecf6b711-dbdb-4061-bf66-a3b1f8508295

**Comment by Diana-Cherry-8** [comment]
Текст выход за рамки поля, и появляется горизонтальный скролл, при длинном тексте
![image](https://github.com/Waiviogit/waivio/assets/67378322/7ad60fa2-1364-45ea-9ac1-81839e7814de)

**Comment by Diana-Cherry-8** [comment]
Символы и текст с новой строки, после ссылки в ответе

![image](https://github.com/Waiviogit/waivio/assets/67378322/92b45801-6991-403e-80ac-d39cb6d6d2f0)

**Comment by Diana-Cherry-8** [comment]
Поле уходит вниз, и все окно чата заслоняется если вставить большой текст. 
Нужно чтобы поле было до максимальной длинны так 5 строк, и там уже можно передвигаться с помощью курсора (поле price на объектах)

https://github.com/Waiviogit/waivio/assets/67378322/904889ca-bb80-4d83-a418-8f6c78dc8278

https://github.com/Waiviogit/waivio/assets/67378322/0869ada0-71e9-4073-9b63-f3438c36c09b

**Comment by Diana-Cherry-8** [comment]
Поле ввода не очищается, если нажать на кнопку закрыть
(по нажатию на кнопку свернуть пусть так и будет, пусть не очищается)

https://github.com/Waiviogit/waivio/assets/67378322/871fd14b-fff0-4628-9c38-c95f59508201

**Comment by Diana-Cherry-8** [comment]
Добавить font-weight: 500
- для пунктов proofread, translate, about waivio 
- для всего текста в переписке тоже.

![image](https://github.com/Waiviogit/waivio/assets/67378322/e126610d-7a5b-4ecd-94b4-6d1368f53f36)

**Comment by Diana-Cherry-8** [comment]
Ссылка может неправильно показываться
обычный
![image](https://github.com/Waiviogit/waivio/assets/67378322/7a5dd924-f081-437d-9f4e-d0275fcc10ac)

**Comment by Diana-Cherry-8** [comment]
Нужно блокировать кнопку для отправки, пока не будет ответа. Чтобы нельзя было отправлять сообщение один за другим, не дожидаюсь ответа от первого.

https://github.com/Waiviogit/waivio/assets/67378322/4f8bcca8-8389-4773-8902-98748b401d99

**Comment by Diana-Cherry-8** [comment]
После того как пользователь отправил сообщение нужно убирать info и options блок (на других чатах так работает, так это для начального экрана, потом это нужно убирать)
![image](https://github.com/Waiviogit/waivio/assets/67378322/7b575d66-441b-41d3-9aee-f87e22e464ae)

**Comment by Diana-Cherry-8** [comment]
Mobile
Окно чата отрывается на бок, часть не видна
![image](https://github.com/Waiviogit/waivio/assets/67378322/c60771be-aa15-4031-b168-69056fac764e)

**Comment by Diana-Cherry-8** [comment]
Если открыть окно, то кнопка будет отображаться, ее можно скрывать

![image](https://github.com/user-attachments/assets/1aa47db3-6c99-4509-85cf-9ac419b925cf)

**Comment by Diana-Cherry-8** [comment]
Добавить font-weight и для самого текста в поле, чтобы было одинаково во всем окне

![image](https://github.com/user-attachments/assets/24d08247-99f4-46e2-a8a3-040b5dc20ff5)

**Comment by Diana-Cherry-8** [comment]
Ссылки с новой строки в ответе

![image](https://github.com/user-attachments/assets/5615309a-7443-4dfa-a7e9-f26fdf4e24e2)
![image](https://github.com/user-attachments/assets/268f7d9e-b7ca-4a63-b6e7-b2b1292d78fd)

**Comment by Diana-Cherry-8** [comment]
Курсор накладывается на кнопку для отправки, если большой текст в поле
![image](https://github.com/user-attachments/assets/fb42811f-ba06-4cb1-9a32-8e4cc5afb5ee)

**Comment by Diana-Cherry-8** [comment]
Если задать вопрос "Give 10 links with more details", то список будет не помещаться в рамки поля ответа

![image](https://github.com/user-attachments/assets/6f46e64b-287a-434b-b65c-b88171736197)

**Comment by Diana-Cherry-8** [comment]
Отступы внутри сообщений можно увеличить со всех сторон

![image](https://github.com/user-attachments/assets/51dcf504-4aa5-4af2-a3e6-04e064ad05e0)

**Comment by Diana-Cherry-8** [comment]
Увеличить отступ между сообщениями

![image](https://github.com/user-attachments/assets/a7d193cd-9449-48d5-bdc1-e4493e738e21)

**Comment by Diana-Cherry-8** [comment]
Fix стиль кнопки AI:
- Увеличить размер кнопки до 50 px (сейчас 37)
- добавить тень, это вроде норм     box-shadow: rgba(31, 31, 31, 0.5) 2px 2px 5px 0px !important;
- добавить hover - чтобы цвет ставал светлее (например, в модалке Transfer если навести на Continue кнопку)

![image](https://github.com/user-attachments/assets/6c0317b3-9bcc-4cc4-a113-2ba0d9f31826)

![image](https://github.com/user-attachments/assets/781f54a1-52f5-46d3-9748-38eb2f07db90)



https://github.com/user-attachments/assets/2e4e4c9c-b92c-4286-97b2-4e57d6940ac3

**Comment by Diana-Cherry-8** [comment]
Если чат был не начат, то кнопку "выключения чата" можно прятать. Она будет появляться после того как чат будут активен.

![image](https://github.com/user-attachments/assets/4d4dbc14-7f66-4382-84f1-fcc43d355e3d)

**Comment by Diana-Cherry-8** [comment]
Proofread и Transate нужно поменять как они работают.
Нужно, чтобы после нажатия на эти пункты, этот текст ("Proofread" или "Translate to English") вставлялся в текстовое поле, и не отправлялось. Иначе очень странные ответы иногда.

![image](https://github.com/user-attachments/assets/7b0bc61c-7289-4903-a0ef-c92d45686e95)
![image](https://github.com/user-attachments/assets/c980c1e6-15ca-4642-ae76-856b12629f14)

**Comment by Diana-Cherry-8** [comment]
При добавлении Proofread и Translate, лучше по добавлению еще пустую строку добавлять и курсор туда, чтобы курсор был с новой строки


![image](https://github.com/user-attachments/assets/f6109b94-5a84-4dc7-b69b-a083de930fe6)

**Comment by Diana-Cherry-8** [comment]
Добавить две точки после "Proofread:", "Translate to English:" 
Поменять "About Waivio" на строку "Question about Waivio:" и будет работать как proofread/translate

**Comment by Diana-Cherry-8** [comment]
Пустую строку нужно добавлять тоже после всех пунктов, чтобы курсор был с новой строки

![image](https://github.com/user-attachments/assets/84da77a1-5bbf-44c1-952d-2a61b557df79)

**Comment by Diana-Cherry-8** [comment]
Пустая строка если отправить между строками, хотя в самом поле не было


https://github.com/user-attachments/assets/d8f6b621-c441-45e0-ad71-e065a98f0e95

**Comment by Diana-Cherry-8** [comment]
Может курсор тоже можно сразу чтобы он был в поле для написания после нажатия на пункты

![image](https://github.com/user-attachments/assets/2a3579a3-d483-4ac3-b09e-a0f569b11a1d)
![image](https://github.com/user-attachments/assets/6176c7a1-3064-4d24-9bb5-eb9301bc04ac)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**

**Comment by Diana-Cherry-8** [comment]
Поcле нажатия на Publish появляется нижний скролл

https://github.com/user-attachments/assets/4e6f838e-a88f-421e-8e88-72693a90bcfe

![image](https://github.com/user-attachments/assets/cdd48dcf-6cba-4fd5-aef7-4a8b624a14d8)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Mobile
Нужно добавить отступ сверху, иначе не видно верхней панели чата

![image](https://github.com/user-attachments/assets/a9464d51-8b7d-4562-901d-94dba7bd6859)

**Comment by Diana-Cherry-8** [comment]
Уменьшить AI кнопку на десктопе и мобилке

**Comment by Diana-Cherry-8** [comment]
Поправить скрол, при ответе-написании

**Comment by katerynapadafa** [comment]
remove feed scroll

**Comment by Diana-Cherry-8** [comment]
[AI / buttons] use the trash can icon to clear the chat (without closing the window). Zoom in and out to avoid erroneous finger presses. In the future, you can add a Maximize button to expand to full screen on desktop using the ChatGPT type (font, etc.) #6808

**Comment by Diana-Cherry-8** [comment]
[AI / formatting] minor corrections to AI window format #6807

**Comment by Diana-Cherry-8** [comment]
Добавить margin-top: 5px для `.ChatWindow .info`, чтобы текст "How can..." был немного ниже и подравнять расстояние до и после текста.

![image](https://github.com/user-attachments/assets/e6253c0d-ac2c-4bbc-9911-fe4bfd32f840)

**Comment by Diana-Cherry-8** [comment]
Наверно тут должен быть кружочек
![image](https://github.com/user-attachments/assets/c425d205-f7ce-4888-ae94-0c053d202096)
![image](https://github.com/user-attachments/assets/2969b436-8f6d-400a-8bbb-9ef85fb22ddf)

**Comment by Diana-Cherry-8** [comment]
По нажатию на кнопку trash, окно не должно закрывать, только убираться чат и возвращать начальный экран (с текстом How can I help you today?)

https://github.com/user-attachments/assets/f1215d41-d964-422e-9501-348123dc7efa

**Comment by Diana-Cherry-8** [comment]
Mobile
Если водить текст, когда клавиатура телефона открыта, то скрол недо самого начало скролит
![image](https://github.com/user-attachments/assets/a18687ed-a6f9-468b-822b-0c4ef3117c74)

**Comment by Diana-Cherry-8** [comment]
Списки в ответе:
- при ответе в виде нумерованного списка, лишняя пустая строка после ":"


Получается что при это "\n\n1" оно понимает это как две пустые строки должны были поставится, но по факту она одна "/n", так как "/n1" означает уже нумерованный список (наверно). 


ответ который приходит
```
{
  "result": "Waivio's main features include:\n\n1. **Social Media Platform on Blockchain**: Users can post content and interact with others within a decentralized social media ecosystem with crypto-rewards, built on the Hive blockchain.\n   \n2. **Crypto Rewards**: Users earn cryptocurrency for creating and curating content, rewarded for their contributions through the Hive blockchain's reward system.\n\n3. **Customizable Feed**: Personalized content feed including different selections such as Trending, Hot, and News, along with posts from subscribed users and objects.\n\n4. **Public Shop Feature**: Users can add shops to their profiles, allowing them to showcase businesses and products.\n\n5. **Favorites Section**: Enable users to highlight their favorite businesses, places, and restaurants in their profiles.\n\n6. **Wallet Integration**: Users have an in-platform wallet with an Exchange button linked to the Blocktrades widget for cryptocurrency transactions.\n\n7. **User Interactions**: Features like following users, extended search, rewards, and notifications all cater to improving user interactions on the platform.\n\n8. **Mobile Optimization**: Ensures a quality experience on mobile devices with clear search fields, and proper display of vertical photos across multiple resolutions.\n\n9. **Open Source**: Waivio is open-source, inviting contributions and allowing users to see the code and development on GitHub.\n\n10. **Map Integration for Discovery**: Users can discover new places and restaurants with a dynamic map that loads objects as it is moved or zoomed.\n\nFor tutorials and more detailed information, users are guided to visit the Waivio website."
}
```

(Если этот текст вставить в гитхаб, то он правильно распознается без лишних пустых строк)
![image](https://github.com/user-attachments/assets/004f6d9d-a71e-4f78-bae3-81b795653199)

https://github.com/user-attachments/assets/c05b6fdf-7acf-4813-bc34-44a240e3cc6b

**Comment by Diana-Cherry-8** [comment]
Списки в ответе:
- добавить отображение для unorder list

```
{
    "result": "- Matchbot system for automating voting strategies based on configurable minimum voting thresholds.\n- Rewards confirmation page with revised formatting for better clarity on rewards.\n- Dynamic upload of map objects in the Discover section to enhance user exploration experiences.\n- Item counters on lists that provide an aggregate count of items across all sub-lists.\n- Advanced reporting features for guides managing prepaid rewards, which include importing exchange rates for accurate USD reporting.\n- Extended user search capabilities under the Discover section to aid in finding and connecting with more users.\n- Clearing search fields on mobile with a convenient 'X' button.\n- Fixed map field submission form for consistently smooth user-generated content entry.\n- Follow feature optimized for mobile phones for better user engagement on-the-go.\n- Support for vertical photos on mobile devices, accommodating multiple resolutions for better display of images."
}
```

![image](https://github.com/user-attachments/assets/820983d5-5645-4ad3-b768-31567ba5aa44)

**Comment by Diana-Cherry-8** [comment]
Когда пользователь получает ответ, то скрол идет на низ, этого не нужно, чтобы пользователь сразу видел начало ответа.


https://github.com/user-attachments/assets/4b794ad2-5ed2-4260-8449-b100fa9d5ee4

**Comment by Diana-Cherry-8** [comment]
Тайтлы не в основном стиле шрифта бота (цвет наверно не тот)

![image](https://github.com/user-attachments/assets/50283504-0ea0-4d48-abf8-77e67a279d9d)

**Comment by Diana-Cherry-8** [comment]
Mobile
Экран мигает если добавлять\убирать курсор в поле



https://github.com/user-attachments/assets/6dceff91-451b-411f-b433-a10db35bcd53

**Comment by Diana-Cherry-8** [comment]
Есть скролл фиды когда открыт чат

https://github.com/user-attachments/assets/d63987d7-57cd-4290-8ecd-62f70e738fe4

**Comment by Diana-Cherry-8** [comment]
Пропадают иконки верхнего хедера при скролле


https://github.com/user-attachments/assets/0d187291-a64c-46d9-8872-51be78f3e063

**Comment by Diana-Cherry-8** [comment]
Текст не поместился 
![image](https://github.com/user-attachments/assets/e4907f9b-5aac-43c0-ab8e-557971e4d730)
![image](https://github.com/user-attachments/assets/a60cc442-0646-4cec-a3b3-bbd415129d12)

**Comment by Diana-Cherry-8** [comment]
А мы можем ничего не делать со скроллом после получения ответа, просто оно появится, но модалка не будет двигаться. Не нужно специально скролить.

https://github.com/user-attachments/assets/86b86ccd-5630-40d4-9870-f30aeb3c452c

**Comment by Diana-Cherry-8** [comment]
Если эта ссылка на картинку, то будет неправильная url, картинка не откроется. ("Tell me about Product ratings on waivio")
Если ссылка с digitalocean, то брать оригинал.

![image](https://github.com/user-attachments/assets/51e67397-6e7f-4a58-8e3b-94a26735b378)

**Comment by Diana-Cherry-8** [comment]
Иногда от чата GPT может быть 502 ошибка. Можно добавить pop-up с ошибкой. 
There was an error. Please try again.

И может в самом тексте подставить "Sorry, an error has occurred".
![image](https://github.com/user-attachments/assets/3d164be1-b449-43c8-8990-1bd14ce17dd6)
![image](https://github.com/user-attachments/assets/32b34061-7355-41d4-b49e-0b69b3cbbcba)

**Comment by Diana-Cherry-8** [comment]
Добавить немного расстояние, с лева, если это нумерованный список
- когда две цифры, то они в притык к границе поле
- когда три - выходят за границы

![image](https://github.com/user-attachments/assets/79cc54f8-9f32-4067-8186-4654644db3db)

**Comment by Diana-Cherry-8** [comment]
Ломаная картинка, хотя там должны быть ссылка
"Does waivio chrome extension support google map?"

Ответ
```
{
    "result": "Yes, the Waivio Chrome Extension (version 1.4.0) supports Google Maps, as well as OpenStreetMap, allowing users to upload information about businesses directly onto the Hive blockchain. For more details, you can visit their update announcement here: https://www.waivio.com/@social.gifts/waivio-chrome-extension-update-google-maps-and-openstreetmap-integration"
}
```


![image](https://github.com/user-attachments/assets/0fe73de5-6b17-4a84-ae8a-65e83f5f19f7)

**Comment by Diana-Cherry-8** [comment]
Ссылки не отображаются как ссылки.

ответ
```
{
    "result": "To contact the Waivio support team, you can leave a thread at https://www.waivio.com/object/ylr-waivio/threads or navigate through the \"About\" tab to the \"Reviews\" section and click on \"Threads\" to leave a message. If you need further details or wish to explore more about Waivio, please visit https://www.waivio.com/@waiviolabs/waivio-updates-april-4-2020.\n\nAdditional contact options include reaching out through their Discord server at https://discord.gg/sAkPkFv or their social media channels, such as Twitter: https://twitter.com/waiviolabs. For technical inquiries or contributions, you might want to check their GitHub repository: https://github.com/Waiviogit/waivio."
}
```

![image](https://github.com/user-attachments/assets/65d6ebd7-4a4d-4a66-b62f-3d5a4f102843)![image](https://github.com/user-attachments/assets/98d46525-3f71-4fdb-9221-4547eb27ce85)
![image](https://github.com/user-attachments/assets/cf47a2f3-3e7c-472d-a994-419e26ff7dc9)

**Comment by Diana-Cherry-8** [comment]
unorder список начинается на строке отдельной от точки ("Tell me about Product ratings on waivio")
![image](https://github.com/user-attachments/assets/9bcd5c53-d30a-4b69-a917-3179d0e5cf9b)

**Comment by Diana-Cherry-8** [comment]
Возможно ссылки от картинок показывать как картинки, если пришла ссылки с "waivio.nyc3.digitaloceanspaces.com"

![image](https://github.com/user-attachments/assets/074be072-678c-43f6-bbaf-04dc6dcd2764)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Попробовать, может при нажатии на картинку, чтобы в новой вкладке открывалась ссылка картинки
![image](https://github.com/user-attachments/assets/a1ee8b75-b8bb-43f5-9aaa-e8da123fc91d)
![image](https://github.com/user-attachments/assets/85bcacac-bd70-453e-810f-ce5e5ad51e92)

**Comment by Diana-Cherry-8** [comment]
Отступ не всегда есть перед картинкой

![image](https://github.com/user-attachments/assets/a7cd1f05-7732-43c9-b243-513827fcf36f)

**Comment by Diana-Cherry-8** [comment]
Точка в конце ссылки воспринимается как часть ссылки

(prompt: `What should I do if I forget my password? Or how do I recover a hacked account?`)

![image](https://github.com/user-attachments/assets/dbfc54d4-befe-4832-8875-79fa656b5f9e)

**Comment by Diana-Cherry-8** [comment]
Иногда перед картинкой большой отступ (Question about Waivio: Tell me about waivio chrome extensio, use images)
![image](https://github.com/user-attachments/assets/32f930a9-2f0b-4b07-b552-1caeb79702c1)

**Comment by Diana-Cherry-8** [comment]
**DOEN**
