### ISSUE TITLE
[profiles / mentions] add a Mentions tab under Profile / Posts to display posts and comments (minus Threads and posts by the user himself), where this user is mentioned.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6709]
**Front-task** #6710 

yammer 3786
profiles / mentions

add a Mentions tab under Profile / Posts to display posts and comments (minus Threads and posts by the user himself), where this user is mentioned.

![image](https://waivio.nyc3.digitaloceanspaces.com/74723adb530dda56734af03148fc1f33cd22db1958d95cb99a0f3a3699f85470)

**Comment by Diana-Cherry-8** [comment]
Only posts will be in mention

**Comment by Waiviogit** [comment]
https://waiviodev.com/api/docs/#/post/post_api_posts_mentions

**Comment by Diana-Cherry-8** [comment]
Посты того же пользователя показывать не нужно в mentions.
Например, на профайле ctrl-news, в меншинах есть его же посты

![image](https://github.com/user-attachments/assets/3a3ede42-1147-4dee-952c-f1f09ef91eda)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
