### ISSUE TITLE
[user profile / map] Add new tab Map, that will display all business and restaurant object from user's Favorites.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6778]
**Front-task** #6779 

yammer 3827
profile / map

add a map to user profiles that shows all hearted objects that can be displayed on the map (business, restaurant, etc.)

![image](https://waivio.nyc3.digitaloceanspaces.com/45fb728c5f3d32a1ebd9fa090fbc42c64d64b988558b60c12d64e1c1b5a11e9e)

**Comment by Waiviogit** [comment]
https://waiviodev.com/api/docs/#/user/post_api_user__userName__favorites_map

**Comment by Diana-Cherry-8** [comment]
Дефолтный вид карты, это вся карта мира чтобы помещалась.

**Comment by Diana-Cherry-8** [comment]
Новый вид карты, не будет разделения по типам объектов

**Comment by Diana-Cherry-8** [comment]
**Staging checked**
