### ISSUE TITLE
[base object / user] Add the ability to hide site tabs in Configuration when the base object is of the 'user' type. And add user map in main menu for social sites if user is base object.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6879]
**Front-task** #6880 

yammer 3911
base object / user

Add the ability to hide site tabs in Configuration when the base object is of the 'user' type.
https://github.com/Waiviogit/waivio/issues/6878

**Comment by Waiviogit** [comment]
**tabsFilter** new field in the configuration. Array of strings, it is assumed that the field values will be filtered against available menus, or standard values on the user's site.

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
