### ISSUE TITLE
[mentions / messages] Add the ability for messaging between the sponsor and the user for the mention campaign type 

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6884]
**Front-task** #6885 

yammer 3941
mentions / messages

Add the ability for messaging between the sponsor and the user for the mention campaign type.

За основу можно использовать "фиктивный"  главный комментарий, который где-то там создается, и к нему будет крепиться переписка. 
Главный комментарий можно создавать только если переписка инициируется то ли спонсором, то ли пользователем.

Карточки mentions будут отображаться в Messages если будет переписка. 
И в поле для отправки сообщения нужно вернуть для mentions карточек.

![image](https://github.com/user-attachments/assets/a112b563-66fe-485e-842c-04d6d81196ca)

**Comment by Fesmofet** [comment]
1) Create new comment when you are guide or user under campaign activation
parent_author: guideName
paent_permlink: activationPermlink

metadata.waivioRewards.type = 'createMessageThread'
metadata.waivioRewards.activationPermlink = activationPermlink
metadata.waivioRewards.reservationPermlink = reservationPermlink

2)to user card will be added field
messagesPermlink : `${author}/${permlink}` and this comment will be use for messaging


3) send message by parsing messagesPermlink const [parent_author, parent_permlink] = messagesPermlink.split('/')

metadata.waivioRewards.type = 'campaignMessage'
metadata.waivioRewards.reservationPermlink = reservationPermlink

4) on notifications if you have reservationPermlink field use it instead parent_permlink

**Comment by Diana-Cherry-8** [comment]
Пустая страница Messages, если нажать на уведомление user asked about mention. Если авторизоваться как спонсор кампании. (wiv01).
Там должна открываться только выбранная кампания, с раскрытыми сообщениями, как для review.

Если авторизоваться как исполнитель, и тоже нажать на уведомление {sponsor} replied on your comment. Также будет пустая страница.

![Image](https://github.com/user-attachments/assets/ed428844-029c-4df1-90a2-f492b7fb530e)

![Image](https://github.com/user-attachments/assets/d6934e52-69be-4146-bf93-0648d8a95286)

**Comment by Diana-Cherry-8** [comment]
Пустая страница Messages, Если авторизоваться как исполнитель, и нажать на уведомление {sponsor} replied on your comment для mention кампании. (new-way)
Там должна открываться только выбранная кампания, с раскрытыми сообщениями, как для review.



![Image](https://github.com/user-attachments/assets/d6934e52-69be-4146-bf93-0648d8a95286)

**Comment by Diana-Cherry-8** [comment]
При отправке самого 1го сообщения для меншин, если это спонсор, отправляется странное сообщение, что спонсор сделал резервацию.
![image](https://github.com/user-attachments/assets/69aafc71-161b-4139-8a5f-4c192e43eae4)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
