### ISSUE TITLE
[site / affiliate] Add the ability to assign multiple affiliate codes to a single site for the same affiliate program

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6914]
**Front-task** #6915 

yammer 3894
social.gifts / affiliate

allow adding multiple affiliate codes for the same affiliate program and give the site owner the ability to set the proportion of the frequency of using these codes. Editing can be done according to the sample weights of objects in posts.

![image](https://waivio.nyc3.digitaloceanspaces.com/7c0852ffcde7acea282d4228cc8a1c27d0e454ebd4920e50c351bf1c46c3273f)

**Comment by Waiviogit** [comment]
https://github.com/Waiviogit/objects-bot/blob/dev/docs/objectFields.md

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
