### ISSUE TITLE
[sites / ai search] Search for users in the AI assistant should be limited to those who are recently active and have expertise in the site's default hashtag.

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6997]
yammer 3973
sites / ai search

Search by users in the AI assistant for the site should be limited to:
- Only users with expertise in the site's default hashtag.
- Users who have been recently active.
![Image](https://github.com/user-attachments/assets/003e3986-7de8-4e61-bad2-5f86935b703f)
![Image](https://github.com/user-attachments/assets/6d35bc76-af2e-4168-9147-1fda60f135e2)

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Fesmofet** [comment]
the last activity filter is set to 180 days, make sure you don't mix up the requirement with the group task.

**Comment by Diana-Cherry-8** [comment]
**Staging checked**

**Comment by Diana-Cherry-8** [comment]
**Production checked**
