### ISSUE TITLE
[ai / advanced] Add the ability to activate advanced AI and to update information for the AI assistant for site owner

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#7043]
**Front-task** #7044 

yammer 3964
ai / advanced

Add the ability to activate advanced AI and to update information for the AI assistant for site owner
#7045

**Comment by Fesmofet** [comment]
configuration.advancedAI: boolean = if set true starts create store task

https://waiviodev.com/api/docs/#/sites/post_api_sites_assistant_custom
for button manual update once 24h

**Comment by Diana-Cherry-8** [comment]
Configuration
Галочка ставится и убирается для всех сайтов сразу.

(Были галки на обоих -> убрать на одном -> в результате убралось сразу на всех сайтах пользователя. И если добавить галку для одного, то на всех будет.) 

https://github.com/user-attachments/assets/621dce7e-8c41-4cbd-9329-98d932e8f88d

**Comment by Diana-Cherry-8** [comment]
Я создала новый сайт, и не активировала чекбокс в Configuration, но сам AI отвечал с объектами с sitemap.

(Изначально было несколько сайтов, на одном было активировано, потом создано новый, на новом ответы были точно такие как на других с активированным чекбоксом, по отношению к объектам)

**Comment by Diana-Cherry-8** [comment]
**DONE**
